// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "conv.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic conv::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic conv::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<11> conv::ap_ST_fsm_state1 = "1";
const sc_lv<11> conv::ap_ST_fsm_state2 = "10";
const sc_lv<11> conv::ap_ST_fsm_state3 = "100";
const sc_lv<11> conv::ap_ST_fsm_state4 = "1000";
const sc_lv<11> conv::ap_ST_fsm_state5 = "10000";
const sc_lv<11> conv::ap_ST_fsm_state6 = "100000";
const sc_lv<11> conv::ap_ST_fsm_state7 = "1000000";
const sc_lv<11> conv::ap_ST_fsm_state8 = "10000000";
const sc_lv<11> conv::ap_ST_fsm_state9 = "100000000";
const sc_lv<11> conv::ap_ST_fsm_state10 = "1000000000";
const sc_lv<11> conv::ap_ST_fsm_state11 = "10000000000";
const sc_lv<32> conv::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> conv::ap_const_lv32_1 = "1";
const sc_lv<1> conv::ap_const_lv1_1 = "1";
const sc_lv<32> conv::ap_const_lv32_2 = "10";
const sc_lv<32> conv::ap_const_lv32_3 = "11";
const sc_lv<1> conv::ap_const_lv1_0 = "0";
const sc_lv<32> conv::ap_const_lv32_4 = "100";
const sc_lv<32> conv::ap_const_lv32_5 = "101";
const sc_lv<32> conv::ap_const_lv32_6 = "110";
const sc_lv<32> conv::ap_const_lv32_7 = "111";
const sc_lv<32> conv::ap_const_lv32_8 = "1000";
const sc_lv<32> conv::ap_const_lv32_9 = "1001";
const sc_lv<6> conv::ap_const_lv6_0 = "000000";
const sc_lv<5> conv::ap_const_lv5_0 = "00000";
const sc_lv<32> conv::ap_const_lv32_A = "1010";
const sc_lv<9> conv::ap_const_lv9_0 = "000000000";
const sc_lv<2> conv::ap_const_lv2_0 = "00";
const sc_lv<5> conv::ap_const_lv5_1E = "11110";
const sc_lv<5> conv::ap_const_lv5_1F = "11111";
const sc_lv<6> conv::ap_const_lv6_1 = "1";
const sc_lv<5> conv::ap_const_lv5_1 = "1";
const sc_lv<3> conv::ap_const_lv3_0 = "000";
const sc_lv<2> conv::ap_const_lv2_3 = "11";
const sc_lv<2> conv::ap_const_lv2_1 = "1";
const bool conv::ap_const_boolean_1 = true;

conv::conv(sc_module_name name) : sc_module(name), mVcdFile(0) {
    w_conv1_U = new conv_w_conv1("w_conv1_U");
    w_conv1_U->clk(ap_clk);
    w_conv1_U->reset(ap_rst);
    w_conv1_U->address0(w_conv1_address0);
    w_conv1_U->ce0(w_conv1_ce0);
    w_conv1_U->q0(w_conv1_q0);
    w_conv2_U = new conv_w_conv2("w_conv2_U");
    w_conv2_U->clk(ap_clk);
    w_conv2_U->reset(ap_rst);
    w_conv2_U->address0(w_conv2_address0);
    w_conv2_U->ce0(w_conv2_ce0);
    w_conv2_U->q0(w_conv2_q0);
    dut_mac_muladd_9ncud_U9 = new dut_mac_muladd_9ncud<1,1,9,5,5,13>("dut_mac_muladd_9ncud_U9");
    dut_mac_muladd_9ncud_U9->din0(grp_fu_729_p0);
    dut_mac_muladd_9ncud_U9->din1(grp_fu_729_p1);
    dut_mac_muladd_9ncud_U9->din2(grp_fu_729_p2);
    dut_mac_muladd_9ncud_U9->dout(grp_fu_729_p3);
    dut_mac_muladd_9ndEe_U10 = new dut_mac_muladd_9ndEe<1,1,9,6,5,13>("dut_mac_muladd_9ndEe_U10");
    dut_mac_muladd_9ndEe_U10->din0(grp_fu_735_p0);
    dut_mac_muladd_9ndEe_U10->din1(grp_fu_735_p1);
    dut_mac_muladd_9ndEe_U10->din2(grp_fu_735_p2);
    dut_mac_muladd_9ndEe_U10->dout(grp_fu_735_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_I_cast_fu_366_p1);
    sensitive << ( I );

    SC_METHOD(thread_L_read_read_fu_90_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( L );

    SC_METHOD(thread_O_cast21_cast_fu_340_p1);
    sensitive << ( O_fu_334_p2 );

    SC_METHOD(thread_O_fu_334_p2);
    sensitive << ( trunc_ln59_fu_330_p1 );

    SC_METHOD(thread_add_ln16_fu_348_p2);
    sensitive << ( trunc_ln59_fu_330_p1 );

    SC_METHOD(thread_add_ln74_1_fu_568_p2);
    sensitive << ( y_0_reg_202 );
    sensitive << ( zext_ln73_1_fu_552_p1 );

    SC_METHOD(thread_add_ln74_fu_509_p2);
    sensitive << ( zext_ln72_fu_493_p1 );
    sensitive << ( x_0_reg_190 );

    SC_METHOD(thread_add_ln76_1_fu_479_p2);
    sensitive << ( zext_ln76_2_fu_475_p1 );
    sensitive << ( zext_ln76_1_fu_463_p1 );

    SC_METHOD(thread_add_ln76_2_fu_625_p2);
    sensitive << ( zext_ln72_reg_876 );
    sensitive << ( sub_ln76_fu_619_p2 );

    SC_METHOD(thread_add_ln76_3_fu_433_p2);
    sensitive << ( zext_ln76_reg_784 );
    sensitive << ( phi_mul2_reg_249 );

    SC_METHOD(thread_add_ln76_4_fu_438_p2);
    sensitive << ( zext_ln75_reg_779 );
    sensitive << ( phi_mul_reg_237 );

    SC_METHOD(thread_add_ln76_fu_458_p2);
    sensitive << ( zext_ln64_reg_794 );
    sensitive << ( phi_mul2_reg_249 );

    SC_METHOD(thread_and_ln16_1_fu_590_p2);
    sensitive << ( and_ln16_fu_585_p2 );
    sensitive << ( icmp_ln16_2_fu_574_p2 );

    SC_METHOD(thread_and_ln16_fu_585_p2);
    sensitive << ( icmp_ln16_1_reg_899 );
    sensitive << ( icmp_ln16_3_fu_580_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln64_fu_378_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln64_fu_378_p2 );

    SC_METHOD(thread_c_fu_503_p2);
    sensitive << ( c_0_reg_284 );

    SC_METHOD(thread_grp_fu_729_p0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln66_fu_413_p2 );
    sensitive << ( grp_fu_729_p00 );

    SC_METHOD(thread_grp_fu_729_p00);
    sensitive << ( tmp29_fu_424_p2 );

    SC_METHOD(thread_grp_fu_729_p1);
    sensitive << ( O_cast21_cast_reg_758 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln66_fu_413_p2 );

    SC_METHOD(thread_grp_fu_729_p2);
    sensitive << ( zext_ln65_reg_812 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln66_fu_413_p2 );

    SC_METHOD(thread_grp_fu_735_p0);
    sensitive << ( or_ln16_reg_932 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_fu_735_p00 );

    SC_METHOD(thread_grp_fu_735_p00);
    sensitive << ( tmp31_reg_917 );

    SC_METHOD(thread_grp_fu_735_p1);
    sensitive << ( I_cast_reg_789 );
    sensitive << ( or_ln16_reg_932 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_grp_fu_735_p2);
    sensitive << ( zext_ln74_reg_889 );
    sensitive << ( or_ln16_reg_932 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_icmp_ln1494_fu_723_p2);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( shl_ln1_fu_711_p3 );
    sensitive << ( sext_ln1494_fu_719_p1 );

    SC_METHOD(thread_icmp_ln16_1_fu_525_p2);
    sensitive << ( add_ln16_reg_768 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln72_fu_497_p2 );
    sensitive << ( add_ln74_fu_509_p2 );

    SC_METHOD(thread_icmp_ln16_2_fu_574_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln73_fu_556_p2 );
    sensitive << ( add_ln74_1_fu_568_p2 );

    SC_METHOD(thread_icmp_ln16_3_fu_580_p2);
    sensitive << ( add_ln16_reg_768 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln73_fu_556_p2 );
    sensitive << ( add_ln74_1_fu_568_p2 );

    SC_METHOD(thread_icmp_ln16_fu_519_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln72_fu_497_p2 );
    sensitive << ( add_ln74_fu_509_p2 );

    SC_METHOD(thread_icmp_ln64_fu_378_p2);
    sensitive << ( N );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln64_1_fu_374_p1 );

    SC_METHOD(thread_icmp_ln65_fu_398_p2);
    sensitive << ( O_reg_752 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( x_0_reg_190 );

    SC_METHOD(thread_icmp_ln66_fu_413_p2);
    sensitive << ( O_reg_752 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( y_0_reg_202 );

    SC_METHOD(thread_icmp_ln69_fu_447_p2);
    sensitive << ( trunc_ln69_reg_774 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( zext_ln69_fu_443_p1 );

    SC_METHOD(thread_icmp_ln72_fu_497_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( c_0_reg_284 );

    SC_METHOD(thread_icmp_ln73_fu_556_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( r_0_reg_319 );

    SC_METHOD(thread_input_r_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( zext_ln77_fu_673_p1 );

    SC_METHOD(thread_input_r_ce0);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_m_fu_452_p2);
    sensitive << ( m_0_reg_226 );

    SC_METHOD(thread_mac_num_2_fu_662_p3);
    sensitive << ( or_ln16_fu_657_p2 );
    sensitive << ( mac_num_1_reg_307 );
    sensitive << ( mac_num_fu_645_p2 );

    SC_METHOD(thread_mac_num_fu_645_p2);
    sensitive << ( mac_num_1_reg_307 );

    SC_METHOD(thread_mul_ln68_fu_389_p0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( mul_ln68_fu_389_p00 );

    SC_METHOD(thread_mul_ln68_fu_389_p00);
    sensitive << ( n_0_reg_179 );

    SC_METHOD(thread_mul_ln68_fu_389_p1);
    sensitive << ( zext_ln68_reg_763 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_mul_ln68_fu_389_p2);
    sensitive << ( mul_ln68_fu_389_p0 );
    sensitive << ( mul_ln68_fu_389_p1 );

    SC_METHOD(thread_n_fu_383_p2);
    sensitive << ( n_0_reg_179 );

    SC_METHOD(thread_one_out_2_fu_704_p3);
    sensitive << ( or_ln16_reg_932 );
    sensitive << ( one_out_1_reg_295 );
    sensitive << ( one_out_fu_698_p2 );

    SC_METHOD(thread_one_out_fu_698_p2);
    sensitive << ( one_out_1_reg_295 );
    sensitive << ( zext_ln78_fu_694_p1 );

    SC_METHOD(thread_or_ln16_fu_657_p2);
    sensitive << ( icmp_ln16_reg_894 );
    sensitive << ( xor_ln16_fu_651_p2 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( zext_ln85_reg_866 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( icmp_ln1494_reg_962 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_r_fu_562_p2);
    sensitive << ( r_0_reg_319 );

    SC_METHOD(thread_select_ln77_fu_677_p3);
    sensitive << ( L );
    sensitive << ( w_conv1_load_reg_947 );
    sensitive << ( w_conv2_load_reg_952 );

    SC_METHOD(thread_sext_ln1494_fu_719_p1);
    sensitive << ( threshold_V_q0 );

    SC_METHOD(thread_sext_ln76_fu_630_p1);
    sensitive << ( add_ln76_2_fu_625_p2 );

    SC_METHOD(thread_sext_ln77_fu_639_p1);
    sensitive << ( w_index_fu_634_p2 );

    SC_METHOD(thread_shl_ln1_fu_711_p3);
    sensitive << ( p_Val2_s_reg_214 );

    SC_METHOD(thread_shl_ln76_1_fu_607_p3);
    sensitive << ( r_0_reg_319 );

    SC_METHOD(thread_shl_ln83_fu_530_p2);
    sensitive << ( one_out_0_reg_260 );

    SC_METHOD(thread_shl_ln_fu_467_p3);
    sensitive << ( add_ln76_fu_458_p2 );

    SC_METHOD(thread_sub_ln76_fu_619_p2);
    sensitive << ( zext_ln73_1_fu_552_p1 );
    sensitive << ( zext_ln76_4_fu_615_p1 );

    SC_METHOD(thread_sub_ln83_fu_536_p2);
    sensitive << ( p_Val2_s_reg_214 );
    sensitive << ( mac_num_0_reg_272 );

    SC_METHOD(thread_sum_fu_542_p2);
    sensitive << ( sub_ln83_fu_536_p2 );
    sensitive << ( shl_ln83_fu_530_p2 );

    SC_METHOD(thread_threshold_V_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( zext_ln85_fu_489_p1 );

    SC_METHOD(thread_threshold_V_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_tmp29_fu_424_p2);
    sensitive << ( mul_ln68_reg_807 );
    sensitive << ( zext_ln66_fu_409_p1 );

    SC_METHOD(thread_tmp31_fu_602_p2);
    sensitive << ( zext_ln66_reg_825 );
    sensitive << ( tmp7_fu_596_p2 );

    SC_METHOD(thread_tmp7_fu_596_p2);
    sensitive << ( phi_mul_reg_237 );
    sensitive << ( zext_ln73_fu_548_p1 );

    SC_METHOD(thread_trunc_ln59_fu_330_p1);
    sensitive << ( I );

    SC_METHOD(thread_trunc_ln69_fu_354_p1);
    sensitive << ( M );

    SC_METHOD(thread_w_conv1_address0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( sext_ln77_fu_639_p1 );

    SC_METHOD(thread_w_conv1_ce0);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_w_conv2_address0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( sext_ln77_fu_639_p1 );

    SC_METHOD(thread_w_conv2_ce0);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_w_index_fu_634_p2);
    sensitive << ( zext_ln76_3_reg_861 );
    sensitive << ( sext_ln76_fu_630_p1 );

    SC_METHOD(thread_x_fu_403_p2);
    sensitive << ( x_0_reg_190 );

    SC_METHOD(thread_xor_ln16_fu_651_p2);
    sensitive << ( and_ln16_1_fu_590_p2 );

    SC_METHOD(thread_xor_ln78_1_fu_688_p2);
    sensitive << ( input_r_q0 );
    sensitive << ( xor_ln78_fu_682_p2 );

    SC_METHOD(thread_xor_ln78_fu_682_p2);
    sensitive << ( select_ln77_fu_677_p3 );

    SC_METHOD(thread_y_fu_418_p2);
    sensitive << ( y_0_reg_202 );

    SC_METHOD(thread_zext_ln64_1_fu_374_p1);
    sensitive << ( n_0_reg_179 );

    SC_METHOD(thread_zext_ln64_fu_370_p1);
    sensitive << ( n_0_reg_179 );

    SC_METHOD(thread_zext_ln65_fu_394_p1);
    sensitive << ( x_0_reg_190 );

    SC_METHOD(thread_zext_ln66_fu_409_p1);
    sensitive << ( y_0_reg_202 );

    SC_METHOD(thread_zext_ln68_fu_344_p1);
    sensitive << ( O_fu_334_p2 );

    SC_METHOD(thread_zext_ln69_fu_443_p1);
    sensitive << ( m_0_reg_226 );

    SC_METHOD(thread_zext_ln72_fu_493_p1);
    sensitive << ( c_0_reg_284 );

    SC_METHOD(thread_zext_ln73_1_fu_552_p1);
    sensitive << ( r_0_reg_319 );

    SC_METHOD(thread_zext_ln73_fu_548_p1);
    sensitive << ( r_0_reg_319 );

    SC_METHOD(thread_zext_ln74_fu_515_p1);
    sensitive << ( add_ln74_fu_509_p2 );

    SC_METHOD(thread_zext_ln75_fu_358_p1);
    sensitive << ( I );

    SC_METHOD(thread_zext_ln76_1_fu_463_p1);
    sensitive << ( add_ln76_fu_458_p2 );

    SC_METHOD(thread_zext_ln76_2_fu_475_p1);
    sensitive << ( shl_ln_fu_467_p3 );

    SC_METHOD(thread_zext_ln76_3_fu_485_p1);
    sensitive << ( add_ln76_1_fu_479_p2 );

    SC_METHOD(thread_zext_ln76_4_fu_615_p1);
    sensitive << ( shl_ln76_1_fu_607_p3 );

    SC_METHOD(thread_zext_ln76_fu_362_p1);
    sensitive << ( N );

    SC_METHOD(thread_zext_ln77_fu_673_p1);
    sensitive << ( grp_fu_735_p3 );

    SC_METHOD(thread_zext_ln78_fu_694_p1);
    sensitive << ( xor_ln78_1_fu_688_p2 );

    SC_METHOD(thread_zext_ln85_fu_489_p1);
    sensitive << ( o_index_reg_838 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln64_fu_378_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln66_fu_413_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln69_fu_447_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln72_fu_497_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln73_fu_556_p2 );
    sensitive << ( icmp_ln65_fu_398_p2 );

    ap_CS_fsm = "00000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "conv_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r_address0, "(port)input_r_address0");
    sc_trace(mVcdFile, input_r_ce0, "(port)input_r_ce0");
    sc_trace(mVcdFile, input_r_q0, "(port)input_r_q0");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
    sc_trace(mVcdFile, threshold_V_address0, "(port)threshold_V_address0");
    sc_trace(mVcdFile, threshold_V_ce0, "(port)threshold_V_ce0");
    sc_trace(mVcdFile, threshold_V_q0, "(port)threshold_V_q0");
    sc_trace(mVcdFile, M, "(port)M");
    sc_trace(mVcdFile, N, "(port)N");
    sc_trace(mVcdFile, I, "(port)I");
    sc_trace(mVcdFile, L, "(port)L");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, w_conv1_address0, "w_conv1_address0");
    sc_trace(mVcdFile, w_conv1_ce0, "w_conv1_ce0");
    sc_trace(mVcdFile, w_conv1_q0, "w_conv1_q0");
    sc_trace(mVcdFile, w_conv2_address0, "w_conv2_address0");
    sc_trace(mVcdFile, w_conv2_ce0, "w_conv2_ce0");
    sc_trace(mVcdFile, w_conv2_q0, "w_conv2_q0");
    sc_trace(mVcdFile, L_read_read_fu_90_p2, "L_read_read_fu_90_p2");
    sc_trace(mVcdFile, O_fu_334_p2, "O_fu_334_p2");
    sc_trace(mVcdFile, O_reg_752, "O_reg_752");
    sc_trace(mVcdFile, O_cast21_cast_fu_340_p1, "O_cast21_cast_fu_340_p1");
    sc_trace(mVcdFile, O_cast21_cast_reg_758, "O_cast21_cast_reg_758");
    sc_trace(mVcdFile, zext_ln68_fu_344_p1, "zext_ln68_fu_344_p1");
    sc_trace(mVcdFile, zext_ln68_reg_763, "zext_ln68_reg_763");
    sc_trace(mVcdFile, add_ln16_fu_348_p2, "add_ln16_fu_348_p2");
    sc_trace(mVcdFile, add_ln16_reg_768, "add_ln16_reg_768");
    sc_trace(mVcdFile, trunc_ln69_fu_354_p1, "trunc_ln69_fu_354_p1");
    sc_trace(mVcdFile, trunc_ln69_reg_774, "trunc_ln69_reg_774");
    sc_trace(mVcdFile, zext_ln75_fu_358_p1, "zext_ln75_fu_358_p1");
    sc_trace(mVcdFile, zext_ln75_reg_779, "zext_ln75_reg_779");
    sc_trace(mVcdFile, zext_ln76_fu_362_p1, "zext_ln76_fu_362_p1");
    sc_trace(mVcdFile, zext_ln76_reg_784, "zext_ln76_reg_784");
    sc_trace(mVcdFile, I_cast_fu_366_p1, "I_cast_fu_366_p1");
    sc_trace(mVcdFile, I_cast_reg_789, "I_cast_reg_789");
    sc_trace(mVcdFile, zext_ln64_fu_370_p1, "zext_ln64_fu_370_p1");
    sc_trace(mVcdFile, zext_ln64_reg_794, "zext_ln64_reg_794");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, n_fu_383_p2, "n_fu_383_p2");
    sc_trace(mVcdFile, n_reg_802, "n_reg_802");
    sc_trace(mVcdFile, mul_ln68_fu_389_p2, "mul_ln68_fu_389_p2");
    sc_trace(mVcdFile, mul_ln68_reg_807, "mul_ln68_reg_807");
    sc_trace(mVcdFile, icmp_ln64_fu_378_p2, "icmp_ln64_fu_378_p2");
    sc_trace(mVcdFile, zext_ln65_fu_394_p1, "zext_ln65_fu_394_p1");
    sc_trace(mVcdFile, zext_ln65_reg_812, "zext_ln65_reg_812");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, x_fu_403_p2, "x_fu_403_p2");
    sc_trace(mVcdFile, x_reg_820, "x_reg_820");
    sc_trace(mVcdFile, zext_ln66_fu_409_p1, "zext_ln66_fu_409_p1");
    sc_trace(mVcdFile, zext_ln66_reg_825, "zext_ln66_reg_825");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, y_fu_418_p2, "y_fu_418_p2");
    sc_trace(mVcdFile, y_reg_833, "y_reg_833");
    sc_trace(mVcdFile, grp_fu_729_p3, "grp_fu_729_p3");
    sc_trace(mVcdFile, o_index_reg_838, "o_index_reg_838");
    sc_trace(mVcdFile, icmp_ln66_fu_413_p2, "icmp_ln66_fu_413_p2");
    sc_trace(mVcdFile, add_ln76_3_fu_433_p2, "add_ln76_3_fu_433_p2");
    sc_trace(mVcdFile, add_ln76_3_reg_843, "add_ln76_3_reg_843");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, add_ln76_4_fu_438_p2, "add_ln76_4_fu_438_p2");
    sc_trace(mVcdFile, add_ln76_4_reg_848, "add_ln76_4_reg_848");
    sc_trace(mVcdFile, m_fu_452_p2, "m_fu_452_p2");
    sc_trace(mVcdFile, m_reg_856, "m_reg_856");
    sc_trace(mVcdFile, zext_ln76_3_fu_485_p1, "zext_ln76_3_fu_485_p1");
    sc_trace(mVcdFile, zext_ln76_3_reg_861, "zext_ln76_3_reg_861");
    sc_trace(mVcdFile, icmp_ln69_fu_447_p2, "icmp_ln69_fu_447_p2");
    sc_trace(mVcdFile, zext_ln85_fu_489_p1, "zext_ln85_fu_489_p1");
    sc_trace(mVcdFile, zext_ln85_reg_866, "zext_ln85_reg_866");
    sc_trace(mVcdFile, zext_ln72_fu_493_p1, "zext_ln72_fu_493_p1");
    sc_trace(mVcdFile, zext_ln72_reg_876, "zext_ln72_reg_876");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, c_fu_503_p2, "c_fu_503_p2");
    sc_trace(mVcdFile, c_reg_884, "c_reg_884");
    sc_trace(mVcdFile, zext_ln74_fu_515_p1, "zext_ln74_fu_515_p1");
    sc_trace(mVcdFile, zext_ln74_reg_889, "zext_ln74_reg_889");
    sc_trace(mVcdFile, icmp_ln72_fu_497_p2, "icmp_ln72_fu_497_p2");
    sc_trace(mVcdFile, icmp_ln16_fu_519_p2, "icmp_ln16_fu_519_p2");
    sc_trace(mVcdFile, icmp_ln16_reg_894, "icmp_ln16_reg_894");
    sc_trace(mVcdFile, icmp_ln16_1_fu_525_p2, "icmp_ln16_1_fu_525_p2");
    sc_trace(mVcdFile, icmp_ln16_1_reg_899, "icmp_ln16_1_reg_899");
    sc_trace(mVcdFile, sum_fu_542_p2, "sum_fu_542_p2");
    sc_trace(mVcdFile, r_fu_562_p2, "r_fu_562_p2");
    sc_trace(mVcdFile, r_reg_912, "r_reg_912");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp31_fu_602_p2, "tmp31_fu_602_p2");
    sc_trace(mVcdFile, tmp31_reg_917, "tmp31_reg_917");
    sc_trace(mVcdFile, icmp_ln73_fu_556_p2, "icmp_ln73_fu_556_p2");
    sc_trace(mVcdFile, or_ln16_fu_657_p2, "or_ln16_fu_657_p2");
    sc_trace(mVcdFile, or_ln16_reg_932, "or_ln16_reg_932");
    sc_trace(mVcdFile, mac_num_2_fu_662_p3, "mac_num_2_fu_662_p3");
    sc_trace(mVcdFile, mac_num_2_reg_937, "mac_num_2_reg_937");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, w_conv1_load_reg_947, "w_conv1_load_reg_947");
    sc_trace(mVcdFile, w_conv2_load_reg_952, "w_conv2_load_reg_952");
    sc_trace(mVcdFile, one_out_2_fu_704_p3, "one_out_2_fu_704_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, icmp_ln1494_fu_723_p2, "icmp_ln1494_fu_723_p2");
    sc_trace(mVcdFile, icmp_ln1494_reg_962, "icmp_ln1494_reg_962");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, n_0_reg_179, "n_0_reg_179");
    sc_trace(mVcdFile, icmp_ln65_fu_398_p2, "icmp_ln65_fu_398_p2");
    sc_trace(mVcdFile, x_0_reg_190, "x_0_reg_190");
    sc_trace(mVcdFile, y_0_reg_202, "y_0_reg_202");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, p_Val2_s_reg_214, "p_Val2_s_reg_214");
    sc_trace(mVcdFile, m_0_reg_226, "m_0_reg_226");
    sc_trace(mVcdFile, phi_mul_reg_237, "phi_mul_reg_237");
    sc_trace(mVcdFile, phi_mul2_reg_249, "phi_mul2_reg_249");
    sc_trace(mVcdFile, one_out_0_reg_260, "one_out_0_reg_260");
    sc_trace(mVcdFile, mac_num_0_reg_272, "mac_num_0_reg_272");
    sc_trace(mVcdFile, c_0_reg_284, "c_0_reg_284");
    sc_trace(mVcdFile, one_out_1_reg_295, "one_out_1_reg_295");
    sc_trace(mVcdFile, mac_num_1_reg_307, "mac_num_1_reg_307");
    sc_trace(mVcdFile, r_0_reg_319, "r_0_reg_319");
    sc_trace(mVcdFile, sext_ln77_fu_639_p1, "sext_ln77_fu_639_p1");
    sc_trace(mVcdFile, zext_ln77_fu_673_p1, "zext_ln77_fu_673_p1");
    sc_trace(mVcdFile, trunc_ln59_fu_330_p1, "trunc_ln59_fu_330_p1");
    sc_trace(mVcdFile, zext_ln64_1_fu_374_p1, "zext_ln64_1_fu_374_p1");
    sc_trace(mVcdFile, mul_ln68_fu_389_p0, "mul_ln68_fu_389_p0");
    sc_trace(mVcdFile, mul_ln68_fu_389_p1, "mul_ln68_fu_389_p1");
    sc_trace(mVcdFile, tmp29_fu_424_p2, "tmp29_fu_424_p2");
    sc_trace(mVcdFile, zext_ln69_fu_443_p1, "zext_ln69_fu_443_p1");
    sc_trace(mVcdFile, add_ln76_fu_458_p2, "add_ln76_fu_458_p2");
    sc_trace(mVcdFile, shl_ln_fu_467_p3, "shl_ln_fu_467_p3");
    sc_trace(mVcdFile, zext_ln76_2_fu_475_p1, "zext_ln76_2_fu_475_p1");
    sc_trace(mVcdFile, zext_ln76_1_fu_463_p1, "zext_ln76_1_fu_463_p1");
    sc_trace(mVcdFile, add_ln76_1_fu_479_p2, "add_ln76_1_fu_479_p2");
    sc_trace(mVcdFile, add_ln74_fu_509_p2, "add_ln74_fu_509_p2");
    sc_trace(mVcdFile, sub_ln83_fu_536_p2, "sub_ln83_fu_536_p2");
    sc_trace(mVcdFile, shl_ln83_fu_530_p2, "shl_ln83_fu_530_p2");
    sc_trace(mVcdFile, zext_ln73_1_fu_552_p1, "zext_ln73_1_fu_552_p1");
    sc_trace(mVcdFile, add_ln74_1_fu_568_p2, "add_ln74_1_fu_568_p2");
    sc_trace(mVcdFile, icmp_ln16_3_fu_580_p2, "icmp_ln16_3_fu_580_p2");
    sc_trace(mVcdFile, and_ln16_fu_585_p2, "and_ln16_fu_585_p2");
    sc_trace(mVcdFile, icmp_ln16_2_fu_574_p2, "icmp_ln16_2_fu_574_p2");
    sc_trace(mVcdFile, zext_ln73_fu_548_p1, "zext_ln73_fu_548_p1");
    sc_trace(mVcdFile, tmp7_fu_596_p2, "tmp7_fu_596_p2");
    sc_trace(mVcdFile, shl_ln76_1_fu_607_p3, "shl_ln76_1_fu_607_p3");
    sc_trace(mVcdFile, zext_ln76_4_fu_615_p1, "zext_ln76_4_fu_615_p1");
    sc_trace(mVcdFile, sub_ln76_fu_619_p2, "sub_ln76_fu_619_p2");
    sc_trace(mVcdFile, add_ln76_2_fu_625_p2, "add_ln76_2_fu_625_p2");
    sc_trace(mVcdFile, sext_ln76_fu_630_p1, "sext_ln76_fu_630_p1");
    sc_trace(mVcdFile, w_index_fu_634_p2, "w_index_fu_634_p2");
    sc_trace(mVcdFile, and_ln16_1_fu_590_p2, "and_ln16_1_fu_590_p2");
    sc_trace(mVcdFile, xor_ln16_fu_651_p2, "xor_ln16_fu_651_p2");
    sc_trace(mVcdFile, mac_num_fu_645_p2, "mac_num_fu_645_p2");
    sc_trace(mVcdFile, grp_fu_735_p3, "grp_fu_735_p3");
    sc_trace(mVcdFile, select_ln77_fu_677_p3, "select_ln77_fu_677_p3");
    sc_trace(mVcdFile, xor_ln78_fu_682_p2, "xor_ln78_fu_682_p2");
    sc_trace(mVcdFile, xor_ln78_1_fu_688_p2, "xor_ln78_1_fu_688_p2");
    sc_trace(mVcdFile, zext_ln78_fu_694_p1, "zext_ln78_fu_694_p1");
    sc_trace(mVcdFile, one_out_fu_698_p2, "one_out_fu_698_p2");
    sc_trace(mVcdFile, shl_ln1_fu_711_p3, "shl_ln1_fu_711_p3");
    sc_trace(mVcdFile, sext_ln1494_fu_719_p1, "sext_ln1494_fu_719_p1");
    sc_trace(mVcdFile, grp_fu_729_p0, "grp_fu_729_p0");
    sc_trace(mVcdFile, grp_fu_729_p1, "grp_fu_729_p1");
    sc_trace(mVcdFile, grp_fu_729_p2, "grp_fu_729_p2");
    sc_trace(mVcdFile, grp_fu_735_p0, "grp_fu_735_p0");
    sc_trace(mVcdFile, grp_fu_735_p1, "grp_fu_735_p1");
    sc_trace(mVcdFile, grp_fu_735_p2, "grp_fu_735_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, grp_fu_729_p00, "grp_fu_729_p00");
    sc_trace(mVcdFile, grp_fu_735_p00, "grp_fu_735_p00");
    sc_trace(mVcdFile, mul_ln68_fu_389_p00, "mul_ln68_fu_389_p00");
#endif

    }
}

conv::~conv() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete w_conv1_U;
    delete w_conv2_U;
    delete dut_mac_muladd_9ncud_U9;
    delete dut_mac_muladd_9ndEe_U10;
}

void conv::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln73_fu_556_p2.read()))) {
        c_0_reg_284 = c_reg_884.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln69_fu_447_p2.read()))) {
        c_0_reg_284 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln72_fu_497_p2.read()))) {
        m_0_reg_226 = m_reg_856.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(icmp_ln66_fu_413_p2.read(), ap_const_lv1_0))) {
        m_0_reg_226 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln73_fu_556_p2.read()))) {
        mac_num_0_reg_272 = mac_num_1_reg_307.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln69_fu_447_p2.read()))) {
        mac_num_0_reg_272 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        mac_num_1_reg_307 = mac_num_2_reg_937.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln72_fu_497_p2.read()))) {
        mac_num_1_reg_307 = mac_num_0_reg_272.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln65_fu_398_p2.read()))) {
        n_0_reg_179 = n_reg_802.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        n_0_reg_179 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln73_fu_556_p2.read()))) {
        one_out_0_reg_260 = one_out_1_reg_295.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln69_fu_447_p2.read()))) {
        one_out_0_reg_260 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        one_out_1_reg_295 = one_out_2_fu_704_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln72_fu_497_p2.read()))) {
        one_out_1_reg_295 = one_out_0_reg_260.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln72_fu_497_p2.read()))) {
        p_Val2_s_reg_214 = sum_fu_542_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(icmp_ln66_fu_413_p2.read(), ap_const_lv1_0))) {
        p_Val2_s_reg_214 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln72_fu_497_p2.read()))) {
        phi_mul2_reg_249 = add_ln76_3_reg_843.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(icmp_ln66_fu_413_p2.read(), ap_const_lv1_0))) {
        phi_mul2_reg_249 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln72_fu_497_p2.read()))) {
        phi_mul_reg_237 = add_ln76_4_reg_848.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(icmp_ln66_fu_413_p2.read(), ap_const_lv1_0))) {
        phi_mul_reg_237 = ap_const_lv9_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        r_0_reg_319 = r_reg_912.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln72_fu_497_p2.read()))) {
        r_0_reg_319 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln66_fu_413_p2.read()))) {
        x_0_reg_190 = x_reg_820.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln64_fu_378_p2.read(), ap_const_lv1_1))) {
        x_0_reg_190 = ap_const_lv5_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        y_0_reg_202 = y_reg_833.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln65_fu_398_p2.read()))) {
        y_0_reg_202 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        I_cast_reg_789 = I_cast_fu_366_p1.read();
        O_cast21_cast_reg_758 = O_cast21_cast_fu_340_p1.read();
        O_reg_752 = O_fu_334_p2.read();
        add_ln16_reg_768 = add_ln16_fu_348_p2.read();
        trunc_ln69_reg_774 = trunc_ln69_fu_354_p1.read();
        zext_ln68_reg_763 = zext_ln68_fu_344_p1.read();
        zext_ln75_reg_779 = zext_ln75_fu_358_p1.read();
        zext_ln76_reg_784 = zext_ln76_fu_362_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        add_ln76_3_reg_843 = add_ln76_3_fu_433_p2.read();
        add_ln76_4_reg_848 = add_ln76_4_fu_438_p2.read();
        m_reg_856 = m_fu_452_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        c_reg_884 = c_fu_503_p2.read();
        zext_ln72_reg_876 = zext_ln72_fu_493_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        icmp_ln1494_reg_962 = icmp_ln1494_fu_723_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln72_fu_497_p2.read()))) {
        icmp_ln16_1_reg_899 = icmp_ln16_1_fu_525_p2.read();
        icmp_ln16_reg_894 = icmp_ln16_fu_519_p2.read();
        zext_ln74_reg_889 = zext_ln74_fu_515_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln73_fu_556_p2.read()))) {
        mac_num_2_reg_937 = mac_num_2_fu_662_p3.read();
        or_ln16_reg_932 = or_ln16_fu_657_p2.read();
        tmp31_reg_917 = tmp31_fu_602_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln64_fu_378_p2.read(), ap_const_lv1_1))) {
        mul_ln68_reg_807 = mul_ln68_fu_389_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        n_reg_802 = n_fu_383_p2.read();
        zext_ln64_reg_794 = zext_ln64_fu_370_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln66_fu_413_p2.read(), ap_const_lv1_0))) {
        o_index_reg_838 = grp_fu_729_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        r_reg_912 = r_fu_562_p2.read();
    }
    if ((esl_seteq<1,1,1>(L_read_read_fu_90_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        w_conv1_load_reg_947 = w_conv1_q0.read();
    }
    if ((esl_seteq<1,1,1>(L_read_read_fu_90_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        w_conv2_load_reg_952 = w_conv2_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        x_reg_820 = x_fu_403_p2.read();
        zext_ln65_reg_812 = zext_ln65_fu_394_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        y_reg_833 = y_fu_418_p2.read();
        zext_ln66_reg_825 = zext_ln66_fu_409_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln69_fu_447_p2.read()))) {
        zext_ln76_3_reg_861 = zext_ln76_3_fu_485_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln69_fu_447_p2.read()))) {
        zext_ln85_reg_866 = zext_ln85_fu_489_p1.read();
    }
}

void conv::thread_I_cast_fu_366_p1() {
    I_cast_fu_366_p1 = esl_zext<13,6>(I.read());
}

void conv::thread_L_read_read_fu_90_p2() {
    L_read_read_fu_90_p2 = L.read();
}

void conv::thread_O_cast21_cast_fu_340_p1() {
    O_cast21_cast_fu_340_p1 = esl_zext<13,5>(O_fu_334_p2.read());
}

void conv::thread_O_fu_334_p2() {
    O_fu_334_p2 = (!ap_const_lv5_1E.is_01() || !trunc_ln59_fu_330_p1.read().is_01())? sc_lv<5>(): (sc_bigint<5>(ap_const_lv5_1E) + sc_biguint<5>(trunc_ln59_fu_330_p1.read()));
}

void conv::thread_add_ln16_fu_348_p2() {
    add_ln16_fu_348_p2 = (!ap_const_lv5_1F.is_01() || !trunc_ln59_fu_330_p1.read().is_01())? sc_lv<5>(): (sc_bigint<5>(ap_const_lv5_1F) + sc_biguint<5>(trunc_ln59_fu_330_p1.read()));
}

void conv::thread_add_ln74_1_fu_568_p2() {
    add_ln74_1_fu_568_p2 = (!zext_ln73_1_fu_552_p1.read().is_01() || !y_0_reg_202.read().is_01())? sc_lv<5>(): (sc_biguint<5>(zext_ln73_1_fu_552_p1.read()) + sc_biguint<5>(y_0_reg_202.read()));
}

void conv::thread_add_ln74_fu_509_p2() {
    add_ln74_fu_509_p2 = (!zext_ln72_fu_493_p1.read().is_01() || !x_0_reg_190.read().is_01())? sc_lv<5>(): (sc_biguint<5>(zext_ln72_fu_493_p1.read()) + sc_biguint<5>(x_0_reg_190.read()));
}

void conv::thread_add_ln76_1_fu_479_p2() {
    add_ln76_1_fu_479_p2 = (!zext_ln76_2_fu_475_p1.read().is_01() || !zext_ln76_1_fu_463_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(zext_ln76_2_fu_475_p1.read()) + sc_biguint<13>(zext_ln76_1_fu_463_p1.read()));
}

void conv::thread_add_ln76_2_fu_625_p2() {
    add_ln76_2_fu_625_p2 = (!zext_ln72_reg_876.read().is_01() || !sub_ln76_fu_619_p2.read().is_01())? sc_lv<5>(): (sc_biguint<5>(zext_ln72_reg_876.read()) + sc_biguint<5>(sub_ln76_fu_619_p2.read()));
}

void conv::thread_add_ln76_3_fu_433_p2() {
    add_ln76_3_fu_433_p2 = (!phi_mul2_reg_249.read().is_01() || !zext_ln76_reg_784.read().is_01())? sc_lv<9>(): (sc_biguint<9>(phi_mul2_reg_249.read()) + sc_biguint<9>(zext_ln76_reg_784.read()));
}

void conv::thread_add_ln76_4_fu_438_p2() {
    add_ln76_4_fu_438_p2 = (!phi_mul_reg_237.read().is_01() || !zext_ln75_reg_779.read().is_01())? sc_lv<9>(): (sc_biguint<9>(phi_mul_reg_237.read()) + sc_biguint<9>(zext_ln75_reg_779.read()));
}

void conv::thread_add_ln76_fu_458_p2() {
    add_ln76_fu_458_p2 = (!zext_ln64_reg_794.read().is_01() || !phi_mul2_reg_249.read().is_01())? sc_lv<9>(): (sc_biguint<9>(zext_ln64_reg_794.read()) + sc_biguint<9>(phi_mul2_reg_249.read()));
}

void conv::thread_and_ln16_1_fu_590_p2() {
    and_ln16_1_fu_590_p2 = (and_ln16_fu_585_p2.read() & icmp_ln16_2_fu_574_p2.read());
}

void conv::thread_and_ln16_fu_585_p2() {
    and_ln16_fu_585_p2 = (icmp_ln16_1_reg_899.read() & icmp_ln16_3_fu_580_p2.read());
}

void conv::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void conv::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void conv::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void conv::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void conv::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void conv::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void conv::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void conv::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void conv::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void conv::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void conv::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void conv::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln64_fu_378_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void conv::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void conv::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln64_fu_378_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void conv::thread_c_fu_503_p2() {
    c_fu_503_p2 = (!c_0_reg_284.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(c_0_reg_284.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv::thread_grp_fu_729_p0() {
    grp_fu_729_p0 =  (sc_lv<9>) (grp_fu_729_p00.read());
}

void conv::thread_grp_fu_729_p00() {
    grp_fu_729_p00 = esl_zext<13,9>(tmp29_fu_424_p2.read());
}

void conv::thread_grp_fu_729_p1() {
    grp_fu_729_p1 =  (sc_lv<5>) (O_cast21_cast_reg_758.read());
}

void conv::thread_grp_fu_729_p2() {
    grp_fu_729_p2 =  (sc_lv<5>) (zext_ln65_reg_812.read());
}

void conv::thread_grp_fu_735_p0() {
    grp_fu_735_p0 =  (sc_lv<9>) (grp_fu_735_p00.read());
}

void conv::thread_grp_fu_735_p00() {
    grp_fu_735_p00 = esl_zext<13,9>(tmp31_reg_917.read());
}

void conv::thread_grp_fu_735_p1() {
    grp_fu_735_p1 =  (sc_lv<6>) (I_cast_reg_789.read());
}

void conv::thread_grp_fu_735_p2() {
    grp_fu_735_p2 =  (sc_lv<5>) (zext_ln74_reg_889.read());
}

void conv::thread_icmp_ln1494_fu_723_p2() {
    icmp_ln1494_fu_723_p2 = (!shl_ln1_fu_711_p3.read().is_01() || !sext_ln1494_fu_719_p1.read().is_01())? sc_lv<1>(): (sc_bigint<34>(shl_ln1_fu_711_p3.read()) > sc_bigint<34>(sext_ln1494_fu_719_p1.read()));
}

void conv::thread_icmp_ln16_1_fu_525_p2() {
    icmp_ln16_1_fu_525_p2 = (!add_ln16_reg_768.read().is_01() || !add_ln74_fu_509_p2.read().is_01())? sc_lv<1>(): (sc_biguint<5>(add_ln16_reg_768.read()) > sc_biguint<5>(add_ln74_fu_509_p2.read()));
}

void conv::thread_icmp_ln16_2_fu_574_p2() {
    icmp_ln16_2_fu_574_p2 = (!add_ln74_1_fu_568_p2.read().is_01() || !ap_const_lv5_0.is_01())? sc_lv<1>(): sc_lv<1>(add_ln74_1_fu_568_p2.read() != ap_const_lv5_0);
}

void conv::thread_icmp_ln16_3_fu_580_p2() {
    icmp_ln16_3_fu_580_p2 = (!add_ln16_reg_768.read().is_01() || !add_ln74_1_fu_568_p2.read().is_01())? sc_lv<1>(): (sc_biguint<5>(add_ln16_reg_768.read()) > sc_biguint<5>(add_ln74_1_fu_568_p2.read()));
}

void conv::thread_icmp_ln16_fu_519_p2() {
    icmp_ln16_fu_519_p2 = (!add_ln74_fu_509_p2.read().is_01() || !ap_const_lv5_0.is_01())? sc_lv<1>(): sc_lv<1>(add_ln74_fu_509_p2.read() == ap_const_lv5_0);
}

void conv::thread_icmp_ln64_fu_378_p2() {
    icmp_ln64_fu_378_p2 = (!zext_ln64_1_fu_374_p1.read().is_01() || !N.read().is_01())? sc_lv<1>(): (sc_bigint<7>(zext_ln64_1_fu_374_p1.read()) < sc_bigint<7>(N.read()));
}

void conv::thread_icmp_ln65_fu_398_p2() {
    icmp_ln65_fu_398_p2 = (!x_0_reg_190.read().is_01() || !O_reg_752.read().is_01())? sc_lv<1>(): sc_lv<1>(x_0_reg_190.read() == O_reg_752.read());
}

void conv::thread_icmp_ln66_fu_413_p2() {
    icmp_ln66_fu_413_p2 = (!y_0_reg_202.read().is_01() || !O_reg_752.read().is_01())? sc_lv<1>(): sc_lv<1>(y_0_reg_202.read() == O_reg_752.read());
}

void conv::thread_icmp_ln69_fu_447_p2() {
    icmp_ln69_fu_447_p2 = (!zext_ln69_fu_443_p1.read().is_01() || !trunc_ln69_reg_774.read().is_01())? sc_lv<1>(): (sc_bigint<6>(zext_ln69_fu_443_p1.read()) < sc_bigint<6>(trunc_ln69_reg_774.read()));
}

void conv::thread_icmp_ln72_fu_497_p2() {
    icmp_ln72_fu_497_p2 = (!c_0_reg_284.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(c_0_reg_284.read() == ap_const_lv2_3);
}

void conv::thread_icmp_ln73_fu_556_p2() {
    icmp_ln73_fu_556_p2 = (!r_0_reg_319.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(r_0_reg_319.read() == ap_const_lv2_3);
}

void conv::thread_input_r_address0() {
    input_r_address0 =  (sc_lv<13>) (zext_ln77_fu_673_p1.read());
}

void conv::thread_input_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        input_r_ce0 = ap_const_logic_1;
    } else {
        input_r_ce0 = ap_const_logic_0;
    }
}

void conv::thread_m_fu_452_p2() {
    m_fu_452_p2 = (!m_0_reg_226.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(m_0_reg_226.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv::thread_mac_num_2_fu_662_p3() {
    mac_num_2_fu_662_p3 = (!or_ln16_fu_657_p2.read()[0].is_01())? sc_lv<32>(): ((or_ln16_fu_657_p2.read()[0].to_bool())? mac_num_1_reg_307.read(): mac_num_fu_645_p2.read());
}

void conv::thread_mac_num_fu_645_p2() {
    mac_num_fu_645_p2 = (!mac_num_1_reg_307.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(mac_num_1_reg_307.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void conv::thread_mul_ln68_fu_389_p0() {
    mul_ln68_fu_389_p0 =  (sc_lv<6>) (mul_ln68_fu_389_p00.read());
}

void conv::thread_mul_ln68_fu_389_p00() {
    mul_ln68_fu_389_p00 = esl_zext<9,6>(n_0_reg_179.read());
}

void conv::thread_mul_ln68_fu_389_p1() {
    mul_ln68_fu_389_p1 =  (sc_lv<5>) (zext_ln68_reg_763.read());
}

void conv::thread_mul_ln68_fu_389_p2() {
    mul_ln68_fu_389_p2 = (!mul_ln68_fu_389_p0.read().is_01() || !mul_ln68_fu_389_p1.read().is_01())? sc_lv<9>(): sc_biguint<6>(mul_ln68_fu_389_p0.read()) * sc_biguint<5>(mul_ln68_fu_389_p1.read());
}

void conv::thread_n_fu_383_p2() {
    n_fu_383_p2 = (!n_0_reg_179.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(n_0_reg_179.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void conv::thread_one_out_2_fu_704_p3() {
    one_out_2_fu_704_p3 = (!or_ln16_reg_932.read()[0].is_01())? sc_lv<32>(): ((or_ln16_reg_932.read()[0].to_bool())? one_out_1_reg_295.read(): one_out_fu_698_p2.read());
}

void conv::thread_one_out_fu_698_p2() {
    one_out_fu_698_p2 = (!one_out_1_reg_295.read().is_01() || !zext_ln78_fu_694_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(one_out_1_reg_295.read()) + sc_biguint<32>(zext_ln78_fu_694_p1.read()));
}

void conv::thread_or_ln16_fu_657_p2() {
    or_ln16_fu_657_p2 = (icmp_ln16_reg_894.read() | xor_ln16_fu_651_p2.read());
}

void conv::thread_output_r_address0() {
    output_r_address0 =  (sc_lv<13>) (zext_ln85_reg_866.read());
}

void conv::thread_output_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void conv::thread_output_r_d0() {
    output_r_d0 = icmp_ln1494_reg_962.read();
}

void conv::thread_output_r_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void conv::thread_r_fu_562_p2() {
    r_fu_562_p2 = (!r_0_reg_319.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(r_0_reg_319.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv::thread_select_ln77_fu_677_p3() {
    select_ln77_fu_677_p3 = (!L.read()[0].is_01())? sc_lv<1>(): ((L.read()[0].to_bool())? w_conv2_load_reg_952.read(): w_conv1_load_reg_947.read());
}

void conv::thread_sext_ln1494_fu_719_p1() {
    sext_ln1494_fu_719_p1 = esl_sext<34,8>(threshold_V_q0.read());
}

void conv::thread_sext_ln76_fu_630_p1() {
    sext_ln76_fu_630_p1 = esl_sext<14,5>(add_ln76_2_fu_625_p2.read());
}

void conv::thread_sext_ln77_fu_639_p1() {
    sext_ln77_fu_639_p1 = esl_sext<64,14>(w_index_fu_634_p2.read());
}

void conv::thread_shl_ln1_fu_711_p3() {
    shl_ln1_fu_711_p3 = esl_concat<32,2>(p_Val2_s_reg_214.read(), ap_const_lv2_0);
}

void conv::thread_shl_ln76_1_fu_607_p3() {
    shl_ln76_1_fu_607_p3 = esl_concat<2,2>(r_0_reg_319.read(), ap_const_lv2_0);
}

void conv::thread_shl_ln83_fu_530_p2() {
    shl_ln83_fu_530_p2 = (!ap_const_lv32_1.is_01())? sc_lv<32>(): one_out_0_reg_260.read() << (unsigned short)ap_const_lv32_1.to_uint();
}

void conv::thread_shl_ln_fu_467_p3() {
    shl_ln_fu_467_p3 = esl_concat<9,3>(add_ln76_fu_458_p2.read(), ap_const_lv3_0);
}

void conv::thread_sub_ln76_fu_619_p2() {
    sub_ln76_fu_619_p2 = (!zext_ln76_4_fu_615_p1.read().is_01() || !zext_ln73_1_fu_552_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(zext_ln76_4_fu_615_p1.read()) - sc_biguint<5>(zext_ln73_1_fu_552_p1.read()));
}

void conv::thread_sub_ln83_fu_536_p2() {
    sub_ln83_fu_536_p2 = (!p_Val2_s_reg_214.read().is_01() || !mac_num_0_reg_272.read().is_01())? sc_lv<32>(): (sc_biguint<32>(p_Val2_s_reg_214.read()) - sc_biguint<32>(mac_num_0_reg_272.read()));
}

void conv::thread_sum_fu_542_p2() {
    sum_fu_542_p2 = (!sub_ln83_fu_536_p2.read().is_01() || !shl_ln83_fu_530_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sub_ln83_fu_536_p2.read()) + sc_biguint<32>(shl_ln83_fu_530_p2.read()));
}

void conv::thread_threshold_V_address0() {
    threshold_V_address0 =  (sc_lv<13>) (zext_ln85_fu_489_p1.read());
}

void conv::thread_threshold_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        threshold_V_ce0 = ap_const_logic_1;
    } else {
        threshold_V_ce0 = ap_const_logic_0;
    }
}

void conv::thread_tmp29_fu_424_p2() {
    tmp29_fu_424_p2 = (!zext_ln66_fu_409_p1.read().is_01() || !mul_ln68_reg_807.read().is_01())? sc_lv<9>(): (sc_biguint<9>(zext_ln66_fu_409_p1.read()) + sc_biguint<9>(mul_ln68_reg_807.read()));
}

void conv::thread_tmp31_fu_602_p2() {
    tmp31_fu_602_p2 = (!tmp7_fu_596_p2.read().is_01() || !zext_ln66_reg_825.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp7_fu_596_p2.read()) + sc_biguint<9>(zext_ln66_reg_825.read()));
}

void conv::thread_tmp7_fu_596_p2() {
    tmp7_fu_596_p2 = (!phi_mul_reg_237.read().is_01() || !zext_ln73_fu_548_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(phi_mul_reg_237.read()) + sc_biguint<9>(zext_ln73_fu_548_p1.read()));
}

void conv::thread_trunc_ln59_fu_330_p1() {
    trunc_ln59_fu_330_p1 = I.read().range(5-1, 0);
}

void conv::thread_trunc_ln69_fu_354_p1() {
    trunc_ln69_fu_354_p1 = M.read().range(6-1, 0);
}

void conv::thread_w_conv1_address0() {
    w_conv1_address0 =  (sc_lv<13>) (sext_ln77_fu_639_p1.read());
}

void conv::thread_w_conv1_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        w_conv1_ce0 = ap_const_logic_1;
    } else {
        w_conv1_ce0 = ap_const_logic_0;
    }
}

void conv::thread_w_conv2_address0() {
    w_conv2_address0 =  (sc_lv<13>) (sext_ln77_fu_639_p1.read());
}

void conv::thread_w_conv2_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        w_conv2_ce0 = ap_const_logic_1;
    } else {
        w_conv2_ce0 = ap_const_logic_0;
    }
}

void conv::thread_w_index_fu_634_p2() {
    w_index_fu_634_p2 = (!sext_ln76_fu_630_p1.read().is_01() || !zext_ln76_3_reg_861.read().is_01())? sc_lv<14>(): (sc_bigint<14>(sext_ln76_fu_630_p1.read()) + sc_biguint<14>(zext_ln76_3_reg_861.read()));
}

void conv::thread_x_fu_403_p2() {
    x_fu_403_p2 = (!x_0_reg_190.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(x_0_reg_190.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv::thread_xor_ln16_fu_651_p2() {
    xor_ln16_fu_651_p2 = (and_ln16_1_fu_590_p2.read() ^ ap_const_lv1_1);
}

void conv::thread_xor_ln78_1_fu_688_p2() {
    xor_ln78_1_fu_688_p2 = (input_r_q0.read() ^ xor_ln78_fu_682_p2.read());
}

void conv::thread_xor_ln78_fu_682_p2() {
    xor_ln78_fu_682_p2 = (select_ln77_fu_677_p3.read() ^ ap_const_lv1_1);
}

void conv::thread_y_fu_418_p2() {
    y_fu_418_p2 = (!y_0_reg_202.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(y_0_reg_202.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv::thread_zext_ln64_1_fu_374_p1() {
    zext_ln64_1_fu_374_p1 = esl_zext<7,6>(n_0_reg_179.read());
}

void conv::thread_zext_ln64_fu_370_p1() {
    zext_ln64_fu_370_p1 = esl_zext<9,6>(n_0_reg_179.read());
}

void conv::thread_zext_ln65_fu_394_p1() {
    zext_ln65_fu_394_p1 = esl_zext<13,5>(x_0_reg_190.read());
}

void conv::thread_zext_ln66_fu_409_p1() {
    zext_ln66_fu_409_p1 = esl_zext<9,5>(y_0_reg_202.read());
}

void conv::thread_zext_ln68_fu_344_p1() {
    zext_ln68_fu_344_p1 = esl_zext<9,5>(O_fu_334_p2.read());
}

void conv::thread_zext_ln69_fu_443_p1() {
    zext_ln69_fu_443_p1 = esl_zext<6,5>(m_0_reg_226.read());
}

void conv::thread_zext_ln72_fu_493_p1() {
    zext_ln72_fu_493_p1 = esl_zext<5,2>(c_0_reg_284.read());
}

void conv::thread_zext_ln73_1_fu_552_p1() {
    zext_ln73_1_fu_552_p1 = esl_zext<5,2>(r_0_reg_319.read());
}

void conv::thread_zext_ln73_fu_548_p1() {
    zext_ln73_fu_548_p1 = esl_zext<9,2>(r_0_reg_319.read());
}

void conv::thread_zext_ln74_fu_515_p1() {
    zext_ln74_fu_515_p1 = esl_zext<13,5>(add_ln74_fu_509_p2.read());
}

void conv::thread_zext_ln75_fu_358_p1() {
    zext_ln75_fu_358_p1 = esl_zext<9,6>(I.read());
}

void conv::thread_zext_ln76_1_fu_463_p1() {
    zext_ln76_1_fu_463_p1 = esl_zext<13,9>(add_ln76_fu_458_p2.read());
}

void conv::thread_zext_ln76_2_fu_475_p1() {
    zext_ln76_2_fu_475_p1 = esl_zext<13,12>(shl_ln_fu_467_p3.read());
}

void conv::thread_zext_ln76_3_fu_485_p1() {
    zext_ln76_3_fu_485_p1 = esl_zext<14,13>(add_ln76_1_fu_479_p2.read());
}

void conv::thread_zext_ln76_4_fu_615_p1() {
    zext_ln76_4_fu_615_p1 = esl_zext<5,4>(shl_ln76_1_fu_607_p3.read());
}

void conv::thread_zext_ln76_fu_362_p1() {
    zext_ln76_fu_362_p1 = esl_zext<9,7>(N.read());
}

void conv::thread_zext_ln77_fu_673_p1() {
    zext_ln77_fu_673_p1 = esl_zext<64,13>(grp_fu_735_p3.read());
}

void conv::thread_zext_ln78_fu_694_p1() {
    zext_ln78_fu_694_p1 = esl_zext<32,1>(xor_ln78_1_fu_688_p2.read());
}

void conv::thread_zext_ln85_fu_489_p1() {
    zext_ln85_fu_489_p1 = esl_zext<64,13>(o_index_reg_838.read());
}

void conv::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln64_fu_378_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln65_fu_398_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln66_fu_413_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln69_fu_447_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln72_fu_497_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln73_fu_556_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXX";
            break;
    }
}

}

