// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dut_max_pool_HH_
#define _dut_max_pool_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct dut_max_pool : public sc_module {
    // Port declarations 15
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<13> > input_r_address0;
    sc_out< sc_logic > input_r_ce0;
    sc_in< sc_lv<1> > input_r_q0;
    sc_out< sc_lv<13> > output_r_address0;
    sc_out< sc_logic > output_r_ce0;
    sc_out< sc_logic > output_r_we0;
    sc_out< sc_lv<1> > output_r_d0;
    sc_in< sc_lv<7> > M;
    sc_in< sc_lv<6> > I;


    // Module declarations
    dut_max_pool(sc_module_name name);
    SC_HAS_PROCESS(dut_max_pool);

    ~dut_max_pool();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<11> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_28;
    sc_signal< sc_lv<4> > O_fu_207_p4;
    sc_signal< sc_lv<4> > O_reg_431;
    sc_signal< sc_lv<11> > O_cast10_cast1_fu_217_p1;
    sc_signal< sc_lv<11> > O_cast10_cast1_reg_437;
    sc_signal< sc_lv<8> > O_cast10_cast_fu_221_p1;
    sc_signal< sc_lv<8> > O_cast10_cast_reg_442;
    sc_signal< sc_lv<13> > i_2_fu_231_p2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_68;
    sc_signal< sc_lv<9> > I_cast2_fu_242_p1;
    sc_signal< sc_lv<9> > I_cast2_reg_455;
    sc_signal< sc_lv<1> > exitcond3_fu_225_p2;
    sc_signal< sc_lv<13> > I_cast_fu_245_p1;
    sc_signal< sc_lv<13> > I_cast_reg_460;
    sc_signal< sc_lv<9> > next_mul_fu_248_p2;
    sc_signal< sc_lv<9> > next_mul_reg_465;
    sc_signal< sc_logic > ap_sig_cseq_ST_st3_fsm_2;
    sc_signal< bool > ap_sig_86;
    sc_signal< sc_lv<6> > m_2_fu_266_p2;
    sc_signal< sc_lv<6> > m_2_reg_473;
    sc_signal< sc_lv<8> > tmp_2_fu_272_p2;
    sc_signal< sc_lv<8> > tmp_2_reg_478;
    sc_signal< sc_lv<1> > tmp_9_fu_261_p2;
    sc_signal< sc_lv<11> > x_cast6_fu_277_p1;
    sc_signal< sc_lv<11> > x_cast6_reg_483;
    sc_signal< sc_logic > ap_sig_cseq_ST_st4_fsm_3;
    sc_signal< bool > ap_sig_103;
    sc_signal< sc_lv<4> > x_3_fu_286_p2;
    sc_signal< sc_lv<4> > x_3_reg_491;
    sc_signal< sc_lv<13> > tmp_5_cast_fu_298_p1;
    sc_signal< sc_lv<13> > tmp_5_cast_reg_496;
    sc_signal< sc_lv<1> > exitcond4_fu_281_p2;
    sc_signal< sc_lv<4> > y_3_fu_311_p2;
    sc_signal< sc_lv<4> > y_3_reg_504;
    sc_signal< sc_logic > ap_sig_cseq_ST_st5_fsm_4;
    sc_signal< bool > ap_sig_119;
    sc_signal< sc_lv<11> > tmp7_fu_326_p2;
    sc_signal< sc_lv<11> > tmp7_reg_509;
    sc_signal< sc_lv<1> > exitcond2_fu_306_p2;
    sc_signal< sc_lv<11> > o_index_fu_331_p2;
    sc_signal< sc_lv<11> > o_index_reg_514;
    sc_signal< sc_logic > ap_sig_cseq_ST_st6_fsm_5;
    sc_signal< bool > ap_sig_133;
    sc_signal< sc_lv<9> > tmp_6_cast_fu_341_p1;
    sc_signal< sc_lv<9> > tmp_6_cast_reg_519;
    sc_signal< sc_lv<13> > c_cast4_fu_345_p1;
    sc_signal< sc_lv<13> > c_cast4_reg_524;
    sc_signal< sc_logic > ap_sig_cseq_ST_st7_fsm_6;
    sc_signal< bool > ap_sig_144;
    sc_signal< sc_lv<2> > c_2_fu_355_p2;
    sc_signal< sc_lv<2> > c_2_reg_532;
    sc_signal< sc_lv<2> > r_1_fu_375_p2;
    sc_signal< sc_lv<2> > r_1_reg_540;
    sc_signal< sc_logic > ap_sig_cseq_ST_st8_fsm_7;
    sc_signal< bool > ap_sig_155;
    sc_signal< sc_lv<9> > tmp8_fu_387_p2;
    sc_signal< sc_lv<9> > tmp8_reg_545;
    sc_signal< sc_lv<1> > exitcond_fu_369_p2;
    sc_signal< sc_lv<13> > tmp9_fu_395_p2;
    sc_signal< sc_lv<13> > tmp9_reg_550;
    sc_signal< sc_logic > ap_sig_cseq_ST_st9_fsm_8;
    sc_signal< bool > ap_sig_169;
    sc_signal< sc_logic > ap_sig_cseq_ST_st10_fsm_9;
    sc_signal< bool > ap_sig_178;
    sc_signal< sc_lv<1> > p_max_1_fu_414_p2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st11_fsm_10;
    sc_signal< bool > ap_sig_187;
    sc_signal< sc_lv<13> > i_reg_103;
    sc_signal< sc_lv<6> > m_reg_114;
    sc_signal< sc_lv<9> > phi_mul_reg_125;
    sc_signal< sc_lv<4> > x_reg_137;
    sc_signal< sc_lv<4> > y_reg_148;
    sc_signal< sc_lv<1> > exitcond1_fu_349_p2;
    sc_signal< sc_lv<1> > max_reg_160;
    sc_signal< sc_lv<2> > c_reg_173;
    sc_signal< sc_lv<1> > max_1_reg_184;
    sc_signal< sc_lv<2> > r_reg_196;
    sc_signal< sc_lv<64> > tmp_s_fu_237_p1;
    sc_signal< sc_lv<64> > tmp_7_fu_361_p1;
    sc_signal< sc_lv<64> > tmp_1_fu_409_p1;
    sc_signal< sc_lv<7> > m_cast_fu_257_p1;
    sc_signal< sc_lv<4> > tmp_2_fu_272_p0;
    sc_signal< sc_lv<6> > tmp_2_fu_272_p1;
    sc_signal< sc_lv<4> > tmp_8_fu_292_p2;
    sc_signal< sc_lv<8> > y_cast5_fu_302_p1;
    sc_signal< sc_lv<8> > tmp_fu_317_p2;
    sc_signal< sc_lv<8> > tmp7_fu_326_p0;
    sc_signal< sc_lv<4> > tmp7_fu_326_p1;
    sc_signal< sc_lv<4> > tmp_10_fu_335_p2;
    sc_signal< sc_lv<9> > r_cast3_fu_365_p1;
    sc_signal< sc_lv<9> > tmp1_fu_381_p2;
    sc_signal< sc_lv<6> > tmp9_fu_395_p0;
    sc_signal< sc_lv<9> > tmp9_fu_395_p1;
    sc_signal< sc_lv<13> > tmp2_fu_400_p2;
    sc_signal< sc_lv<13> > i_index_fu_404_p2;
    sc_signal< sc_lv<11> > ap_NS_fsm;
    sc_signal< sc_lv<11> > tmp7_fu_326_p00;
    sc_signal< sc_lv<13> > tmp9_fu_395_p10;
    sc_signal< sc_lv<8> > tmp_2_fu_272_p10;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<11> ap_ST_st1_fsm_0;
    static const sc_lv<11> ap_ST_st2_fsm_1;
    static const sc_lv<11> ap_ST_st3_fsm_2;
    static const sc_lv<11> ap_ST_st4_fsm_3;
    static const sc_lv<11> ap_ST_st5_fsm_4;
    static const sc_lv<11> ap_ST_st6_fsm_5;
    static const sc_lv<11> ap_ST_st7_fsm_6;
    static const sc_lv<11> ap_ST_st8_fsm_7;
    static const sc_lv<11> ap_ST_st9_fsm_8;
    static const sc_lv<11> ap_ST_st10_fsm_9;
    static const sc_lv<11> ap_ST_st11_fsm_10;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<13> ap_const_lv13_0;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<13> ap_const_lv13_1440;
    static const sc_lv<13> ap_const_lv13_1;
    static const sc_lv<6> ap_const_lv6_1;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_I_cast2_fu_242_p1();
    void thread_I_cast_fu_245_p1();
    void thread_O_cast10_cast1_fu_217_p1();
    void thread_O_cast10_cast_fu_221_p1();
    void thread_O_fu_207_p4();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_103();
    void thread_ap_sig_119();
    void thread_ap_sig_133();
    void thread_ap_sig_144();
    void thread_ap_sig_155();
    void thread_ap_sig_169();
    void thread_ap_sig_178();
    void thread_ap_sig_187();
    void thread_ap_sig_28();
    void thread_ap_sig_68();
    void thread_ap_sig_86();
    void thread_ap_sig_cseq_ST_st10_fsm_9();
    void thread_ap_sig_cseq_ST_st11_fsm_10();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st3_fsm_2();
    void thread_ap_sig_cseq_ST_st4_fsm_3();
    void thread_ap_sig_cseq_ST_st5_fsm_4();
    void thread_ap_sig_cseq_ST_st6_fsm_5();
    void thread_ap_sig_cseq_ST_st7_fsm_6();
    void thread_ap_sig_cseq_ST_st8_fsm_7();
    void thread_ap_sig_cseq_ST_st9_fsm_8();
    void thread_c_2_fu_355_p2();
    void thread_c_cast4_fu_345_p1();
    void thread_exitcond1_fu_349_p2();
    void thread_exitcond2_fu_306_p2();
    void thread_exitcond3_fu_225_p2();
    void thread_exitcond4_fu_281_p2();
    void thread_exitcond_fu_369_p2();
    void thread_i_2_fu_231_p2();
    void thread_i_index_fu_404_p2();
    void thread_input_r_address0();
    void thread_input_r_ce0();
    void thread_m_2_fu_266_p2();
    void thread_m_cast_fu_257_p1();
    void thread_next_mul_fu_248_p2();
    void thread_o_index_fu_331_p2();
    void thread_output_r_address0();
    void thread_output_r_ce0();
    void thread_output_r_d0();
    void thread_output_r_we0();
    void thread_p_max_1_fu_414_p2();
    void thread_r_1_fu_375_p2();
    void thread_r_cast3_fu_365_p1();
    void thread_tmp1_fu_381_p2();
    void thread_tmp2_fu_400_p2();
    void thread_tmp7_fu_326_p0();
    void thread_tmp7_fu_326_p00();
    void thread_tmp7_fu_326_p1();
    void thread_tmp7_fu_326_p2();
    void thread_tmp8_fu_387_p2();
    void thread_tmp9_fu_395_p0();
    void thread_tmp9_fu_395_p1();
    void thread_tmp9_fu_395_p10();
    void thread_tmp9_fu_395_p2();
    void thread_tmp_10_fu_335_p2();
    void thread_tmp_1_fu_409_p1();
    void thread_tmp_2_fu_272_p0();
    void thread_tmp_2_fu_272_p1();
    void thread_tmp_2_fu_272_p10();
    void thread_tmp_2_fu_272_p2();
    void thread_tmp_5_cast_fu_298_p1();
    void thread_tmp_6_cast_fu_341_p1();
    void thread_tmp_7_fu_361_p1();
    void thread_tmp_8_fu_292_p2();
    void thread_tmp_9_fu_261_p2();
    void thread_tmp_fu_317_p2();
    void thread_tmp_s_fu_237_p1();
    void thread_x_3_fu_286_p2();
    void thread_x_cast6_fu_277_p1();
    void thread_y_3_fu_311_p2();
    void thread_y_cast5_fu_302_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
