// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dut_pad_HH_
#define _dut_pad_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct dut_pad : public sc_module {
    // Port declarations 15
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<13> > input_r_address0;
    sc_out< sc_logic > input_r_ce0;
    sc_in< sc_lv<1> > input_r_q0;
    sc_out< sc_lv<13> > output_r_address0;
    sc_out< sc_logic > output_r_ce0;
    sc_out< sc_logic > output_r_we0;
    sc_out< sc_lv<1> > output_r_d0;
    sc_in< sc_lv<7> > M;
    sc_in< sc_lv<6> > I;


    // Module declarations
    dut_pad(sc_module_name name);
    SC_HAS_PROCESS(dut_pad);

    ~dut_pad();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<7> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_24;
    sc_signal< sc_lv<13> > tmp_cast6_cast_fu_152_p1;
    sc_signal< sc_lv<13> > tmp_cast6_cast_reg_320;
    sc_signal< sc_lv<9> > tmp_cast_cast_fu_156_p1;
    sc_signal< sc_lv<9> > tmp_cast_cast_reg_325;
    sc_signal< sc_lv<13> > i_1_fu_166_p2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_62;
    sc_signal< sc_lv<6> > tmp_6_fu_177_p1;
    sc_signal< sc_lv<6> > tmp_6_reg_338;
    sc_signal< sc_lv<1> > exitcond1_fu_160_p2;
    sc_signal< sc_lv<8> > I_cast7_fu_180_p1;
    sc_signal< sc_lv<8> > I_cast7_reg_343;
    sc_signal< sc_lv<13> > I_cast_fu_183_p1;
    sc_signal< sc_lv<13> > I_cast_reg_348;
    sc_signal< sc_lv<8> > next_mul_fu_186_p2;
    sc_signal< sc_lv<8> > next_mul_reg_353;
    sc_signal< sc_logic > ap_sig_cseq_ST_st3_fsm_2;
    sc_signal< bool > ap_sig_82;
    sc_signal< sc_lv<5> > m_1_fu_204_p2;
    sc_signal< sc_lv<5> > m_1_reg_361;
    sc_signal< sc_lv<9> > tmp_4_fu_210_p2;
    sc_signal< sc_lv<9> > tmp_4_reg_366;
    sc_signal< sc_lv<1> > tmp_2_fu_199_p2;
    sc_signal< sc_lv<13> > x_cast2_fu_215_p1;
    sc_signal< sc_lv<13> > x_cast2_reg_371;
    sc_signal< sc_logic > ap_sig_cseq_ST_st4_fsm_3;
    sc_signal< bool > ap_sig_99;
    sc_signal< sc_lv<5> > x_2_fu_228_p2;
    sc_signal< sc_lv<5> > x_2_reg_379;
    sc_signal< sc_lv<13> > tmp_6_cast_fu_234_p1;
    sc_signal< sc_lv<13> > tmp_6_cast_reg_384;
    sc_signal< sc_lv<1> > tmp_5_fu_223_p2;
    sc_signal< sc_lv<5> > y_2_fu_251_p2;
    sc_signal< sc_lv<5> > y_2_reg_392;
    sc_signal< sc_logic > ap_sig_cseq_ST_st5_fsm_4;
    sc_signal< bool > ap_sig_116;
    sc_signal< sc_lv<13> > tmp4_fu_267_p2;
    sc_signal< sc_lv<13> > tmp4_reg_397;
    sc_signal< sc_lv<1> > exitcond_fu_246_p2;
    sc_signal< sc_lv<9> > tmp5_fu_276_p2;
    sc_signal< sc_lv<9> > tmp5_reg_402;
    sc_signal< sc_lv<13> > o_index_fu_293_p2;
    sc_signal< sc_lv<13> > o_index_reg_407;
    sc_signal< sc_logic > ap_sig_cseq_ST_st6_fsm_5;
    sc_signal< bool > ap_sig_132;
    sc_signal< sc_lv<13> > i_reg_86;
    sc_signal< sc_lv<5> > m_reg_97;
    sc_signal< sc_lv<8> > phi_mul_reg_108;
    sc_signal< sc_lv<5> > x_reg_120;
    sc_signal< sc_lv<5> > y_reg_131;
    sc_signal< sc_logic > ap_sig_cseq_ST_st7_fsm_6;
    sc_signal< bool > ap_sig_158;
    sc_signal< sc_lv<64> > tmp_1_fu_172_p1;
    sc_signal< sc_lv<64> > tmp_7_fu_298_p1;
    sc_signal< sc_lv<64> > tmp_8_fu_303_p1;
    sc_signal< sc_lv<5> > tmp_3_fu_142_p1;
    sc_signal< sc_lv<5> > tmp_s_fu_146_p2;
    sc_signal< sc_lv<6> > m_cast_fu_195_p1;
    sc_signal< sc_lv<5> > tmp_4_fu_210_p0;
    sc_signal< sc_lv<5> > tmp_4_fu_210_p1;
    sc_signal< sc_lv<6> > x_cast_fu_219_p1;
    sc_signal< sc_lv<6> > y_cast_fu_242_p1;
    sc_signal< sc_lv<8> > y_cast1_fu_238_p1;
    sc_signal< sc_lv<8> > tmp_fu_257_p2;
    sc_signal< sc_lv<6> > tmp4_fu_267_p0;
    sc_signal< sc_lv<8> > tmp4_fu_267_p1;
    sc_signal< sc_lv<9> > y_2_cast_fu_272_p1;
    sc_signal< sc_lv<9> > tmp6_fu_288_p0;
    sc_signal< sc_lv<5> > tmp6_fu_288_p1;
    sc_signal< sc_lv<13> > tmp6_fu_288_p2;
    sc_signal< sc_lv<13> > i_index_fu_281_p2;
    sc_signal< sc_lv<7> > ap_NS_fsm;
    sc_signal< sc_lv<13> > tmp4_fu_267_p10;
    sc_signal< sc_lv<13> > tmp6_fu_288_p00;
    sc_signal< sc_lv<9> > tmp_4_fu_210_p00;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<7> ap_ST_st1_fsm_0;
    static const sc_lv<7> ap_ST_st2_fsm_1;
    static const sc_lv<7> ap_ST_st3_fsm_2;
    static const sc_lv<7> ap_ST_st4_fsm_3;
    static const sc_lv<7> ap_ST_st5_fsm_4;
    static const sc_lv<7> ap_ST_st6_fsm_5;
    static const sc_lv<7> ap_ST_st7_fsm_6;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<13> ap_const_lv13_0;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<5> ap_const_lv5_2;
    static const sc_lv<13> ap_const_lv13_1440;
    static const sc_lv<13> ap_const_lv13_1;
    static const sc_lv<5> ap_const_lv5_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_I_cast7_fu_180_p1();
    void thread_I_cast_fu_183_p1();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_116();
    void thread_ap_sig_132();
    void thread_ap_sig_158();
    void thread_ap_sig_24();
    void thread_ap_sig_62();
    void thread_ap_sig_82();
    void thread_ap_sig_99();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st3_fsm_2();
    void thread_ap_sig_cseq_ST_st4_fsm_3();
    void thread_ap_sig_cseq_ST_st5_fsm_4();
    void thread_ap_sig_cseq_ST_st6_fsm_5();
    void thread_ap_sig_cseq_ST_st7_fsm_6();
    void thread_exitcond1_fu_160_p2();
    void thread_exitcond_fu_246_p2();
    void thread_i_1_fu_166_p2();
    void thread_i_index_fu_281_p2();
    void thread_input_r_address0();
    void thread_input_r_ce0();
    void thread_m_1_fu_204_p2();
    void thread_m_cast_fu_195_p1();
    void thread_next_mul_fu_186_p2();
    void thread_o_index_fu_293_p2();
    void thread_output_r_address0();
    void thread_output_r_ce0();
    void thread_output_r_d0();
    void thread_output_r_we0();
    void thread_tmp4_fu_267_p0();
    void thread_tmp4_fu_267_p1();
    void thread_tmp4_fu_267_p10();
    void thread_tmp4_fu_267_p2();
    void thread_tmp5_fu_276_p2();
    void thread_tmp6_fu_288_p0();
    void thread_tmp6_fu_288_p00();
    void thread_tmp6_fu_288_p1();
    void thread_tmp6_fu_288_p2();
    void thread_tmp_1_fu_172_p1();
    void thread_tmp_2_fu_199_p2();
    void thread_tmp_3_fu_142_p1();
    void thread_tmp_4_fu_210_p0();
    void thread_tmp_4_fu_210_p00();
    void thread_tmp_4_fu_210_p1();
    void thread_tmp_4_fu_210_p2();
    void thread_tmp_5_fu_223_p2();
    void thread_tmp_6_cast_fu_234_p1();
    void thread_tmp_6_fu_177_p1();
    void thread_tmp_7_fu_298_p1();
    void thread_tmp_8_fu_303_p1();
    void thread_tmp_cast6_cast_fu_152_p1();
    void thread_tmp_cast_cast_fu_156_p1();
    void thread_tmp_fu_257_p2();
    void thread_tmp_s_fu_146_p2();
    void thread_x_2_fu_228_p2();
    void thread_x_cast2_fu_215_p1();
    void thread_x_cast_fu_219_p1();
    void thread_y_2_cast_fu_272_p1();
    void thread_y_2_fu_251_p2();
    void thread_y_cast1_fu_238_p1();
    void thread_y_cast_fu_242_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
