// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dut_conv.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dut_conv::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dut_conv::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<12> dut_conv::ap_ST_st1_fsm_0 = "1";
const sc_lv<12> dut_conv::ap_ST_st2_fsm_1 = "10";
const sc_lv<12> dut_conv::ap_ST_st3_fsm_2 = "100";
const sc_lv<12> dut_conv::ap_ST_st4_fsm_3 = "1000";
const sc_lv<12> dut_conv::ap_ST_st5_fsm_4 = "10000";
const sc_lv<12> dut_conv::ap_ST_st6_fsm_5 = "100000";
const sc_lv<12> dut_conv::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<12> dut_conv::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<12> dut_conv::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<12> dut_conv::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<12> dut_conv::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<12> dut_conv::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<32> dut_conv::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> dut_conv::ap_const_lv1_1 = "1";
const sc_lv<32> dut_conv::ap_const_lv32_1 = "1";
const sc_lv<1> dut_conv::ap_const_lv1_0 = "0";
const sc_lv<32> dut_conv::ap_const_lv32_2 = "10";
const sc_lv<32> dut_conv::ap_const_lv32_3 = "11";
const sc_lv<32> dut_conv::ap_const_lv32_4 = "100";
const sc_lv<32> dut_conv::ap_const_lv32_5 = "101";
const sc_lv<32> dut_conv::ap_const_lv32_6 = "110";
const sc_lv<32> dut_conv::ap_const_lv32_7 = "111";
const sc_lv<32> dut_conv::ap_const_lv32_8 = "1000";
const sc_lv<32> dut_conv::ap_const_lv32_9 = "1001";
const sc_lv<32> dut_conv::ap_const_lv32_A = "1010";
const sc_lv<6> dut_conv::ap_const_lv6_0 = "000000";
const sc_lv<5> dut_conv::ap_const_lv5_0 = "00000";
const sc_lv<32> dut_conv::ap_const_lv32_B = "1011";
const sc_lv<9> dut_conv::ap_const_lv9_0 = "000000000";
const sc_lv<2> dut_conv::ap_const_lv2_0 = "00";
const sc_lv<5> dut_conv::ap_const_lv5_1E = "11110";
const sc_lv<5> dut_conv::ap_const_lv5_1F = "11111";
const sc_lv<6> dut_conv::ap_const_lv6_1 = "1";
const sc_lv<5> dut_conv::ap_const_lv5_1 = "1";
const sc_lv<3> dut_conv::ap_const_lv3_0 = "000";
const sc_lv<2> dut_conv::ap_const_lv2_3 = "11";
const sc_lv<2> dut_conv::ap_const_lv2_1 = "1";

dut_conv::dut_conv(sc_module_name name) : sc_module(name), mVcdFile(0) {
    w_conv1_U = new dut_conv_w_conv1("w_conv1_U");
    w_conv1_U->clk(ap_clk);
    w_conv1_U->reset(ap_rst);
    w_conv1_U->address0(w_conv1_address0);
    w_conv1_U->ce0(w_conv1_ce0);
    w_conv1_U->q0(w_conv1_q0);
    w_conv2_U = new dut_conv_w_conv2("w_conv2_U");
    w_conv2_U->clk(ap_clk);
    w_conv2_U->reset(ap_rst);
    w_conv2_U->address0(w_conv2_address0);
    w_conv2_U->ce0(w_conv2_ce0);
    w_conv2_U->q0(w_conv2_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_I_cast5_fu_351_p1);
    sensitive << ( I );

    SC_METHOD(thread_I_cast_fu_359_p1);
    sensitive << ( I );

    SC_METHOD(thread_L_read_read_fu_88_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( L );

    SC_METHOD(thread_N_cast_fu_355_p1);
    sensitive << ( N );

    SC_METHOD(thread_O_cast24_cast_fu_337_p1);
    sensitive << ( O_fu_327_p2 );

    SC_METHOD(thread_O_cast25_cast_fu_333_p1);
    sensitive << ( O_fu_327_p2 );

    SC_METHOD(thread_O_fu_327_p2);
    sensitive << ( tmp_24_fu_323_p1 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( tmp_s_fu_371_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( tmp_s_fu_371_p2 );

    SC_METHOD(thread_ap_sig_101);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_119);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_130);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_146);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_155);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_179);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_203);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_231);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_246);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_256);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_278);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_29);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st10_fsm_9);
    sensitive << ( ap_sig_246 );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_10);
    sensitive << ( ap_sig_256 );

    SC_METHOD(thread_ap_sig_cseq_ST_st12_fsm_11);
    sensitive << ( ap_sig_278 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_29 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_101 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_119 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_130 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_146 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_155 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_179 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_203 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_231 );

    SC_METHOD(thread_c_3_fu_505_p2);
    sensitive << ( c_reg_277 );

    SC_METHOD(thread_c_cast_fu_495_p1);
    sensitive << ( c_reg_277 );

    SC_METHOD(thread_exitcond1_fu_391_p2);
    sensitive << ( O_reg_744 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( x_reg_183 );

    SC_METHOD(thread_exitcond2_fu_499_p2);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( c_reg_277 );

    SC_METHOD(thread_exitcond3_fu_406_p2);
    sensitive << ( O_reg_744 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( y_reg_195 );

    SC_METHOD(thread_exitcond_fu_558_p2);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( r_reg_312 );

    SC_METHOD(thread_i_index_fu_680_p2);
    sensitive << ( x_assign_cast_reg_886 );
    sensitive << ( tmp7_fu_675_p2 );

    SC_METHOD(thread_input_r_address0);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( tmp_22_fu_685_p1 );

    SC_METHOD(thread_input_r_ce0);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );

    SC_METHOD(thread_m_4_fu_454_p2);
    sensitive << ( m_reg_219 );

    SC_METHOD(thread_m_cast_fu_445_p1);
    sensitive << ( m_reg_219 );

    SC_METHOD(thread_mac_num_2_fu_664_p3);
    sensitive << ( sel_tmp1_fu_659_p2 );
    sensitive << ( mac_num_1_reg_300 );
    sensitive << ( mac_num_3_fu_647_p2 );

    SC_METHOD(thread_mac_num_3_fu_647_p2);
    sensitive << ( mac_num_1_reg_300 );

    SC_METHOD(thread_n_2_fu_376_p2);
    sensitive << ( n_reg_172 );

    SC_METHOD(thread_n_cast1_fu_363_p1);
    sensitive << ( n_reg_172 );

    SC_METHOD(thread_n_cast_fu_367_p1);
    sensitive << ( n_reg_172 );

    SC_METHOD(thread_next_mul4_fu_435_p2);
    sensitive << ( N_cast_reg_776 );
    sensitive << ( phi_mul3_reg_242 );

    SC_METHOD(thread_next_mul_fu_440_p2);
    sensitive << ( I_cast5_reg_771 );
    sensitive << ( phi_mul_reg_230 );

    SC_METHOD(thread_notlhs_i_fu_527_p2);
    sensitive << ( tmp_i_reg_760 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( exitcond2_fu_499_p2 );
    sensitive << ( x_assign_fu_511_p2 );

    SC_METHOD(thread_notrhs_i_fu_576_p2);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( exitcond_fu_558_p2 );
    sensitive << ( y_assign_fu_570_p2 );

    SC_METHOD(thread_o_index_fu_431_p2);
    sensitive << ( x_cast_reg_804 );
    sensitive << ( tmp5_reg_830 );

    SC_METHOD(thread_one_out_2_fu_710_p2);
    sensitive << ( one_out_1_reg_288 );
    sensitive << ( p_pn_fu_706_p1 );

    SC_METHOD(thread_one_out_3_fu_716_p3);
    sensitive << ( sel_tmp1_reg_929 );
    sensitive << ( one_out_1_reg_288 );
    sensitive << ( one_out_2_fu_710_p2 );

    SC_METHOD(thread_or_cond2_i_fu_592_p2);
    sensitive << ( tmp_fu_587_p2 );
    sensitive << ( notrhs_i_fu_576_p2 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( tmp_17_reg_863 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( sum_reg_207 );
    sensitive << ( tmp_18_fu_723_p1 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );

    SC_METHOD(thread_p_pn_fu_706_p1);
    sensitive << ( p_pn_in_fu_700_p2 );

    SC_METHOD(thread_p_pn_in_fu_700_p2);
    sensitive << ( input_r_q0 );
    sensitive << ( tmp11_fu_694_p2 );

    SC_METHOD(thread_p_pn_in_in_v_fu_689_p3);
    sensitive << ( L );
    sensitive << ( w_conv1_load_reg_944 );
    sensitive << ( w_conv2_load_reg_949 );

    SC_METHOD(thread_p_shl1_cast_fu_617_p1);
    sensitive << ( p_shl1_fu_609_p3 );

    SC_METHOD(thread_p_shl1_fu_609_p3);
    sensitive << ( r_reg_312 );

    SC_METHOD(thread_p_shl_cast_fu_477_p1);
    sensitive << ( p_shl_fu_469_p3 );

    SC_METHOD(thread_p_shl_fu_469_p3);
    sensitive << ( tmp_16_fu_460_p2 );

    SC_METHOD(thread_r_2_fu_564_p2);
    sensitive << ( r_reg_312 );

    SC_METHOD(thread_r_cast1_fu_554_p1);
    sensitive << ( r_reg_312 );

    SC_METHOD(thread_r_cast_fu_550_p1);
    sensitive << ( r_reg_312 );

    SC_METHOD(thread_sel_tmp1_fu_659_p2);
    sensitive << ( tmp_i_26_reg_891 );
    sensitive << ( sel_tmp_fu_653_p2 );

    SC_METHOD(thread_sel_tmp_fu_653_p2);
    sensitive << ( or_cond2_i_fu_592_p2 );

    SC_METHOD(thread_sum_1_fu_544_p2);
    sensitive << ( tmp_20_fu_538_p2 );
    sensitive << ( tmp_30_fu_532_p2 );

    SC_METHOD(thread_threshold_V_address0);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( tmp_17_fu_491_p1 );

    SC_METHOD(thread_threshold_V_ce0);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_tmp10_cast_fu_632_p1);
    sensitive << ( tmp10_fu_627_p2 );

    SC_METHOD(thread_tmp10_fu_627_p2);
    sensitive << ( c_cast_reg_873 );
    sensitive << ( tmp_21_fu_621_p2 );

    SC_METHOD(thread_tmp11_fu_694_p2);
    sensitive << ( p_pn_in_in_v_fu_689_p3 );

    SC_METHOD(thread_tmp4_fu_417_p2);
    sensitive << ( tmp_14_reg_799 );
    sensitive << ( y_cast_fu_402_p1 );

    SC_METHOD(thread_tmp5_fu_426_p0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp5_fu_426_p00 );

    SC_METHOD(thread_tmp5_fu_426_p00);
    sensitive << ( tmp4_fu_417_p2 );

    SC_METHOD(thread_tmp5_fu_426_p1);
    sensitive << ( O_cast25_cast_reg_750 );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_tmp5_fu_426_p2);
    sensitive << ( tmp5_fu_426_p0 );
    sensitive << ( tmp5_fu_426_p1 );

    SC_METHOD(thread_tmp6_fu_604_p2);
    sensitive << ( y_cast_reg_817 );
    sensitive << ( tmp8_fu_598_p2 );

    SC_METHOD(thread_tmp7_fu_675_p0);
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( tmp7_fu_675_p00 );

    SC_METHOD(thread_tmp7_fu_675_p00);
    sensitive << ( tmp6_reg_914 );

    SC_METHOD(thread_tmp7_fu_675_p1);
    sensitive << ( I_cast_reg_781 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );

    SC_METHOD(thread_tmp7_fu_675_p2);
    sensitive << ( tmp7_fu_675_p0 );
    sensitive << ( tmp7_fu_675_p1 );

    SC_METHOD(thread_tmp8_fu_598_p2);
    sensitive << ( phi_mul_reg_230 );
    sensitive << ( r_cast_fu_550_p1 );

    SC_METHOD(thread_tmp9_cast_fu_487_p1);
    sensitive << ( tmp9_fu_481_p2 );

    SC_METHOD(thread_tmp9_fu_481_p2);
    sensitive << ( p_shl_cast_fu_477_p1 );
    sensitive << ( tmp_29_cast1_fu_465_p1 );

    SC_METHOD(thread_tmp_12_i_fu_582_p2);
    sensitive << ( tmp_i_reg_760 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( exitcond_fu_558_p2 );
    sensitive << ( y_assign_fu_570_p2 );

    SC_METHOD(thread_tmp_14_fu_382_p0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( tmp_14_fu_382_p00 );

    SC_METHOD(thread_tmp_14_fu_382_p00);
    sensitive << ( n_reg_172 );

    SC_METHOD(thread_tmp_14_fu_382_p1);
    sensitive << ( O_cast24_cast_reg_755 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_tmp_14_fu_382_p2);
    sensitive << ( tmp_14_fu_382_p0 );
    sensitive << ( tmp_14_fu_382_p1 );

    SC_METHOD(thread_tmp_15_fu_449_p2);
    sensitive << ( tmp_25_reg_766 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( m_cast_fu_445_p1 );

    SC_METHOD(thread_tmp_16_fu_460_p2);
    sensitive << ( n_cast1_reg_786 );
    sensitive << ( phi_mul3_reg_242 );

    SC_METHOD(thread_tmp_17_fu_491_p1);
    sensitive << ( o_index_reg_835 );

    SC_METHOD(thread_tmp_18_fu_723_p1);
    sensitive << ( threshold_V_q0 );

    SC_METHOD(thread_tmp_20_fu_538_p2);
    sensitive << ( sum_reg_207 );
    sensitive << ( mac_num_reg_265 );

    SC_METHOD(thread_tmp_21_fu_621_p2);
    sensitive << ( r_cast1_fu_554_p1 );
    sensitive << ( p_shl1_cast_fu_617_p1 );

    SC_METHOD(thread_tmp_22_fu_685_p1);
    sensitive << ( i_index_reg_939 );

    SC_METHOD(thread_tmp_23_fu_641_p1);
    sensitive << ( w_index_fu_636_p2 );

    SC_METHOD(thread_tmp_24_fu_323_p1);
    sensitive << ( I );

    SC_METHOD(thread_tmp_25_fu_347_p1);
    sensitive << ( M );

    SC_METHOD(thread_tmp_29_cast1_fu_465_p1);
    sensitive << ( tmp_16_fu_460_p2 );

    SC_METHOD(thread_tmp_30_fu_532_p2);
    sensitive << ( one_out_reg_253 );

    SC_METHOD(thread_tmp_fu_587_p2);
    sensitive << ( notlhs_i_reg_896 );
    sensitive << ( tmp_12_i_fu_582_p2 );

    SC_METHOD(thread_tmp_i_26_fu_521_p2);
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( exitcond2_fu_499_p2 );
    sensitive << ( x_assign_fu_511_p2 );

    SC_METHOD(thread_tmp_i_fu_341_p2);
    sensitive << ( tmp_24_fu_323_p1 );

    SC_METHOD(thread_tmp_s_fu_371_p2);
    sensitive << ( N );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( n_cast_fu_367_p1 );

    SC_METHOD(thread_w_conv1_address0);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( tmp_23_fu_641_p1 );

    SC_METHOD(thread_w_conv1_ce0);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_w_conv2_address0);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( tmp_23_fu_641_p1 );

    SC_METHOD(thread_w_conv2_ce0);
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_w_index_fu_636_p2);
    sensitive << ( tmp9_cast_reg_858 );
    sensitive << ( tmp10_cast_fu_632_p1 );

    SC_METHOD(thread_x_4_fu_396_p2);
    sensitive << ( x_reg_183 );

    SC_METHOD(thread_x_assign_cast_fu_517_p1);
    sensitive << ( x_assign_fu_511_p2 );

    SC_METHOD(thread_x_assign_fu_511_p2);
    sensitive << ( c_cast_fu_495_p1 );
    sensitive << ( x_reg_183 );

    SC_METHOD(thread_x_cast_fu_387_p1);
    sensitive << ( x_reg_183 );

    SC_METHOD(thread_y_4_fu_411_p2);
    sensitive << ( y_reg_195 );

    SC_METHOD(thread_y_assign_fu_570_p2);
    sensitive << ( y_reg_195 );
    sensitive << ( r_cast1_fu_554_p1 );

    SC_METHOD(thread_y_cast_fu_402_p1);
    sensitive << ( y_reg_195 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_s_fu_371_p2 );
    sensitive << ( exitcond3_fu_406_p2 );
    sensitive << ( tmp_15_fu_449_p2 );
    sensitive << ( exitcond2_fu_499_p2 );
    sensitive << ( exitcond_fu_558_p2 );
    sensitive << ( exitcond1_fu_391_p2 );

    ap_CS_fsm = "000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dut_conv_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r_address0, "(port)input_r_address0");
    sc_trace(mVcdFile, input_r_ce0, "(port)input_r_ce0");
    sc_trace(mVcdFile, input_r_q0, "(port)input_r_q0");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
    sc_trace(mVcdFile, threshold_V_address0, "(port)threshold_V_address0");
    sc_trace(mVcdFile, threshold_V_ce0, "(port)threshold_V_ce0");
    sc_trace(mVcdFile, threshold_V_q0, "(port)threshold_V_q0");
    sc_trace(mVcdFile, M, "(port)M");
    sc_trace(mVcdFile, N, "(port)N");
    sc_trace(mVcdFile, I, "(port)I");
    sc_trace(mVcdFile, L, "(port)L");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_29, "ap_sig_29");
    sc_trace(mVcdFile, w_conv1_address0, "w_conv1_address0");
    sc_trace(mVcdFile, w_conv1_ce0, "w_conv1_ce0");
    sc_trace(mVcdFile, w_conv1_q0, "w_conv1_q0");
    sc_trace(mVcdFile, w_conv2_address0, "w_conv2_address0");
    sc_trace(mVcdFile, w_conv2_ce0, "w_conv2_ce0");
    sc_trace(mVcdFile, w_conv2_q0, "w_conv2_q0");
    sc_trace(mVcdFile, L_read_read_fu_88_p2, "L_read_read_fu_88_p2");
    sc_trace(mVcdFile, O_fu_327_p2, "O_fu_327_p2");
    sc_trace(mVcdFile, O_reg_744, "O_reg_744");
    sc_trace(mVcdFile, O_cast25_cast_fu_333_p1, "O_cast25_cast_fu_333_p1");
    sc_trace(mVcdFile, O_cast25_cast_reg_750, "O_cast25_cast_reg_750");
    sc_trace(mVcdFile, O_cast24_cast_fu_337_p1, "O_cast24_cast_fu_337_p1");
    sc_trace(mVcdFile, O_cast24_cast_reg_755, "O_cast24_cast_reg_755");
    sc_trace(mVcdFile, tmp_i_fu_341_p2, "tmp_i_fu_341_p2");
    sc_trace(mVcdFile, tmp_i_reg_760, "tmp_i_reg_760");
    sc_trace(mVcdFile, tmp_25_fu_347_p1, "tmp_25_fu_347_p1");
    sc_trace(mVcdFile, tmp_25_reg_766, "tmp_25_reg_766");
    sc_trace(mVcdFile, I_cast5_fu_351_p1, "I_cast5_fu_351_p1");
    sc_trace(mVcdFile, I_cast5_reg_771, "I_cast5_reg_771");
    sc_trace(mVcdFile, N_cast_fu_355_p1, "N_cast_fu_355_p1");
    sc_trace(mVcdFile, N_cast_reg_776, "N_cast_reg_776");
    sc_trace(mVcdFile, I_cast_fu_359_p1, "I_cast_fu_359_p1");
    sc_trace(mVcdFile, I_cast_reg_781, "I_cast_reg_781");
    sc_trace(mVcdFile, n_cast1_fu_363_p1, "n_cast1_fu_363_p1");
    sc_trace(mVcdFile, n_cast1_reg_786, "n_cast1_reg_786");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_101, "ap_sig_101");
    sc_trace(mVcdFile, n_2_fu_376_p2, "n_2_fu_376_p2");
    sc_trace(mVcdFile, n_2_reg_794, "n_2_reg_794");
    sc_trace(mVcdFile, tmp_14_fu_382_p2, "tmp_14_fu_382_p2");
    sc_trace(mVcdFile, tmp_14_reg_799, "tmp_14_reg_799");
    sc_trace(mVcdFile, tmp_s_fu_371_p2, "tmp_s_fu_371_p2");
    sc_trace(mVcdFile, x_cast_fu_387_p1, "x_cast_fu_387_p1");
    sc_trace(mVcdFile, x_cast_reg_804, "x_cast_reg_804");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_119, "ap_sig_119");
    sc_trace(mVcdFile, x_4_fu_396_p2, "x_4_fu_396_p2");
    sc_trace(mVcdFile, x_4_reg_812, "x_4_reg_812");
    sc_trace(mVcdFile, y_cast_fu_402_p1, "y_cast_fu_402_p1");
    sc_trace(mVcdFile, y_cast_reg_817, "y_cast_reg_817");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_130, "ap_sig_130");
    sc_trace(mVcdFile, y_4_fu_411_p2, "y_4_fu_411_p2");
    sc_trace(mVcdFile, y_4_reg_825, "y_4_reg_825");
    sc_trace(mVcdFile, tmp5_fu_426_p2, "tmp5_fu_426_p2");
    sc_trace(mVcdFile, tmp5_reg_830, "tmp5_reg_830");
    sc_trace(mVcdFile, exitcond3_fu_406_p2, "exitcond3_fu_406_p2");
    sc_trace(mVcdFile, o_index_fu_431_p2, "o_index_fu_431_p2");
    sc_trace(mVcdFile, o_index_reg_835, "o_index_reg_835");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_146, "ap_sig_146");
    sc_trace(mVcdFile, next_mul4_fu_435_p2, "next_mul4_fu_435_p2");
    sc_trace(mVcdFile, next_mul4_reg_840, "next_mul4_reg_840");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_155, "ap_sig_155");
    sc_trace(mVcdFile, next_mul_fu_440_p2, "next_mul_fu_440_p2");
    sc_trace(mVcdFile, next_mul_reg_845, "next_mul_reg_845");
    sc_trace(mVcdFile, m_4_fu_454_p2, "m_4_fu_454_p2");
    sc_trace(mVcdFile, m_4_reg_853, "m_4_reg_853");
    sc_trace(mVcdFile, tmp9_cast_fu_487_p1, "tmp9_cast_fu_487_p1");
    sc_trace(mVcdFile, tmp9_cast_reg_858, "tmp9_cast_reg_858");
    sc_trace(mVcdFile, tmp_15_fu_449_p2, "tmp_15_fu_449_p2");
    sc_trace(mVcdFile, tmp_17_fu_491_p1, "tmp_17_fu_491_p1");
    sc_trace(mVcdFile, tmp_17_reg_863, "tmp_17_reg_863");
    sc_trace(mVcdFile, c_cast_fu_495_p1, "c_cast_fu_495_p1");
    sc_trace(mVcdFile, c_cast_reg_873, "c_cast_reg_873");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_179, "ap_sig_179");
    sc_trace(mVcdFile, c_3_fu_505_p2, "c_3_fu_505_p2");
    sc_trace(mVcdFile, c_3_reg_881, "c_3_reg_881");
    sc_trace(mVcdFile, x_assign_cast_fu_517_p1, "x_assign_cast_fu_517_p1");
    sc_trace(mVcdFile, x_assign_cast_reg_886, "x_assign_cast_reg_886");
    sc_trace(mVcdFile, exitcond2_fu_499_p2, "exitcond2_fu_499_p2");
    sc_trace(mVcdFile, tmp_i_26_fu_521_p2, "tmp_i_26_fu_521_p2");
    sc_trace(mVcdFile, tmp_i_26_reg_891, "tmp_i_26_reg_891");
    sc_trace(mVcdFile, notlhs_i_fu_527_p2, "notlhs_i_fu_527_p2");
    sc_trace(mVcdFile, notlhs_i_reg_896, "notlhs_i_reg_896");
    sc_trace(mVcdFile, sum_1_fu_544_p2, "sum_1_fu_544_p2");
    sc_trace(mVcdFile, r_2_fu_564_p2, "r_2_fu_564_p2");
    sc_trace(mVcdFile, r_2_reg_909, "r_2_reg_909");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_203, "ap_sig_203");
    sc_trace(mVcdFile, tmp6_fu_604_p2, "tmp6_fu_604_p2");
    sc_trace(mVcdFile, tmp6_reg_914, "tmp6_reg_914");
    sc_trace(mVcdFile, exitcond_fu_558_p2, "exitcond_fu_558_p2");
    sc_trace(mVcdFile, sel_tmp1_fu_659_p2, "sel_tmp1_fu_659_p2");
    sc_trace(mVcdFile, sel_tmp1_reg_929, "sel_tmp1_reg_929");
    sc_trace(mVcdFile, mac_num_2_fu_664_p3, "mac_num_2_fu_664_p3");
    sc_trace(mVcdFile, mac_num_2_reg_934, "mac_num_2_reg_934");
    sc_trace(mVcdFile, i_index_fu_680_p2, "i_index_fu_680_p2");
    sc_trace(mVcdFile, i_index_reg_939, "i_index_reg_939");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_231, "ap_sig_231");
    sc_trace(mVcdFile, w_conv1_load_reg_944, "w_conv1_load_reg_944");
    sc_trace(mVcdFile, w_conv2_load_reg_949, "w_conv2_load_reg_949");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st10_fsm_9, "ap_sig_cseq_ST_st10_fsm_9");
    sc_trace(mVcdFile, ap_sig_246, "ap_sig_246");
    sc_trace(mVcdFile, one_out_3_fu_716_p3, "one_out_3_fu_716_p3");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_10, "ap_sig_cseq_ST_st11_fsm_10");
    sc_trace(mVcdFile, ap_sig_256, "ap_sig_256");
    sc_trace(mVcdFile, n_reg_172, "n_reg_172");
    sc_trace(mVcdFile, exitcond1_fu_391_p2, "exitcond1_fu_391_p2");
    sc_trace(mVcdFile, x_reg_183, "x_reg_183");
    sc_trace(mVcdFile, y_reg_195, "y_reg_195");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st12_fsm_11, "ap_sig_cseq_ST_st12_fsm_11");
    sc_trace(mVcdFile, ap_sig_278, "ap_sig_278");
    sc_trace(mVcdFile, sum_reg_207, "sum_reg_207");
    sc_trace(mVcdFile, m_reg_219, "m_reg_219");
    sc_trace(mVcdFile, phi_mul_reg_230, "phi_mul_reg_230");
    sc_trace(mVcdFile, phi_mul3_reg_242, "phi_mul3_reg_242");
    sc_trace(mVcdFile, one_out_reg_253, "one_out_reg_253");
    sc_trace(mVcdFile, mac_num_reg_265, "mac_num_reg_265");
    sc_trace(mVcdFile, c_reg_277, "c_reg_277");
    sc_trace(mVcdFile, one_out_1_reg_288, "one_out_1_reg_288");
    sc_trace(mVcdFile, mac_num_1_reg_300, "mac_num_1_reg_300");
    sc_trace(mVcdFile, r_reg_312, "r_reg_312");
    sc_trace(mVcdFile, tmp_23_fu_641_p1, "tmp_23_fu_641_p1");
    sc_trace(mVcdFile, tmp_22_fu_685_p1, "tmp_22_fu_685_p1");
    sc_trace(mVcdFile, tmp_24_fu_323_p1, "tmp_24_fu_323_p1");
    sc_trace(mVcdFile, n_cast_fu_367_p1, "n_cast_fu_367_p1");
    sc_trace(mVcdFile, tmp_14_fu_382_p0, "tmp_14_fu_382_p0");
    sc_trace(mVcdFile, tmp_14_fu_382_p1, "tmp_14_fu_382_p1");
    sc_trace(mVcdFile, tmp4_fu_417_p2, "tmp4_fu_417_p2");
    sc_trace(mVcdFile, tmp5_fu_426_p0, "tmp5_fu_426_p0");
    sc_trace(mVcdFile, tmp5_fu_426_p1, "tmp5_fu_426_p1");
    sc_trace(mVcdFile, m_cast_fu_445_p1, "m_cast_fu_445_p1");
    sc_trace(mVcdFile, tmp_16_fu_460_p2, "tmp_16_fu_460_p2");
    sc_trace(mVcdFile, p_shl_fu_469_p3, "p_shl_fu_469_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_477_p1, "p_shl_cast_fu_477_p1");
    sc_trace(mVcdFile, tmp_29_cast1_fu_465_p1, "tmp_29_cast1_fu_465_p1");
    sc_trace(mVcdFile, tmp9_fu_481_p2, "tmp9_fu_481_p2");
    sc_trace(mVcdFile, x_assign_fu_511_p2, "x_assign_fu_511_p2");
    sc_trace(mVcdFile, tmp_20_fu_538_p2, "tmp_20_fu_538_p2");
    sc_trace(mVcdFile, tmp_30_fu_532_p2, "tmp_30_fu_532_p2");
    sc_trace(mVcdFile, r_cast1_fu_554_p1, "r_cast1_fu_554_p1");
    sc_trace(mVcdFile, y_assign_fu_570_p2, "y_assign_fu_570_p2");
    sc_trace(mVcdFile, tmp_12_i_fu_582_p2, "tmp_12_i_fu_582_p2");
    sc_trace(mVcdFile, tmp_fu_587_p2, "tmp_fu_587_p2");
    sc_trace(mVcdFile, notrhs_i_fu_576_p2, "notrhs_i_fu_576_p2");
    sc_trace(mVcdFile, r_cast_fu_550_p1, "r_cast_fu_550_p1");
    sc_trace(mVcdFile, tmp8_fu_598_p2, "tmp8_fu_598_p2");
    sc_trace(mVcdFile, p_shl1_fu_609_p3, "p_shl1_fu_609_p3");
    sc_trace(mVcdFile, p_shl1_cast_fu_617_p1, "p_shl1_cast_fu_617_p1");
    sc_trace(mVcdFile, tmp_21_fu_621_p2, "tmp_21_fu_621_p2");
    sc_trace(mVcdFile, tmp10_fu_627_p2, "tmp10_fu_627_p2");
    sc_trace(mVcdFile, tmp10_cast_fu_632_p1, "tmp10_cast_fu_632_p1");
    sc_trace(mVcdFile, w_index_fu_636_p2, "w_index_fu_636_p2");
    sc_trace(mVcdFile, or_cond2_i_fu_592_p2, "or_cond2_i_fu_592_p2");
    sc_trace(mVcdFile, sel_tmp_fu_653_p2, "sel_tmp_fu_653_p2");
    sc_trace(mVcdFile, mac_num_3_fu_647_p2, "mac_num_3_fu_647_p2");
    sc_trace(mVcdFile, tmp7_fu_675_p0, "tmp7_fu_675_p0");
    sc_trace(mVcdFile, tmp7_fu_675_p1, "tmp7_fu_675_p1");
    sc_trace(mVcdFile, tmp7_fu_675_p2, "tmp7_fu_675_p2");
    sc_trace(mVcdFile, p_pn_in_in_v_fu_689_p3, "p_pn_in_in_v_fu_689_p3");
    sc_trace(mVcdFile, tmp11_fu_694_p2, "tmp11_fu_694_p2");
    sc_trace(mVcdFile, p_pn_in_fu_700_p2, "p_pn_in_fu_700_p2");
    sc_trace(mVcdFile, p_pn_fu_706_p1, "p_pn_fu_706_p1");
    sc_trace(mVcdFile, one_out_2_fu_710_p2, "one_out_2_fu_710_p2");
    sc_trace(mVcdFile, tmp_18_fu_723_p1, "tmp_18_fu_723_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, tmp5_fu_426_p00, "tmp5_fu_426_p00");
    sc_trace(mVcdFile, tmp7_fu_675_p00, "tmp7_fu_675_p00");
    sc_trace(mVcdFile, tmp_14_fu_382_p00, "tmp_14_fu_382_p00");
#endif

    }
}

dut_conv::~dut_conv() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete w_conv1_U;
    delete w_conv2_U;
}

void dut_conv::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_558_p2.read()))) {
        c_reg_277 = c_3_reg_881.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_15_fu_449_p2.read()))) {
        c_reg_277 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_499_p2.read()))) {
        m_reg_219 = m_4_reg_853.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        m_reg_219 = ap_const_lv5_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        mac_num_1_reg_300 = mac_num_2_reg_934.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_499_p2.read()))) {
        mac_num_1_reg_300 = mac_num_reg_265.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_558_p2.read()))) {
        mac_num_reg_265 = mac_num_1_reg_300.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_15_fu_449_p2.read()))) {
        mac_num_reg_265 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_391_p2.read()))) {
        n_reg_172 = n_2_reg_794.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        n_reg_172 = ap_const_lv6_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        one_out_1_reg_288 = one_out_3_fu_716_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_499_p2.read()))) {
        one_out_1_reg_288 = one_out_reg_253.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_558_p2.read()))) {
        one_out_reg_253 = one_out_1_reg_288.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_15_fu_449_p2.read()))) {
        one_out_reg_253 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_499_p2.read()))) {
        phi_mul3_reg_242 = next_mul4_reg_840.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        phi_mul3_reg_242 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_499_p2.read()))) {
        phi_mul_reg_230 = next_mul_reg_845.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        phi_mul_reg_230 = ap_const_lv9_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        r_reg_312 = r_2_reg_909.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_499_p2.read()))) {
        r_reg_312 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_499_p2.read()))) {
        sum_reg_207 = sum_1_fu_544_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        sum_reg_207 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_406_p2.read()))) {
        x_reg_183 = x_4_reg_812.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                !esl_seteq<1,1,1>(tmp_s_fu_371_p2.read(), ap_const_lv1_0))) {
        x_reg_183 = ap_const_lv5_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        y_reg_195 = y_4_reg_825.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_391_p2.read()))) {
        y_reg_195 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        I_cast5_reg_771 = I_cast5_fu_351_p1.read();
        I_cast_reg_781 = I_cast_fu_359_p1.read();
        N_cast_reg_776 = N_cast_fu_355_p1.read();
        O_cast24_cast_reg_755 = O_cast24_cast_fu_337_p1.read();
        O_cast25_cast_reg_750 = O_cast25_cast_fu_333_p1.read();
        O_reg_744 = O_fu_327_p2.read();
        tmp_25_reg_766 = tmp_25_fu_347_p1.read();
        tmp_i_reg_760 = tmp_i_fu_341_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        c_3_reg_881 = c_3_fu_505_p2.read();
        c_cast_reg_873 = c_cast_fu_495_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, sel_tmp1_reg_929.read()))) {
        i_index_reg_939 = i_index_fu_680_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        m_4_reg_853 = m_4_fu_454_p2.read();
        next_mul4_reg_840 = next_mul4_fu_435_p2.read();
        next_mul_reg_845 = next_mul_fu_440_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_558_p2.read()))) {
        mac_num_2_reg_934 = mac_num_2_fu_664_p3.read();
        sel_tmp1_reg_929 = sel_tmp1_fu_659_p2.read();
        tmp6_reg_914 = tmp6_fu_604_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        n_2_reg_794 = n_2_fu_376_p2.read();
        n_cast1_reg_786 = n_cast1_fu_363_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_499_p2.read()))) {
        notlhs_i_reg_896 = notlhs_i_fu_527_p2.read();
        tmp_i_26_reg_891 = tmp_i_26_fu_521_p2.read();
        x_assign_cast_reg_886 = x_assign_cast_fu_517_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        o_index_reg_835 = o_index_fu_431_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        r_2_reg_909 = r_2_fu_564_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_406_p2.read()))) {
        tmp5_reg_830 = tmp5_fu_426_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_15_fu_449_p2.read()))) {
        tmp9_cast_reg_858 = tmp9_cast_fu_487_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && !esl_seteq<1,1,1>(tmp_s_fu_371_p2.read(), ap_const_lv1_0))) {
        tmp_14_reg_799 = tmp_14_fu_382_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_15_fu_449_p2.read()))) {
        tmp_17_reg_863 = tmp_17_fu_491_p1.read();
    }
    if ((esl_seteq<1,1,1>(L_read_read_fu_88_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()))) {
        w_conv1_load_reg_944 = w_conv1_q0.read();
    }
    if ((!esl_seteq<1,1,1>(L_read_read_fu_88_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()))) {
        w_conv2_load_reg_949 = w_conv2_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        x_4_reg_812 = x_4_fu_396_p2.read();
        x_cast_reg_804 = x_cast_fu_387_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        y_4_reg_825 = y_4_fu_411_p2.read();
        y_cast_reg_817 = y_cast_fu_402_p1.read();
    }
}

void dut_conv::thread_I_cast5_fu_351_p1() {
    I_cast5_fu_351_p1 = esl_zext<9,6>(I.read());
}

void dut_conv::thread_I_cast_fu_359_p1() {
    I_cast_fu_359_p1 = esl_zext<13,6>(I.read());
}

void dut_conv::thread_L_read_read_fu_88_p2() {
    L_read_read_fu_88_p2 = L.read();
}

void dut_conv::thread_N_cast_fu_355_p1() {
    N_cast_fu_355_p1 = esl_zext<9,7>(N.read());
}

void dut_conv::thread_O_cast24_cast_fu_337_p1() {
    O_cast24_cast_fu_337_p1 = esl_zext<9,5>(O_fu_327_p2.read());
}

void dut_conv::thread_O_cast25_cast_fu_333_p1() {
    O_cast25_cast_fu_333_p1 = esl_zext<13,5>(O_fu_327_p2.read());
}

void dut_conv::thread_O_fu_327_p2() {
    O_fu_327_p2 = (!ap_const_lv5_1E.is_01() || !tmp_24_fu_323_p1.read().is_01())? sc_lv<5>(): (sc_bigint<5>(ap_const_lv5_1E) + sc_biguint<5>(tmp_24_fu_323_p1.read()));
}

void dut_conv::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          esl_seteq<1,1,1>(tmp_s_fu_371_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dut_conv::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dut_conv::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(tmp_s_fu_371_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dut_conv::thread_ap_sig_101() {
    ap_sig_101 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void dut_conv::thread_ap_sig_119() {
    ap_sig_119 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void dut_conv::thread_ap_sig_130() {
    ap_sig_130 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void dut_conv::thread_ap_sig_146() {
    ap_sig_146 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void dut_conv::thread_ap_sig_155() {
    ap_sig_155 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void dut_conv::thread_ap_sig_179() {
    ap_sig_179 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void dut_conv::thread_ap_sig_203() {
    ap_sig_203 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void dut_conv::thread_ap_sig_231() {
    ap_sig_231 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void dut_conv::thread_ap_sig_246() {
    ap_sig_246 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(9, 9));
}

void dut_conv::thread_ap_sig_256() {
    ap_sig_256 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(10, 10));
}

void dut_conv::thread_ap_sig_278() {
    ap_sig_278 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(11, 11));
}

void dut_conv::thread_ap_sig_29() {
    ap_sig_29 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void dut_conv::thread_ap_sig_cseq_ST_st10_fsm_9() {
    if (ap_sig_246.read()) {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    }
}

void dut_conv::thread_ap_sig_cseq_ST_st11_fsm_10() {
    if (ap_sig_256.read()) {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    }
}

void dut_conv::thread_ap_sig_cseq_ST_st12_fsm_11() {
    if (ap_sig_278.read()) {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    }
}

void dut_conv::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_29.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void dut_conv::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_101.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void dut_conv::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_119.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void dut_conv::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_130.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void dut_conv::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_146.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void dut_conv::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_155.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void dut_conv::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_179.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void dut_conv::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_203.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void dut_conv::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_231.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void dut_conv::thread_c_3_fu_505_p2() {
    c_3_fu_505_p2 = (!c_reg_277.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(c_reg_277.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void dut_conv::thread_c_cast_fu_495_p1() {
    c_cast_fu_495_p1 = esl_zext<5,2>(c_reg_277.read());
}

void dut_conv::thread_exitcond1_fu_391_p2() {
    exitcond1_fu_391_p2 = (!x_reg_183.read().is_01() || !O_reg_744.read().is_01())? sc_lv<1>(): sc_lv<1>(x_reg_183.read() == O_reg_744.read());
}

void dut_conv::thread_exitcond2_fu_499_p2() {
    exitcond2_fu_499_p2 = (!c_reg_277.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(c_reg_277.read() == ap_const_lv2_3);
}

void dut_conv::thread_exitcond3_fu_406_p2() {
    exitcond3_fu_406_p2 = (!y_reg_195.read().is_01() || !O_reg_744.read().is_01())? sc_lv<1>(): sc_lv<1>(y_reg_195.read() == O_reg_744.read());
}

void dut_conv::thread_exitcond_fu_558_p2() {
    exitcond_fu_558_p2 = (!r_reg_312.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(r_reg_312.read() == ap_const_lv2_3);
}

void dut_conv::thread_i_index_fu_680_p2() {
    i_index_fu_680_p2 = (!x_assign_cast_reg_886.read().is_01() || !tmp7_fu_675_p2.read().is_01())? sc_lv<13>(): (sc_biguint<13>(x_assign_cast_reg_886.read()) + sc_biguint<13>(tmp7_fu_675_p2.read()));
}

void dut_conv::thread_input_r_address0() {
    input_r_address0 =  (sc_lv<13>) (tmp_22_fu_685_p1.read());
}

void dut_conv::thread_input_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        input_r_ce0 = ap_const_logic_1;
    } else {
        input_r_ce0 = ap_const_logic_0;
    }
}

void dut_conv::thread_m_4_fu_454_p2() {
    m_4_fu_454_p2 = (!m_reg_219.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(m_reg_219.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void dut_conv::thread_m_cast_fu_445_p1() {
    m_cast_fu_445_p1 = esl_zext<6,5>(m_reg_219.read());
}

void dut_conv::thread_mac_num_2_fu_664_p3() {
    mac_num_2_fu_664_p3 = (!sel_tmp1_fu_659_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp1_fu_659_p2.read()[0].to_bool())? mac_num_1_reg_300.read(): mac_num_3_fu_647_p2.read());
}

void dut_conv::thread_mac_num_3_fu_647_p2() {
    mac_num_3_fu_647_p2 = (!mac_num_1_reg_300.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(mac_num_1_reg_300.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void dut_conv::thread_n_2_fu_376_p2() {
    n_2_fu_376_p2 = (!n_reg_172.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(n_reg_172.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void dut_conv::thread_n_cast1_fu_363_p1() {
    n_cast1_fu_363_p1 = esl_zext<9,6>(n_reg_172.read());
}

void dut_conv::thread_n_cast_fu_367_p1() {
    n_cast_fu_367_p1 = esl_zext<7,6>(n_reg_172.read());
}

void dut_conv::thread_next_mul4_fu_435_p2() {
    next_mul4_fu_435_p2 = (!phi_mul3_reg_242.read().is_01() || !N_cast_reg_776.read().is_01())? sc_lv<9>(): (sc_biguint<9>(phi_mul3_reg_242.read()) + sc_biguint<9>(N_cast_reg_776.read()));
}

void dut_conv::thread_next_mul_fu_440_p2() {
    next_mul_fu_440_p2 = (!phi_mul_reg_230.read().is_01() || !I_cast5_reg_771.read().is_01())? sc_lv<9>(): (sc_biguint<9>(phi_mul_reg_230.read()) + sc_biguint<9>(I_cast5_reg_771.read()));
}

void dut_conv::thread_notlhs_i_fu_527_p2() {
    notlhs_i_fu_527_p2 = (!tmp_i_reg_760.read().is_01() || !x_assign_fu_511_p2.read().is_01())? sc_lv<1>(): (sc_biguint<5>(tmp_i_reg_760.read()) > sc_biguint<5>(x_assign_fu_511_p2.read()));
}

void dut_conv::thread_notrhs_i_fu_576_p2() {
    notrhs_i_fu_576_p2 = (!y_assign_fu_570_p2.read().is_01() || !ap_const_lv5_0.is_01())? sc_lv<1>(): sc_lv<1>(y_assign_fu_570_p2.read() != ap_const_lv5_0);
}

void dut_conv::thread_o_index_fu_431_p2() {
    o_index_fu_431_p2 = (!tmp5_reg_830.read().is_01() || !x_cast_reg_804.read().is_01())? sc_lv<13>(): (sc_biguint<13>(tmp5_reg_830.read()) + sc_biguint<13>(x_cast_reg_804.read()));
}

void dut_conv::thread_one_out_2_fu_710_p2() {
    one_out_2_fu_710_p2 = (!one_out_1_reg_288.read().is_01() || !p_pn_fu_706_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(one_out_1_reg_288.read()) + sc_biguint<32>(p_pn_fu_706_p1.read()));
}

void dut_conv::thread_one_out_3_fu_716_p3() {
    one_out_3_fu_716_p3 = (!sel_tmp1_reg_929.read()[0].is_01())? sc_lv<32>(): ((sel_tmp1_reg_929.read()[0].to_bool())? one_out_1_reg_288.read(): one_out_2_fu_710_p2.read());
}

void dut_conv::thread_or_cond2_i_fu_592_p2() {
    or_cond2_i_fu_592_p2 = (tmp_fu_587_p2.read() & notrhs_i_fu_576_p2.read());
}

void dut_conv::thread_output_r_address0() {
    output_r_address0 =  (sc_lv<13>) (tmp_17_reg_863.read());
}

void dut_conv::thread_output_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void dut_conv::thread_output_r_d0() {
    output_r_d0 = (!sum_reg_207.read().is_01() || !tmp_18_fu_723_p1.read().is_01())? sc_lv<1>(): (sc_bigint<32>(sum_reg_207.read()) > sc_bigint<32>(tmp_18_fu_723_p1.read()));
}

void dut_conv::thread_output_r_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()))) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void dut_conv::thread_p_pn_fu_706_p1() {
    p_pn_fu_706_p1 = esl_zext<32,1>(p_pn_in_fu_700_p2.read());
}

void dut_conv::thread_p_pn_in_fu_700_p2() {
    p_pn_in_fu_700_p2 = (input_r_q0.read() ^ tmp11_fu_694_p2.read());
}

void dut_conv::thread_p_pn_in_in_v_fu_689_p3() {
    p_pn_in_in_v_fu_689_p3 = (!L.read()[0].is_01())? sc_lv<1>(): ((L.read()[0].to_bool())? w_conv2_load_reg_949.read(): w_conv1_load_reg_944.read());
}

void dut_conv::thread_p_shl1_cast_fu_617_p1() {
    p_shl1_cast_fu_617_p1 = esl_zext<5,4>(p_shl1_fu_609_p3.read());
}

void dut_conv::thread_p_shl1_fu_609_p3() {
    p_shl1_fu_609_p3 = esl_concat<2,2>(r_reg_312.read(), ap_const_lv2_0);
}

void dut_conv::thread_p_shl_cast_fu_477_p1() {
    p_shl_cast_fu_477_p1 = esl_zext<13,12>(p_shl_fu_469_p3.read());
}

void dut_conv::thread_p_shl_fu_469_p3() {
    p_shl_fu_469_p3 = esl_concat<9,3>(tmp_16_fu_460_p2.read(), ap_const_lv3_0);
}

void dut_conv::thread_r_2_fu_564_p2() {
    r_2_fu_564_p2 = (!r_reg_312.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(r_reg_312.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void dut_conv::thread_r_cast1_fu_554_p1() {
    r_cast1_fu_554_p1 = esl_zext<5,2>(r_reg_312.read());
}

void dut_conv::thread_r_cast_fu_550_p1() {
    r_cast_fu_550_p1 = esl_zext<9,2>(r_reg_312.read());
}

void dut_conv::thread_sel_tmp1_fu_659_p2() {
    sel_tmp1_fu_659_p2 = (tmp_i_26_reg_891.read() | sel_tmp_fu_653_p2.read());
}

void dut_conv::thread_sel_tmp_fu_653_p2() {
    sel_tmp_fu_653_p2 = (or_cond2_i_fu_592_p2.read() ^ ap_const_lv1_1);
}

void dut_conv::thread_sum_1_fu_544_p2() {
    sum_1_fu_544_p2 = (!tmp_20_fu_538_p2.read().is_01() || !tmp_30_fu_532_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_20_fu_538_p2.read()) + sc_biguint<32>(tmp_30_fu_532_p2.read()));
}

void dut_conv::thread_threshold_V_address0() {
    threshold_V_address0 =  (sc_lv<13>) (tmp_17_fu_491_p1.read());
}

void dut_conv::thread_threshold_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        threshold_V_ce0 = ap_const_logic_1;
    } else {
        threshold_V_ce0 = ap_const_logic_0;
    }
}

void dut_conv::thread_tmp10_cast_fu_632_p1() {
    tmp10_cast_fu_632_p1 = esl_sext<14,5>(tmp10_fu_627_p2.read());
}

void dut_conv::thread_tmp10_fu_627_p2() {
    tmp10_fu_627_p2 = (!c_cast_reg_873.read().is_01() || !tmp_21_fu_621_p2.read().is_01())? sc_lv<5>(): (sc_biguint<5>(c_cast_reg_873.read()) + sc_biguint<5>(tmp_21_fu_621_p2.read()));
}

void dut_conv::thread_tmp11_fu_694_p2() {
    tmp11_fu_694_p2 = (p_pn_in_in_v_fu_689_p3.read() ^ ap_const_lv1_1);
}

void dut_conv::thread_tmp4_fu_417_p2() {
    tmp4_fu_417_p2 = (!y_cast_fu_402_p1.read().is_01() || !tmp_14_reg_799.read().is_01())? sc_lv<9>(): (sc_biguint<9>(y_cast_fu_402_p1.read()) + sc_biguint<9>(tmp_14_reg_799.read()));
}

void dut_conv::thread_tmp5_fu_426_p0() {
    tmp5_fu_426_p0 =  (sc_lv<9>) (tmp5_fu_426_p00.read());
}

void dut_conv::thread_tmp5_fu_426_p00() {
    tmp5_fu_426_p00 = esl_zext<13,9>(tmp4_fu_417_p2.read());
}

void dut_conv::thread_tmp5_fu_426_p1() {
    tmp5_fu_426_p1 =  (sc_lv<5>) (O_cast25_cast_reg_750.read());
}

void dut_conv::thread_tmp5_fu_426_p2() {
    tmp5_fu_426_p2 = (!tmp5_fu_426_p0.read().is_01() || !tmp5_fu_426_p1.read().is_01())? sc_lv<13>(): sc_biguint<9>(tmp5_fu_426_p0.read()) * sc_biguint<5>(tmp5_fu_426_p1.read());
}

void dut_conv::thread_tmp6_fu_604_p2() {
    tmp6_fu_604_p2 = (!tmp8_fu_598_p2.read().is_01() || !y_cast_reg_817.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp8_fu_598_p2.read()) + sc_biguint<9>(y_cast_reg_817.read()));
}

void dut_conv::thread_tmp7_fu_675_p0() {
    tmp7_fu_675_p0 =  (sc_lv<9>) (tmp7_fu_675_p00.read());
}

void dut_conv::thread_tmp7_fu_675_p00() {
    tmp7_fu_675_p00 = esl_zext<13,9>(tmp6_reg_914.read());
}

void dut_conv::thread_tmp7_fu_675_p1() {
    tmp7_fu_675_p1 =  (sc_lv<6>) (I_cast_reg_781.read());
}

void dut_conv::thread_tmp7_fu_675_p2() {
    tmp7_fu_675_p2 = (!tmp7_fu_675_p0.read().is_01() || !tmp7_fu_675_p1.read().is_01())? sc_lv<13>(): sc_biguint<9>(tmp7_fu_675_p0.read()) * sc_biguint<6>(tmp7_fu_675_p1.read());
}

void dut_conv::thread_tmp8_fu_598_p2() {
    tmp8_fu_598_p2 = (!phi_mul_reg_230.read().is_01() || !r_cast_fu_550_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(phi_mul_reg_230.read()) + sc_biguint<9>(r_cast_fu_550_p1.read()));
}

void dut_conv::thread_tmp9_cast_fu_487_p1() {
    tmp9_cast_fu_487_p1 = esl_zext<14,13>(tmp9_fu_481_p2.read());
}

void dut_conv::thread_tmp9_fu_481_p2() {
    tmp9_fu_481_p2 = (!p_shl_cast_fu_477_p1.read().is_01() || !tmp_29_cast1_fu_465_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(p_shl_cast_fu_477_p1.read()) + sc_biguint<13>(tmp_29_cast1_fu_465_p1.read()));
}

void dut_conv::thread_tmp_12_i_fu_582_p2() {
    tmp_12_i_fu_582_p2 = (!tmp_i_reg_760.read().is_01() || !y_assign_fu_570_p2.read().is_01())? sc_lv<1>(): (sc_biguint<5>(tmp_i_reg_760.read()) > sc_biguint<5>(y_assign_fu_570_p2.read()));
}

void dut_conv::thread_tmp_14_fu_382_p0() {
    tmp_14_fu_382_p0 =  (sc_lv<6>) (tmp_14_fu_382_p00.read());
}

void dut_conv::thread_tmp_14_fu_382_p00() {
    tmp_14_fu_382_p00 = esl_zext<9,6>(n_reg_172.read());
}

void dut_conv::thread_tmp_14_fu_382_p1() {
    tmp_14_fu_382_p1 =  (sc_lv<5>) (O_cast24_cast_reg_755.read());
}

void dut_conv::thread_tmp_14_fu_382_p2() {
    tmp_14_fu_382_p2 = (!tmp_14_fu_382_p0.read().is_01() || !tmp_14_fu_382_p1.read().is_01())? sc_lv<9>(): sc_biguint<6>(tmp_14_fu_382_p0.read()) * sc_biguint<5>(tmp_14_fu_382_p1.read());
}

void dut_conv::thread_tmp_15_fu_449_p2() {
    tmp_15_fu_449_p2 = (!m_cast_fu_445_p1.read().is_01() || !tmp_25_reg_766.read().is_01())? sc_lv<1>(): (sc_bigint<6>(m_cast_fu_445_p1.read()) < sc_bigint<6>(tmp_25_reg_766.read()));
}

void dut_conv::thread_tmp_16_fu_460_p2() {
    tmp_16_fu_460_p2 = (!n_cast1_reg_786.read().is_01() || !phi_mul3_reg_242.read().is_01())? sc_lv<9>(): (sc_biguint<9>(n_cast1_reg_786.read()) + sc_biguint<9>(phi_mul3_reg_242.read()));
}

void dut_conv::thread_tmp_17_fu_491_p1() {
    tmp_17_fu_491_p1 = esl_zext<64,13>(o_index_reg_835.read());
}

void dut_conv::thread_tmp_18_fu_723_p1() {
    tmp_18_fu_723_p1 = esl_sext<32,8>(threshold_V_q0.read());
}

void dut_conv::thread_tmp_20_fu_538_p2() {
    tmp_20_fu_538_p2 = (!sum_reg_207.read().is_01() || !mac_num_reg_265.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sum_reg_207.read()) - sc_biguint<32>(mac_num_reg_265.read()));
}

void dut_conv::thread_tmp_21_fu_621_p2() {
    tmp_21_fu_621_p2 = (!p_shl1_cast_fu_617_p1.read().is_01() || !r_cast1_fu_554_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(p_shl1_cast_fu_617_p1.read()) - sc_biguint<5>(r_cast1_fu_554_p1.read()));
}

void dut_conv::thread_tmp_22_fu_685_p1() {
    tmp_22_fu_685_p1 = esl_zext<64,13>(i_index_reg_939.read());
}

void dut_conv::thread_tmp_23_fu_641_p1() {
    tmp_23_fu_641_p1 = esl_sext<64,14>(w_index_fu_636_p2.read());
}

void dut_conv::thread_tmp_24_fu_323_p1() {
    tmp_24_fu_323_p1 = I.read().range(5-1, 0);
}

void dut_conv::thread_tmp_25_fu_347_p1() {
    tmp_25_fu_347_p1 = M.read().range(6-1, 0);
}

void dut_conv::thread_tmp_29_cast1_fu_465_p1() {
    tmp_29_cast1_fu_465_p1 = esl_zext<13,9>(tmp_16_fu_460_p2.read());
}

void dut_conv::thread_tmp_30_fu_532_p2() {
    tmp_30_fu_532_p2 = (!ap_const_lv32_1.is_01())? sc_lv<32>(): one_out_reg_253.read() << (unsigned short)ap_const_lv32_1.to_uint();
}

void dut_conv::thread_tmp_fu_587_p2() {
    tmp_fu_587_p2 = (notlhs_i_reg_896.read() & tmp_12_i_fu_582_p2.read());
}

void dut_conv::thread_tmp_i_26_fu_521_p2() {
    tmp_i_26_fu_521_p2 = (!x_assign_fu_511_p2.read().is_01() || !ap_const_lv5_0.is_01())? sc_lv<1>(): sc_lv<1>(x_assign_fu_511_p2.read() == ap_const_lv5_0);
}

void dut_conv::thread_tmp_i_fu_341_p2() {
    tmp_i_fu_341_p2 = (!ap_const_lv5_1F.is_01() || !tmp_24_fu_323_p1.read().is_01())? sc_lv<5>(): (sc_bigint<5>(ap_const_lv5_1F) + sc_biguint<5>(tmp_24_fu_323_p1.read()));
}

void dut_conv::thread_tmp_s_fu_371_p2() {
    tmp_s_fu_371_p2 = (!n_cast_fu_367_p1.read().is_01() || !N.read().is_01())? sc_lv<1>(): (sc_bigint<7>(n_cast_fu_367_p1.read()) < sc_bigint<7>(N.read()));
}

void dut_conv::thread_w_conv1_address0() {
    w_conv1_address0 =  (sc_lv<13>) (tmp_23_fu_641_p1.read());
}

void dut_conv::thread_w_conv1_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        w_conv1_ce0 = ap_const_logic_1;
    } else {
        w_conv1_ce0 = ap_const_logic_0;
    }
}

void dut_conv::thread_w_conv2_address0() {
    w_conv2_address0 =  (sc_lv<13>) (tmp_23_fu_641_p1.read());
}

void dut_conv::thread_w_conv2_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        w_conv2_ce0 = ap_const_logic_1;
    } else {
        w_conv2_ce0 = ap_const_logic_0;
    }
}

void dut_conv::thread_w_index_fu_636_p2() {
    w_index_fu_636_p2 = (!tmp10_cast_fu_632_p1.read().is_01() || !tmp9_cast_reg_858.read().is_01())? sc_lv<14>(): (sc_bigint<14>(tmp10_cast_fu_632_p1.read()) + sc_biguint<14>(tmp9_cast_reg_858.read()));
}

void dut_conv::thread_x_4_fu_396_p2() {
    x_4_fu_396_p2 = (!x_reg_183.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(x_reg_183.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void dut_conv::thread_x_assign_cast_fu_517_p1() {
    x_assign_cast_fu_517_p1 = esl_zext<13,5>(x_assign_fu_511_p2.read());
}

void dut_conv::thread_x_assign_fu_511_p2() {
    x_assign_fu_511_p2 = (!c_cast_fu_495_p1.read().is_01() || !x_reg_183.read().is_01())? sc_lv<5>(): (sc_biguint<5>(c_cast_fu_495_p1.read()) + sc_biguint<5>(x_reg_183.read()));
}

void dut_conv::thread_x_cast_fu_387_p1() {
    x_cast_fu_387_p1 = esl_zext<13,5>(x_reg_183.read());
}

void dut_conv::thread_y_4_fu_411_p2() {
    y_4_fu_411_p2 = (!y_reg_195.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(y_reg_195.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void dut_conv::thread_y_assign_fu_570_p2() {
    y_assign_fu_570_p2 = (!r_cast1_fu_554_p1.read().is_01() || !y_reg_195.read().is_01())? sc_lv<5>(): (sc_biguint<5>(r_cast1_fu_554_p1.read()) + sc_biguint<5>(y_reg_195.read()));
}

void dut_conv::thread_y_cast_fu_402_p1() {
    y_cast_fu_402_p1 = esl_zext<9,5>(y_reg_195.read());
}

void dut_conv::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (esl_seteq<1,1,1>(tmp_s_fu_371_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 4 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_391_p2.read())) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            }
            break;
        case 8 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_406_p2.read())) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 32 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_15_fu_449_p2.read())) {
                ap_NS_fsm = ap_ST_st7_fsm_6;
            } else {
                ap_NS_fsm = ap_ST_st12_fsm_11;
            }
            break;
        case 64 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_499_p2.read())) {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            } else {
                ap_NS_fsm = ap_ST_st8_fsm_7;
            }
            break;
        case 128 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_558_p2.read())) {
                ap_NS_fsm = ap_ST_st7_fsm_6;
            } else {
                ap_NS_fsm = ap_ST_st9_fsm_8;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXXXX";
            break;
    }
}

}

