// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dut_pad.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dut_pad::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dut_pad::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<7> dut_pad::ap_ST_st1_fsm_0 = "1";
const sc_lv<7> dut_pad::ap_ST_st2_fsm_1 = "10";
const sc_lv<7> dut_pad::ap_ST_st3_fsm_2 = "100";
const sc_lv<7> dut_pad::ap_ST_st4_fsm_3 = "1000";
const sc_lv<7> dut_pad::ap_ST_st5_fsm_4 = "10000";
const sc_lv<7> dut_pad::ap_ST_st6_fsm_5 = "100000";
const sc_lv<7> dut_pad::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<32> dut_pad::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> dut_pad::ap_const_lv1_1 = "1";
const sc_lv<32> dut_pad::ap_const_lv32_1 = "1";
const sc_lv<1> dut_pad::ap_const_lv1_0 = "0";
const sc_lv<32> dut_pad::ap_const_lv32_2 = "10";
const sc_lv<32> dut_pad::ap_const_lv32_3 = "11";
const sc_lv<32> dut_pad::ap_const_lv32_4 = "100";
const sc_lv<32> dut_pad::ap_const_lv32_5 = "101";
const sc_lv<13> dut_pad::ap_const_lv13_0 = "0000000000000";
const sc_lv<5> dut_pad::ap_const_lv5_0 = "00000";
const sc_lv<8> dut_pad::ap_const_lv8_0 = "00000000";
const sc_lv<32> dut_pad::ap_const_lv32_6 = "110";
const sc_lv<5> dut_pad::ap_const_lv5_2 = "10";
const sc_lv<13> dut_pad::ap_const_lv13_1440 = "1010001000000";
const sc_lv<13> dut_pad::ap_const_lv13_1 = "1";
const sc_lv<5> dut_pad::ap_const_lv5_1 = "1";

dut_pad::dut_pad(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_I_cast7_fu_180_p1);
    sensitive << ( I );

    SC_METHOD(thread_I_cast_fu_183_p1);
    sensitive << ( I );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_2_fu_199_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_2_fu_199_p2 );

    SC_METHOD(thread_ap_sig_116);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_132);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_158);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_62);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_82);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_99);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_24 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_62 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_82 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_99 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_116 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_132 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_158 );

    SC_METHOD(thread_exitcond1_fu_160_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( i_reg_86 );

    SC_METHOD(thread_exitcond_fu_246_p2);
    sensitive << ( I );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( y_cast_fu_242_p1 );

    SC_METHOD(thread_i_1_fu_166_p2);
    sensitive << ( i_reg_86 );

    SC_METHOD(thread_i_index_fu_281_p2);
    sensitive << ( x_cast2_reg_371 );
    sensitive << ( tmp4_reg_397 );

    SC_METHOD(thread_input_r_address0);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( tmp_7_fu_298_p1 );

    SC_METHOD(thread_input_r_ce0);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_m_1_fu_204_p2);
    sensitive << ( m_reg_97 );

    SC_METHOD(thread_m_cast_fu_195_p1);
    sensitive << ( m_reg_97 );

    SC_METHOD(thread_next_mul_fu_186_p2);
    sensitive << ( I_cast7_reg_343 );
    sensitive << ( phi_mul_reg_108 );

    SC_METHOD(thread_o_index_fu_293_p2);
    sensitive << ( tmp_6_cast_reg_384 );
    sensitive << ( tmp6_fu_288_p2 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( tmp_1_fu_172_p1 );
    sensitive << ( tmp_8_fu_303_p1 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( input_r_q0 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( exitcond1_fu_160_p2 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );

    SC_METHOD(thread_tmp4_fu_267_p0);
    sensitive << ( I_cast_reg_348 );
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_tmp4_fu_267_p1);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( tmp4_fu_267_p10 );

    SC_METHOD(thread_tmp4_fu_267_p10);
    sensitive << ( tmp_fu_257_p2 );

    SC_METHOD(thread_tmp4_fu_267_p2);
    sensitive << ( tmp4_fu_267_p0 );
    sensitive << ( tmp4_fu_267_p1 );

    SC_METHOD(thread_tmp5_fu_276_p2);
    sensitive << ( tmp_4_reg_366 );
    sensitive << ( y_2_cast_fu_272_p1 );

    SC_METHOD(thread_tmp6_fu_288_p0);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( tmp6_fu_288_p00 );

    SC_METHOD(thread_tmp6_fu_288_p00);
    sensitive << ( tmp5_reg_402 );

    SC_METHOD(thread_tmp6_fu_288_p1);
    sensitive << ( tmp_cast6_cast_reg_320 );
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );

    SC_METHOD(thread_tmp6_fu_288_p2);
    sensitive << ( tmp6_fu_288_p0 );
    sensitive << ( tmp6_fu_288_p1 );

    SC_METHOD(thread_tmp_1_fu_172_p1);
    sensitive << ( i_reg_86 );

    SC_METHOD(thread_tmp_2_fu_199_p2);
    sensitive << ( tmp_6_reg_338 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( m_cast_fu_195_p1 );

    SC_METHOD(thread_tmp_3_fu_142_p1);
    sensitive << ( I );

    SC_METHOD(thread_tmp_4_fu_210_p0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( tmp_4_fu_210_p00 );

    SC_METHOD(thread_tmp_4_fu_210_p00);
    sensitive << ( m_reg_97 );

    SC_METHOD(thread_tmp_4_fu_210_p1);
    sensitive << ( tmp_cast_cast_reg_325 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_tmp_4_fu_210_p2);
    sensitive << ( tmp_4_fu_210_p0 );
    sensitive << ( tmp_4_fu_210_p1 );

    SC_METHOD(thread_tmp_5_fu_223_p2);
    sensitive << ( I );
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( x_cast_fu_219_p1 );

    SC_METHOD(thread_tmp_6_cast_fu_234_p1);
    sensitive << ( x_2_fu_228_p2 );

    SC_METHOD(thread_tmp_6_fu_177_p1);
    sensitive << ( M );

    SC_METHOD(thread_tmp_7_fu_298_p1);
    sensitive << ( i_index_fu_281_p2 );

    SC_METHOD(thread_tmp_8_fu_303_p1);
    sensitive << ( o_index_reg_407 );

    SC_METHOD(thread_tmp_cast6_cast_fu_152_p1);
    sensitive << ( tmp_s_fu_146_p2 );

    SC_METHOD(thread_tmp_cast_cast_fu_156_p1);
    sensitive << ( tmp_s_fu_146_p2 );

    SC_METHOD(thread_tmp_fu_257_p2);
    sensitive << ( phi_mul_reg_108 );
    sensitive << ( y_cast1_fu_238_p1 );

    SC_METHOD(thread_tmp_s_fu_146_p2);
    sensitive << ( tmp_3_fu_142_p1 );

    SC_METHOD(thread_x_2_fu_228_p2);
    sensitive << ( x_reg_120 );

    SC_METHOD(thread_x_cast2_fu_215_p1);
    sensitive << ( x_reg_120 );

    SC_METHOD(thread_x_cast_fu_219_p1);
    sensitive << ( x_reg_120 );

    SC_METHOD(thread_y_2_cast_fu_272_p1);
    sensitive << ( y_2_fu_251_p2 );

    SC_METHOD(thread_y_2_fu_251_p2);
    sensitive << ( y_reg_131 );

    SC_METHOD(thread_y_cast1_fu_238_p1);
    sensitive << ( y_reg_131 );

    SC_METHOD(thread_y_cast_fu_242_p1);
    sensitive << ( y_reg_131 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond1_fu_160_p2 );
    sensitive << ( tmp_2_fu_199_p2 );
    sensitive << ( tmp_5_fu_223_p2 );
    sensitive << ( exitcond_fu_246_p2 );

    ap_CS_fsm = "0000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dut_pad_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r_address0, "(port)input_r_address0");
    sc_trace(mVcdFile, input_r_ce0, "(port)input_r_ce0");
    sc_trace(mVcdFile, input_r_q0, "(port)input_r_q0");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
    sc_trace(mVcdFile, M, "(port)M");
    sc_trace(mVcdFile, I, "(port)I");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_24, "ap_sig_24");
    sc_trace(mVcdFile, tmp_cast6_cast_fu_152_p1, "tmp_cast6_cast_fu_152_p1");
    sc_trace(mVcdFile, tmp_cast6_cast_reg_320, "tmp_cast6_cast_reg_320");
    sc_trace(mVcdFile, tmp_cast_cast_fu_156_p1, "tmp_cast_cast_fu_156_p1");
    sc_trace(mVcdFile, tmp_cast_cast_reg_325, "tmp_cast_cast_reg_325");
    sc_trace(mVcdFile, i_1_fu_166_p2, "i_1_fu_166_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_62, "ap_sig_62");
    sc_trace(mVcdFile, tmp_6_fu_177_p1, "tmp_6_fu_177_p1");
    sc_trace(mVcdFile, tmp_6_reg_338, "tmp_6_reg_338");
    sc_trace(mVcdFile, exitcond1_fu_160_p2, "exitcond1_fu_160_p2");
    sc_trace(mVcdFile, I_cast7_fu_180_p1, "I_cast7_fu_180_p1");
    sc_trace(mVcdFile, I_cast7_reg_343, "I_cast7_reg_343");
    sc_trace(mVcdFile, I_cast_fu_183_p1, "I_cast_fu_183_p1");
    sc_trace(mVcdFile, I_cast_reg_348, "I_cast_reg_348");
    sc_trace(mVcdFile, next_mul_fu_186_p2, "next_mul_fu_186_p2");
    sc_trace(mVcdFile, next_mul_reg_353, "next_mul_reg_353");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_82, "ap_sig_82");
    sc_trace(mVcdFile, m_1_fu_204_p2, "m_1_fu_204_p2");
    sc_trace(mVcdFile, m_1_reg_361, "m_1_reg_361");
    sc_trace(mVcdFile, tmp_4_fu_210_p2, "tmp_4_fu_210_p2");
    sc_trace(mVcdFile, tmp_4_reg_366, "tmp_4_reg_366");
    sc_trace(mVcdFile, tmp_2_fu_199_p2, "tmp_2_fu_199_p2");
    sc_trace(mVcdFile, x_cast2_fu_215_p1, "x_cast2_fu_215_p1");
    sc_trace(mVcdFile, x_cast2_reg_371, "x_cast2_reg_371");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_99, "ap_sig_99");
    sc_trace(mVcdFile, x_2_fu_228_p2, "x_2_fu_228_p2");
    sc_trace(mVcdFile, x_2_reg_379, "x_2_reg_379");
    sc_trace(mVcdFile, tmp_6_cast_fu_234_p1, "tmp_6_cast_fu_234_p1");
    sc_trace(mVcdFile, tmp_6_cast_reg_384, "tmp_6_cast_reg_384");
    sc_trace(mVcdFile, tmp_5_fu_223_p2, "tmp_5_fu_223_p2");
    sc_trace(mVcdFile, y_2_fu_251_p2, "y_2_fu_251_p2");
    sc_trace(mVcdFile, y_2_reg_392, "y_2_reg_392");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_116, "ap_sig_116");
    sc_trace(mVcdFile, tmp4_fu_267_p2, "tmp4_fu_267_p2");
    sc_trace(mVcdFile, tmp4_reg_397, "tmp4_reg_397");
    sc_trace(mVcdFile, exitcond_fu_246_p2, "exitcond_fu_246_p2");
    sc_trace(mVcdFile, tmp5_fu_276_p2, "tmp5_fu_276_p2");
    sc_trace(mVcdFile, tmp5_reg_402, "tmp5_reg_402");
    sc_trace(mVcdFile, o_index_fu_293_p2, "o_index_fu_293_p2");
    sc_trace(mVcdFile, o_index_reg_407, "o_index_reg_407");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_132, "ap_sig_132");
    sc_trace(mVcdFile, i_reg_86, "i_reg_86");
    sc_trace(mVcdFile, m_reg_97, "m_reg_97");
    sc_trace(mVcdFile, phi_mul_reg_108, "phi_mul_reg_108");
    sc_trace(mVcdFile, x_reg_120, "x_reg_120");
    sc_trace(mVcdFile, y_reg_131, "y_reg_131");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_158, "ap_sig_158");
    sc_trace(mVcdFile, tmp_1_fu_172_p1, "tmp_1_fu_172_p1");
    sc_trace(mVcdFile, tmp_7_fu_298_p1, "tmp_7_fu_298_p1");
    sc_trace(mVcdFile, tmp_8_fu_303_p1, "tmp_8_fu_303_p1");
    sc_trace(mVcdFile, tmp_3_fu_142_p1, "tmp_3_fu_142_p1");
    sc_trace(mVcdFile, tmp_s_fu_146_p2, "tmp_s_fu_146_p2");
    sc_trace(mVcdFile, m_cast_fu_195_p1, "m_cast_fu_195_p1");
    sc_trace(mVcdFile, tmp_4_fu_210_p0, "tmp_4_fu_210_p0");
    sc_trace(mVcdFile, tmp_4_fu_210_p1, "tmp_4_fu_210_p1");
    sc_trace(mVcdFile, x_cast_fu_219_p1, "x_cast_fu_219_p1");
    sc_trace(mVcdFile, y_cast_fu_242_p1, "y_cast_fu_242_p1");
    sc_trace(mVcdFile, y_cast1_fu_238_p1, "y_cast1_fu_238_p1");
    sc_trace(mVcdFile, tmp_fu_257_p2, "tmp_fu_257_p2");
    sc_trace(mVcdFile, tmp4_fu_267_p0, "tmp4_fu_267_p0");
    sc_trace(mVcdFile, tmp4_fu_267_p1, "tmp4_fu_267_p1");
    sc_trace(mVcdFile, y_2_cast_fu_272_p1, "y_2_cast_fu_272_p1");
    sc_trace(mVcdFile, tmp6_fu_288_p0, "tmp6_fu_288_p0");
    sc_trace(mVcdFile, tmp6_fu_288_p1, "tmp6_fu_288_p1");
    sc_trace(mVcdFile, tmp6_fu_288_p2, "tmp6_fu_288_p2");
    sc_trace(mVcdFile, i_index_fu_281_p2, "i_index_fu_281_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, tmp4_fu_267_p10, "tmp4_fu_267_p10");
    sc_trace(mVcdFile, tmp6_fu_288_p00, "tmp6_fu_288_p00");
    sc_trace(mVcdFile, tmp_4_fu_210_p00, "tmp_4_fu_210_p00");
#endif

    }
}

dut_pad::~dut_pad() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void dut_pad::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_160_p2.read(), ap_const_lv1_0))) {
        i_reg_86 = i_1_fu_166_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        i_reg_86 = ap_const_lv13_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_223_p2.read()))) {
        m_reg_97 = m_1_reg_361.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                !esl_seteq<1,1,1>(exitcond1_fu_160_p2.read(), ap_const_lv1_0))) {
        m_reg_97 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_223_p2.read()))) {
        phi_mul_reg_108 = next_mul_reg_353.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                !esl_seteq<1,1,1>(exitcond1_fu_160_p2.read(), ap_const_lv1_0))) {
        phi_mul_reg_108 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_246_p2.read()))) {
        x_reg_120 = x_2_reg_379.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_fu_199_p2.read()))) {
        x_reg_120 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_223_p2.read()))) {
        y_reg_131 = ap_const_lv5_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        y_reg_131 = y_2_reg_392.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && !esl_seteq<1,1,1>(exitcond1_fu_160_p2.read(), ap_const_lv1_0))) {
        I_cast7_reg_343 = I_cast7_fu_180_p1.read();
        I_cast_reg_348 = I_cast_fu_183_p1.read();
        tmp_6_reg_338 = tmp_6_fu_177_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        m_1_reg_361 = m_1_fu_204_p2.read();
        next_mul_reg_353 = next_mul_fu_186_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        o_index_reg_407 = o_index_fu_293_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_246_p2.read()))) {
        tmp4_reg_397 = tmp4_fu_267_p2.read();
        tmp5_reg_402 = tmp5_fu_276_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_fu_199_p2.read()))) {
        tmp_4_reg_366 = tmp_4_fu_210_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_223_p2.read()))) {
        tmp_6_cast_reg_384 = tmp_6_cast_fu_234_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        tmp_cast6_cast_reg_320 = tmp_cast6_cast_fu_152_p1.read();
        tmp_cast_cast_reg_325 = tmp_cast_cast_fu_156_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        x_2_reg_379 = x_2_fu_228_p2.read();
        x_cast2_reg_371 = x_cast2_fu_215_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        y_2_reg_392 = y_2_fu_251_p2.read();
    }
}

void dut_pad::thread_I_cast7_fu_180_p1() {
    I_cast7_fu_180_p1 = esl_zext<8,6>(I.read());
}

void dut_pad::thread_I_cast_fu_183_p1() {
    I_cast_fu_183_p1 = esl_zext<13,6>(I.read());
}

void dut_pad::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_fu_199_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dut_pad::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dut_pad::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_fu_199_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dut_pad::thread_ap_sig_116() {
    ap_sig_116 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void dut_pad::thread_ap_sig_132() {
    ap_sig_132 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void dut_pad::thread_ap_sig_158() {
    ap_sig_158 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void dut_pad::thread_ap_sig_24() {
    ap_sig_24 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void dut_pad::thread_ap_sig_62() {
    ap_sig_62 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void dut_pad::thread_ap_sig_82() {
    ap_sig_82 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void dut_pad::thread_ap_sig_99() {
    ap_sig_99 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void dut_pad::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_24.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void dut_pad::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_62.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void dut_pad::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_82.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void dut_pad::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_99.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void dut_pad::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_116.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void dut_pad::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_132.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void dut_pad::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_158.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void dut_pad::thread_exitcond1_fu_160_p2() {
    exitcond1_fu_160_p2 = (!i_reg_86.read().is_01() || !ap_const_lv13_1440.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_86.read() == ap_const_lv13_1440);
}

void dut_pad::thread_exitcond_fu_246_p2() {
    exitcond_fu_246_p2 = (!y_cast_fu_242_p1.read().is_01() || !I.read().is_01())? sc_lv<1>(): sc_lv<1>(y_cast_fu_242_p1.read() == I.read());
}

void dut_pad::thread_i_1_fu_166_p2() {
    i_1_fu_166_p2 = (!i_reg_86.read().is_01() || !ap_const_lv13_1.is_01())? sc_lv<13>(): (sc_biguint<13>(i_reg_86.read()) + sc_biguint<13>(ap_const_lv13_1));
}

void dut_pad::thread_i_index_fu_281_p2() {
    i_index_fu_281_p2 = (!tmp4_reg_397.read().is_01() || !x_cast2_reg_371.read().is_01())? sc_lv<13>(): (sc_biguint<13>(tmp4_reg_397.read()) + sc_biguint<13>(x_cast2_reg_371.read()));
}

void dut_pad::thread_input_r_address0() {
    input_r_address0 =  (sc_lv<13>) (tmp_7_fu_298_p1.read());
}

void dut_pad::thread_input_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        input_r_ce0 = ap_const_logic_1;
    } else {
        input_r_ce0 = ap_const_logic_0;
    }
}

void dut_pad::thread_m_1_fu_204_p2() {
    m_1_fu_204_p2 = (!m_reg_97.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(m_reg_97.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void dut_pad::thread_m_cast_fu_195_p1() {
    m_cast_fu_195_p1 = esl_zext<6,5>(m_reg_97.read());
}

void dut_pad::thread_next_mul_fu_186_p2() {
    next_mul_fu_186_p2 = (!phi_mul_reg_108.read().is_01() || !I_cast7_reg_343.read().is_01())? sc_lv<8>(): (sc_biguint<8>(phi_mul_reg_108.read()) + sc_biguint<8>(I_cast7_reg_343.read()));
}

void dut_pad::thread_o_index_fu_293_p2() {
    o_index_fu_293_p2 = (!tmp_6_cast_reg_384.read().is_01() || !tmp6_fu_288_p2.read().is_01())? sc_lv<13>(): (sc_biguint<13>(tmp_6_cast_reg_384.read()) + sc_biguint<13>(tmp6_fu_288_p2.read()));
}

void dut_pad::thread_output_r_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        output_r_address0 =  (sc_lv<13>) (tmp_8_fu_303_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        output_r_address0 =  (sc_lv<13>) (tmp_1_fu_172_p1.read());
    } else {
        output_r_address0 = "XXXXXXXXXXXXX";
    }
}

void dut_pad::thread_output_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()))) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void dut_pad::thread_output_r_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read())) {
        output_r_d0 = input_r_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        output_r_d0 = ap_const_lv1_0;
    } else {
        output_r_d0 =  (sc_lv<1>) ("X");
    }
}

void dut_pad::thread_output_r_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          esl_seteq<1,1,1>(exitcond1_fu_160_p2.read(), ap_const_lv1_0)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()))) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void dut_pad::thread_tmp4_fu_267_p0() {
    tmp4_fu_267_p0 =  (sc_lv<6>) (I_cast_reg_348.read());
}

void dut_pad::thread_tmp4_fu_267_p1() {
    tmp4_fu_267_p1 =  (sc_lv<8>) (tmp4_fu_267_p10.read());
}

void dut_pad::thread_tmp4_fu_267_p10() {
    tmp4_fu_267_p10 = esl_zext<13,8>(tmp_fu_257_p2.read());
}

void dut_pad::thread_tmp4_fu_267_p2() {
    tmp4_fu_267_p2 = (!tmp4_fu_267_p0.read().is_01() || !tmp4_fu_267_p1.read().is_01())? sc_lv<13>(): sc_biguint<6>(tmp4_fu_267_p0.read()) * sc_biguint<8>(tmp4_fu_267_p1.read());
}

void dut_pad::thread_tmp5_fu_276_p2() {
    tmp5_fu_276_p2 = (!y_2_cast_fu_272_p1.read().is_01() || !tmp_4_reg_366.read().is_01())? sc_lv<9>(): (sc_biguint<9>(y_2_cast_fu_272_p1.read()) + sc_biguint<9>(tmp_4_reg_366.read()));
}

void dut_pad::thread_tmp6_fu_288_p0() {
    tmp6_fu_288_p0 =  (sc_lv<9>) (tmp6_fu_288_p00.read());
}

void dut_pad::thread_tmp6_fu_288_p00() {
    tmp6_fu_288_p00 = esl_zext<13,9>(tmp5_reg_402.read());
}

void dut_pad::thread_tmp6_fu_288_p1() {
    tmp6_fu_288_p1 =  (sc_lv<5>) (tmp_cast6_cast_reg_320.read());
}

void dut_pad::thread_tmp6_fu_288_p2() {
    tmp6_fu_288_p2 = (!tmp6_fu_288_p0.read().is_01() || !tmp6_fu_288_p1.read().is_01())? sc_lv<13>(): sc_biguint<9>(tmp6_fu_288_p0.read()) * sc_biguint<5>(tmp6_fu_288_p1.read());
}

void dut_pad::thread_tmp_1_fu_172_p1() {
    tmp_1_fu_172_p1 = esl_zext<64,13>(i_reg_86.read());
}

void dut_pad::thread_tmp_2_fu_199_p2() {
    tmp_2_fu_199_p2 = (!m_cast_fu_195_p1.read().is_01() || !tmp_6_reg_338.read().is_01())? sc_lv<1>(): (sc_bigint<6>(m_cast_fu_195_p1.read()) < sc_bigint<6>(tmp_6_reg_338.read()));
}

void dut_pad::thread_tmp_3_fu_142_p1() {
    tmp_3_fu_142_p1 = I.read().range(5-1, 0);
}

void dut_pad::thread_tmp_4_fu_210_p0() {
    tmp_4_fu_210_p0 =  (sc_lv<5>) (tmp_4_fu_210_p00.read());
}

void dut_pad::thread_tmp_4_fu_210_p00() {
    tmp_4_fu_210_p00 = esl_zext<9,5>(m_reg_97.read());
}

void dut_pad::thread_tmp_4_fu_210_p1() {
    tmp_4_fu_210_p1 =  (sc_lv<5>) (tmp_cast_cast_reg_325.read());
}

void dut_pad::thread_tmp_4_fu_210_p2() {
    tmp_4_fu_210_p2 = (!tmp_4_fu_210_p0.read().is_01() || !tmp_4_fu_210_p1.read().is_01())? sc_lv<9>(): sc_biguint<5>(tmp_4_fu_210_p0.read()) * sc_biguint<5>(tmp_4_fu_210_p1.read());
}

void dut_pad::thread_tmp_5_fu_223_p2() {
    tmp_5_fu_223_p2 = (!x_cast_fu_219_p1.read().is_01() || !I.read().is_01())? sc_lv<1>(): (sc_bigint<6>(x_cast_fu_219_p1.read()) < sc_bigint<6>(I.read()));
}

void dut_pad::thread_tmp_6_cast_fu_234_p1() {
    tmp_6_cast_fu_234_p1 = esl_zext<13,5>(x_2_fu_228_p2.read());
}

void dut_pad::thread_tmp_6_fu_177_p1() {
    tmp_6_fu_177_p1 = M.read().range(6-1, 0);
}

void dut_pad::thread_tmp_7_fu_298_p1() {
    tmp_7_fu_298_p1 = esl_zext<64,13>(i_index_fu_281_p2.read());
}

void dut_pad::thread_tmp_8_fu_303_p1() {
    tmp_8_fu_303_p1 = esl_zext<64,13>(o_index_reg_407.read());
}

void dut_pad::thread_tmp_cast6_cast_fu_152_p1() {
    tmp_cast6_cast_fu_152_p1 = esl_zext<13,5>(tmp_s_fu_146_p2.read());
}

void dut_pad::thread_tmp_cast_cast_fu_156_p1() {
    tmp_cast_cast_fu_156_p1 = esl_zext<9,5>(tmp_s_fu_146_p2.read());
}

void dut_pad::thread_tmp_fu_257_p2() {
    tmp_fu_257_p2 = (!y_cast1_fu_238_p1.read().is_01() || !phi_mul_reg_108.read().is_01())? sc_lv<8>(): (sc_biguint<8>(y_cast1_fu_238_p1.read()) + sc_biguint<8>(phi_mul_reg_108.read()));
}

void dut_pad::thread_tmp_s_fu_146_p2() {
    tmp_s_fu_146_p2 = (!ap_const_lv5_2.is_01() || !tmp_3_fu_142_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(ap_const_lv5_2) + sc_biguint<5>(tmp_3_fu_142_p1.read()));
}

void dut_pad::thread_x_2_fu_228_p2() {
    x_2_fu_228_p2 = (!x_reg_120.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(x_reg_120.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void dut_pad::thread_x_cast2_fu_215_p1() {
    x_cast2_fu_215_p1 = esl_zext<13,5>(x_reg_120.read());
}

void dut_pad::thread_x_cast_fu_219_p1() {
    x_cast_fu_219_p1 = esl_zext<6,5>(x_reg_120.read());
}

void dut_pad::thread_y_2_cast_fu_272_p1() {
    y_2_cast_fu_272_p1 = esl_zext<9,5>(y_2_fu_251_p2.read());
}

void dut_pad::thread_y_2_fu_251_p2() {
    y_2_fu_251_p2 = (!y_reg_131.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(y_reg_131.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void dut_pad::thread_y_cast1_fu_238_p1() {
    y_cast1_fu_238_p1 = esl_zext<8,5>(y_reg_131.read());
}

void dut_pad::thread_y_cast_fu_242_p1() {
    y_cast_fu_242_p1 = esl_zext<6,5>(y_reg_131.read());
}

void dut_pad::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(exitcond1_fu_160_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        case 4 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_2_fu_199_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            }
            break;
        case 8 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_5_fu_223_p2.read())) {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 16 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_246_p2.read())) {
                ap_NS_fsm = ap_ST_st6_fsm_5;
            } else {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<7>) ("XXXXXXX");
            break;
    }
}

}

