// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "max_pool.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic max_pool::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic max_pool::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> max_pool::ap_ST_fsm_state1 = "1";
const sc_lv<9> max_pool::ap_ST_fsm_state2 = "10";
const sc_lv<9> max_pool::ap_ST_fsm_state3 = "100";
const sc_lv<9> max_pool::ap_ST_fsm_state4 = "1000";
const sc_lv<9> max_pool::ap_ST_fsm_state5 = "10000";
const sc_lv<9> max_pool::ap_ST_fsm_state6 = "100000";
const sc_lv<9> max_pool::ap_ST_fsm_state7 = "1000000";
const sc_lv<9> max_pool::ap_ST_fsm_state8 = "10000000";
const sc_lv<9> max_pool::ap_ST_fsm_state9 = "100000000";
const sc_lv<32> max_pool::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> max_pool::ap_const_lv32_1 = "1";
const sc_lv<1> max_pool::ap_const_lv1_1 = "1";
const sc_lv<32> max_pool::ap_const_lv32_2 = "10";
const sc_lv<32> max_pool::ap_const_lv32_3 = "11";
const sc_lv<1> max_pool::ap_const_lv1_0 = "0";
const sc_lv<32> max_pool::ap_const_lv32_4 = "100";
const sc_lv<32> max_pool::ap_const_lv32_5 = "101";
const sc_lv<32> max_pool::ap_const_lv32_6 = "110";
const sc_lv<32> max_pool::ap_const_lv32_7 = "111";
const sc_lv<32> max_pool::ap_const_lv32_8 = "1000";
const sc_lv<13> max_pool::ap_const_lv13_0 = "0000000000000";
const sc_lv<6> max_pool::ap_const_lv6_0 = "000000";
const sc_lv<9> max_pool::ap_const_lv9_0 = "000000000";
const sc_lv<4> max_pool::ap_const_lv4_0 = "0000";
const sc_lv<2> max_pool::ap_const_lv2_0 = "00";
const sc_lv<13> max_pool::ap_const_lv13_1440 = "1010001000000";
const sc_lv<13> max_pool::ap_const_lv13_1 = "1";
const sc_lv<6> max_pool::ap_const_lv6_1 = "1";
const sc_lv<4> max_pool::ap_const_lv4_1 = "1";
const sc_lv<2> max_pool::ap_const_lv2_2 = "10";
const sc_lv<2> max_pool::ap_const_lv2_1 = "1";
const bool max_pool::ap_const_boolean_1 = true;

max_pool::max_pool(sc_module_name name) : sc_module(name), mVcdFile(0) {
    dut_mac_muladd_8neOg_U21 = new dut_mac_muladd_8neOg<1,1,8,4,4,11>("dut_mac_muladd_8neOg_U21");
    dut_mac_muladd_8neOg_U21->din0(grp_fu_402_p0);
    dut_mac_muladd_8neOg_U21->din1(grp_fu_402_p1);
    dut_mac_muladd_8neOg_U21->din2(grp_fu_402_p2);
    dut_mac_muladd_8neOg_U21->dout(grp_fu_402_p3);
    dut_mac_muladd_6nfYi_U22 = new dut_mac_muladd_6nfYi<1,1,6,9,4,13>("dut_mac_muladd_6nfYi_U22");
    dut_mac_muladd_6nfYi_U22->din0(grp_fu_408_p0);
    dut_mac_muladd_6nfYi_U22->din1(grp_fu_408_p1);
    dut_mac_muladd_6nfYi_U22->din2(grp_fu_408_p2);
    dut_mac_muladd_6nfYi_U22->dout(grp_fu_408_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_I_cast_fu_246_p1);
    sensitive << ( I );

    SC_METHOD(thread_O_fu_208_p4);
    sensitive << ( I );

    SC_METHOD(thread_add_ln113_1_fu_249_p2);
    sensitive << ( zext_ln113_1_reg_450 );
    sensitive << ( phi_mul_reg_127 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln106_fu_262_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln106_fu_262_p2 );

    SC_METHOD(thread_c_fu_347_p2);
    sensitive << ( c_0_reg_174 );

    SC_METHOD(thread_grp_fu_402_p0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln108_fu_307_p2 );
    sensitive << ( grp_fu_402_p00 );

    SC_METHOD(thread_grp_fu_402_p00);
    sensitive << ( tmp_fu_318_p2 );

    SC_METHOD(thread_grp_fu_402_p1);
    sensitive << ( zext_ln109_reg_432 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln108_fu_307_p2 );

    SC_METHOD(thread_grp_fu_402_p2);
    sensitive << ( zext_ln107_reg_478 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln108_fu_307_p2 );

    SC_METHOD(thread_grp_fu_408_p0);
    sensitive << ( I_cast_reg_455 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_grp_fu_408_p1);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_fu_408_p10 );

    SC_METHOD(thread_grp_fu_408_p10);
    sensitive << ( tmp5_reg_535 );

    SC_METHOD(thread_grp_fu_408_p2);
    sensitive << ( zext_ln113_3_reg_491 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_i_fu_232_p2);
    sensitive << ( i_0_reg_105 );

    SC_METHOD(thread_i_index_fu_387_p2);
    sensitive << ( zext_ln111_reg_514 );
    sensitive << ( grp_fu_408_p3 );

    SC_METHOD(thread_icmp_ln104_fu_226_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_105 );

    SC_METHOD(thread_icmp_ln106_fu_262_p2);
    sensitive << ( M );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln106_fu_258_p1 );

    SC_METHOD(thread_icmp_ln107_fu_282_p2);
    sensitive << ( O_reg_426 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( x_0_reg_139 );

    SC_METHOD(thread_icmp_ln108_fu_307_p2);
    sensitive << ( O_reg_426 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( y_0_reg_150 );

    SC_METHOD(thread_icmp_ln111_fu_341_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( c_0_reg_174 );

    SC_METHOD(thread_icmp_ln112_fu_361_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( r_0_reg_197 );

    SC_METHOD(thread_input_r_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( zext_ln114_fu_391_p1 );

    SC_METHOD(thread_input_r_ce0);
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_m_fu_267_p2);
    sensitive << ( m_0_reg_116 );

    SC_METHOD(thread_mul_ln113_fu_273_p0);
    sensitive << ( zext_ln113_reg_437 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_mul_ln113_fu_273_p1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( mul_ln113_fu_273_p10 );

    SC_METHOD(thread_mul_ln113_fu_273_p10);
    sensitive << ( m_0_reg_116 );

    SC_METHOD(thread_mul_ln113_fu_273_p2);
    sensitive << ( mul_ln113_fu_273_p0 );
    sensitive << ( mul_ln113_fu_273_p1 );

    SC_METHOD(thread_or_ln114_fu_396_p2);
    sensitive << ( input_r_q0 );
    sensitive << ( max_1_reg_185 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln104_fu_238_p1 );
    sensitive << ( zext_ln117_fu_353_p1 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( max_0_reg_161 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln104_fu_226_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln111_fu_341_p2 );

    SC_METHOD(thread_r_fu_367_p2);
    sensitive << ( r_0_reg_197 );

    SC_METHOD(thread_shl_ln113_1_fu_327_p2);
    sensitive << ( y_0_reg_150 );

    SC_METHOD(thread_shl_ln113_fu_293_p2);
    sensitive << ( x_0_reg_139 );

    SC_METHOD(thread_tmp1_fu_373_p2);
    sensitive << ( phi_mul_reg_127 );
    sensitive << ( zext_ln112_fu_357_p1 );

    SC_METHOD(thread_tmp5_fu_379_p2);
    sensitive << ( zext_ln113_4_reg_509 );
    sensitive << ( tmp1_fu_373_p2 );

    SC_METHOD(thread_tmp_fu_318_p2);
    sensitive << ( mul_ln113_reg_473 );
    sensitive << ( zext_ln108_fu_303_p1 );

    SC_METHOD(thread_x_fu_287_p2);
    sensitive << ( x_0_reg_139 );

    SC_METHOD(thread_y_fu_312_p2);
    sensitive << ( y_0_reg_150 );

    SC_METHOD(thread_zext_ln104_fu_238_p1);
    sensitive << ( i_0_reg_105 );

    SC_METHOD(thread_zext_ln106_fu_258_p1);
    sensitive << ( m_0_reg_116 );

    SC_METHOD(thread_zext_ln107_fu_278_p1);
    sensitive << ( x_0_reg_139 );

    SC_METHOD(thread_zext_ln108_fu_303_p1);
    sensitive << ( y_0_reg_150 );

    SC_METHOD(thread_zext_ln109_fu_218_p1);
    sensitive << ( O_fu_208_p4 );

    SC_METHOD(thread_zext_ln111_fu_337_p1);
    sensitive << ( c_0_reg_174 );

    SC_METHOD(thread_zext_ln112_fu_357_p1);
    sensitive << ( r_0_reg_197 );

    SC_METHOD(thread_zext_ln113_1_fu_243_p1);
    sensitive << ( I );

    SC_METHOD(thread_zext_ln113_3_fu_299_p1);
    sensitive << ( shl_ln113_fu_293_p2 );

    SC_METHOD(thread_zext_ln113_4_fu_333_p1);
    sensitive << ( shl_ln113_1_fu_327_p2 );

    SC_METHOD(thread_zext_ln113_fu_222_p1);
    sensitive << ( O_fu_208_p4 );

    SC_METHOD(thread_zext_ln114_fu_391_p1);
    sensitive << ( i_index_fu_387_p2 );

    SC_METHOD(thread_zext_ln117_fu_353_p1);
    sensitive << ( o_index_reg_504 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln104_fu_226_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln106_fu_262_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln107_fu_282_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln108_fu_307_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln112_fu_361_p2 );
    sensitive << ( icmp_ln111_fu_341_p2 );

    ap_CS_fsm = "000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "max_pool_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_r_address0, "(port)input_r_address0");
    sc_trace(mVcdFile, input_r_ce0, "(port)input_r_ce0");
    sc_trace(mVcdFile, input_r_q0, "(port)input_r_q0");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
    sc_trace(mVcdFile, M, "(port)M");
    sc_trace(mVcdFile, I, "(port)I");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, O_fu_208_p4, "O_fu_208_p4");
    sc_trace(mVcdFile, O_reg_426, "O_reg_426");
    sc_trace(mVcdFile, zext_ln109_fu_218_p1, "zext_ln109_fu_218_p1");
    sc_trace(mVcdFile, zext_ln109_reg_432, "zext_ln109_reg_432");
    sc_trace(mVcdFile, zext_ln113_fu_222_p1, "zext_ln113_fu_222_p1");
    sc_trace(mVcdFile, zext_ln113_reg_437, "zext_ln113_reg_437");
    sc_trace(mVcdFile, i_fu_232_p2, "i_fu_232_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, zext_ln113_1_fu_243_p1, "zext_ln113_1_fu_243_p1");
    sc_trace(mVcdFile, zext_ln113_1_reg_450, "zext_ln113_1_reg_450");
    sc_trace(mVcdFile, icmp_ln104_fu_226_p2, "icmp_ln104_fu_226_p2");
    sc_trace(mVcdFile, I_cast_fu_246_p1, "I_cast_fu_246_p1");
    sc_trace(mVcdFile, I_cast_reg_455, "I_cast_reg_455");
    sc_trace(mVcdFile, add_ln113_1_fu_249_p2, "add_ln113_1_fu_249_p2");
    sc_trace(mVcdFile, add_ln113_1_reg_460, "add_ln113_1_reg_460");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, m_fu_267_p2, "m_fu_267_p2");
    sc_trace(mVcdFile, m_reg_468, "m_reg_468");
    sc_trace(mVcdFile, mul_ln113_fu_273_p2, "mul_ln113_fu_273_p2");
    sc_trace(mVcdFile, mul_ln113_reg_473, "mul_ln113_reg_473");
    sc_trace(mVcdFile, icmp_ln106_fu_262_p2, "icmp_ln106_fu_262_p2");
    sc_trace(mVcdFile, zext_ln107_fu_278_p1, "zext_ln107_fu_278_p1");
    sc_trace(mVcdFile, zext_ln107_reg_478, "zext_ln107_reg_478");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, x_fu_287_p2, "x_fu_287_p2");
    sc_trace(mVcdFile, x_reg_486, "x_reg_486");
    sc_trace(mVcdFile, zext_ln113_3_fu_299_p1, "zext_ln113_3_fu_299_p1");
    sc_trace(mVcdFile, zext_ln113_3_reg_491, "zext_ln113_3_reg_491");
    sc_trace(mVcdFile, icmp_ln107_fu_282_p2, "icmp_ln107_fu_282_p2");
    sc_trace(mVcdFile, y_fu_312_p2, "y_fu_312_p2");
    sc_trace(mVcdFile, y_reg_499, "y_reg_499");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, grp_fu_402_p3, "grp_fu_402_p3");
    sc_trace(mVcdFile, o_index_reg_504, "o_index_reg_504");
    sc_trace(mVcdFile, icmp_ln108_fu_307_p2, "icmp_ln108_fu_307_p2");
    sc_trace(mVcdFile, zext_ln113_4_fu_333_p1, "zext_ln113_4_fu_333_p1");
    sc_trace(mVcdFile, zext_ln113_4_reg_509, "zext_ln113_4_reg_509");
    sc_trace(mVcdFile, zext_ln111_fu_337_p1, "zext_ln111_fu_337_p1");
    sc_trace(mVcdFile, zext_ln111_reg_514, "zext_ln111_reg_514");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, c_fu_347_p2, "c_fu_347_p2");
    sc_trace(mVcdFile, c_reg_522, "c_reg_522");
    sc_trace(mVcdFile, r_fu_367_p2, "r_fu_367_p2");
    sc_trace(mVcdFile, r_reg_530, "r_reg_530");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp5_fu_379_p2, "tmp5_fu_379_p2");
    sc_trace(mVcdFile, tmp5_reg_535, "tmp5_reg_535");
    sc_trace(mVcdFile, icmp_ln112_fu_361_p2, "icmp_ln112_fu_361_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, or_ln114_fu_396_p2, "or_ln114_fu_396_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, i_0_reg_105, "i_0_reg_105");
    sc_trace(mVcdFile, m_0_reg_116, "m_0_reg_116");
    sc_trace(mVcdFile, phi_mul_reg_127, "phi_mul_reg_127");
    sc_trace(mVcdFile, x_0_reg_139, "x_0_reg_139");
    sc_trace(mVcdFile, y_0_reg_150, "y_0_reg_150");
    sc_trace(mVcdFile, icmp_ln111_fu_341_p2, "icmp_ln111_fu_341_p2");
    sc_trace(mVcdFile, max_0_reg_161, "max_0_reg_161");
    sc_trace(mVcdFile, c_0_reg_174, "c_0_reg_174");
    sc_trace(mVcdFile, max_1_reg_185, "max_1_reg_185");
    sc_trace(mVcdFile, r_0_reg_197, "r_0_reg_197");
    sc_trace(mVcdFile, zext_ln104_fu_238_p1, "zext_ln104_fu_238_p1");
    sc_trace(mVcdFile, zext_ln117_fu_353_p1, "zext_ln117_fu_353_p1");
    sc_trace(mVcdFile, zext_ln114_fu_391_p1, "zext_ln114_fu_391_p1");
    sc_trace(mVcdFile, zext_ln106_fu_258_p1, "zext_ln106_fu_258_p1");
    sc_trace(mVcdFile, mul_ln113_fu_273_p0, "mul_ln113_fu_273_p0");
    sc_trace(mVcdFile, mul_ln113_fu_273_p1, "mul_ln113_fu_273_p1");
    sc_trace(mVcdFile, shl_ln113_fu_293_p2, "shl_ln113_fu_293_p2");
    sc_trace(mVcdFile, zext_ln108_fu_303_p1, "zext_ln108_fu_303_p1");
    sc_trace(mVcdFile, tmp_fu_318_p2, "tmp_fu_318_p2");
    sc_trace(mVcdFile, shl_ln113_1_fu_327_p2, "shl_ln113_1_fu_327_p2");
    sc_trace(mVcdFile, zext_ln112_fu_357_p1, "zext_ln112_fu_357_p1");
    sc_trace(mVcdFile, tmp1_fu_373_p2, "tmp1_fu_373_p2");
    sc_trace(mVcdFile, grp_fu_408_p3, "grp_fu_408_p3");
    sc_trace(mVcdFile, i_index_fu_387_p2, "i_index_fu_387_p2");
    sc_trace(mVcdFile, grp_fu_402_p0, "grp_fu_402_p0");
    sc_trace(mVcdFile, grp_fu_402_p1, "grp_fu_402_p1");
    sc_trace(mVcdFile, grp_fu_402_p2, "grp_fu_402_p2");
    sc_trace(mVcdFile, grp_fu_408_p0, "grp_fu_408_p0");
    sc_trace(mVcdFile, grp_fu_408_p1, "grp_fu_408_p1");
    sc_trace(mVcdFile, grp_fu_408_p2, "grp_fu_408_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, grp_fu_402_p00, "grp_fu_402_p00");
    sc_trace(mVcdFile, grp_fu_408_p10, "grp_fu_408_p10");
    sc_trace(mVcdFile, mul_ln113_fu_273_p10, "mul_ln113_fu_273_p10");
#endif

    }
}

max_pool::~max_pool() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete dut_mac_muladd_8neOg_U21;
    delete dut_mac_muladd_6nfYi_U22;
}

void max_pool::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln112_fu_361_p2.read()))) {
        c_0_reg_174 = c_reg_522.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln108_fu_307_p2.read()))) {
        c_0_reg_174 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln104_fu_226_p2.read(), ap_const_lv1_0))) {
        i_0_reg_105 = i_fu_232_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_105 = ap_const_lv13_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln107_fu_282_p2.read()))) {
        m_0_reg_116 = m_reg_468.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln104_fu_226_p2.read(), ap_const_lv1_1))) {
        m_0_reg_116 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln112_fu_361_p2.read()))) {
        max_0_reg_161 = max_1_reg_185.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln108_fu_307_p2.read()))) {
        max_0_reg_161 = ap_const_lv1_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln111_fu_341_p2.read()))) {
        max_1_reg_185 = max_0_reg_161.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        max_1_reg_185 = or_ln114_fu_396_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln107_fu_282_p2.read()))) {
        phi_mul_reg_127 = add_ln113_1_reg_460.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln104_fu_226_p2.read(), ap_const_lv1_1))) {
        phi_mul_reg_127 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln111_fu_341_p2.read()))) {
        r_0_reg_197 = ap_const_lv2_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        r_0_reg_197 = r_reg_530.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln108_fu_307_p2.read()))) {
        x_0_reg_139 = x_reg_486.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln106_fu_262_p2.read()))) {
        x_0_reg_139 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(icmp_ln107_fu_282_p2.read(), ap_const_lv1_0))) {
        y_0_reg_150 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln111_fu_341_p2.read()))) {
        y_0_reg_150 = y_reg_499.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln104_fu_226_p2.read(), ap_const_lv1_1))) {
        I_cast_reg_455 = I_cast_fu_246_p1.read();
        zext_ln113_1_reg_450 = zext_ln113_1_fu_243_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        O_reg_426 = I.read().range(4, 1);
        zext_ln109_reg_432 = zext_ln109_fu_218_p1.read();
        zext_ln113_reg_437 = zext_ln113_fu_222_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        add_ln113_1_reg_460 = add_ln113_1_fu_249_p2.read();
        m_reg_468 = m_fu_267_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        c_reg_522 = c_fu_347_p2.read();
        zext_ln111_reg_514 = zext_ln111_fu_337_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln106_fu_262_p2.read()))) {
        mul_ln113_reg_473 = mul_ln113_fu_273_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln108_fu_307_p2.read()))) {
        o_index_reg_504 = grp_fu_402_p3.read();
        zext_ln113_4_reg_509 = zext_ln113_4_fu_333_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        r_reg_530 = r_fu_367_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln112_fu_361_p2.read()))) {
        tmp5_reg_535 = tmp5_fu_379_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        x_reg_486 = x_fu_287_p2.read();
        zext_ln107_reg_478 = zext_ln107_fu_278_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        y_reg_499 = y_fu_312_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln107_fu_282_p2.read(), ap_const_lv1_0))) {
        zext_ln113_3_reg_491 = zext_ln113_3_fu_299_p1.read();
    }
}

void max_pool::thread_I_cast_fu_246_p1() {
    I_cast_fu_246_p1 = esl_zext<13,6>(I.read());
}

void max_pool::thread_O_fu_208_p4() {
    O_fu_208_p4 = I.read().range(4, 1);
}

void max_pool::thread_add_ln113_1_fu_249_p2() {
    add_ln113_1_fu_249_p2 = (!phi_mul_reg_127.read().is_01() || !zext_ln113_1_reg_450.read().is_01())? sc_lv<9>(): (sc_biguint<9>(phi_mul_reg_127.read()) + sc_biguint<9>(zext_ln113_1_reg_450.read()));
}

void max_pool::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void max_pool::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void max_pool::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void max_pool::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void max_pool::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void max_pool::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void max_pool::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void max_pool::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void max_pool::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void max_pool::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,1,1>(icmp_ln106_fu_262_p2.read(), ap_const_lv1_0)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void max_pool::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void max_pool::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln106_fu_262_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void max_pool::thread_c_fu_347_p2() {
    c_fu_347_p2 = (!c_0_reg_174.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(c_0_reg_174.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void max_pool::thread_grp_fu_402_p0() {
    grp_fu_402_p0 =  (sc_lv<8>) (grp_fu_402_p00.read());
}

void max_pool::thread_grp_fu_402_p00() {
    grp_fu_402_p00 = esl_zext<11,8>(tmp_fu_318_p2.read());
}

void max_pool::thread_grp_fu_402_p1() {
    grp_fu_402_p1 =  (sc_lv<4>) (zext_ln109_reg_432.read());
}

void max_pool::thread_grp_fu_402_p2() {
    grp_fu_402_p2 =  (sc_lv<4>) (zext_ln107_reg_478.read());
}

void max_pool::thread_grp_fu_408_p0() {
    grp_fu_408_p0 =  (sc_lv<6>) (I_cast_reg_455.read());
}

void max_pool::thread_grp_fu_408_p1() {
    grp_fu_408_p1 =  (sc_lv<9>) (grp_fu_408_p10.read());
}

void max_pool::thread_grp_fu_408_p10() {
    grp_fu_408_p10 = esl_zext<13,9>(tmp5_reg_535.read());
}

void max_pool::thread_grp_fu_408_p2() {
    grp_fu_408_p2 =  (sc_lv<4>) (zext_ln113_3_reg_491.read());
}

void max_pool::thread_i_fu_232_p2() {
    i_fu_232_p2 = (!i_0_reg_105.read().is_01() || !ap_const_lv13_1.is_01())? sc_lv<13>(): (sc_biguint<13>(i_0_reg_105.read()) + sc_biguint<13>(ap_const_lv13_1));
}

void max_pool::thread_i_index_fu_387_p2() {
    i_index_fu_387_p2 = (!zext_ln111_reg_514.read().is_01() || !grp_fu_408_p3.read().is_01())? sc_lv<13>(): (sc_biguint<13>(zext_ln111_reg_514.read()) + sc_biguint<13>(grp_fu_408_p3.read()));
}

void max_pool::thread_icmp_ln104_fu_226_p2() {
    icmp_ln104_fu_226_p2 = (!i_0_reg_105.read().is_01() || !ap_const_lv13_1440.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_105.read() == ap_const_lv13_1440);
}

void max_pool::thread_icmp_ln106_fu_262_p2() {
    icmp_ln106_fu_262_p2 = (!zext_ln106_fu_258_p1.read().is_01() || !M.read().is_01())? sc_lv<1>(): (sc_bigint<7>(zext_ln106_fu_258_p1.read()) < sc_bigint<7>(M.read()));
}

void max_pool::thread_icmp_ln107_fu_282_p2() {
    icmp_ln107_fu_282_p2 = (!x_0_reg_139.read().is_01() || !O_reg_426.read().is_01())? sc_lv<1>(): sc_lv<1>(x_0_reg_139.read() == O_reg_426.read());
}

void max_pool::thread_icmp_ln108_fu_307_p2() {
    icmp_ln108_fu_307_p2 = (!y_0_reg_150.read().is_01() || !O_reg_426.read().is_01())? sc_lv<1>(): sc_lv<1>(y_0_reg_150.read() == O_reg_426.read());
}

void max_pool::thread_icmp_ln111_fu_341_p2() {
    icmp_ln111_fu_341_p2 = (!c_0_reg_174.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(c_0_reg_174.read() == ap_const_lv2_2);
}

void max_pool::thread_icmp_ln112_fu_361_p2() {
    icmp_ln112_fu_361_p2 = (!r_0_reg_197.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(r_0_reg_197.read() == ap_const_lv2_2);
}

void max_pool::thread_input_r_address0() {
    input_r_address0 =  (sc_lv<13>) (zext_ln114_fu_391_p1.read());
}

void max_pool::thread_input_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        input_r_ce0 = ap_const_logic_1;
    } else {
        input_r_ce0 = ap_const_logic_0;
    }
}

void max_pool::thread_m_fu_267_p2() {
    m_fu_267_p2 = (!m_0_reg_116.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(m_0_reg_116.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void max_pool::thread_mul_ln113_fu_273_p0() {
    mul_ln113_fu_273_p0 =  (sc_lv<4>) (zext_ln113_reg_437.read());
}

void max_pool::thread_mul_ln113_fu_273_p1() {
    mul_ln113_fu_273_p1 =  (sc_lv<6>) (mul_ln113_fu_273_p10.read());
}

void max_pool::thread_mul_ln113_fu_273_p10() {
    mul_ln113_fu_273_p10 = esl_zext<8,6>(m_0_reg_116.read());
}

void max_pool::thread_mul_ln113_fu_273_p2() {
    mul_ln113_fu_273_p2 = (!mul_ln113_fu_273_p0.read().is_01() || !mul_ln113_fu_273_p1.read().is_01())? sc_lv<8>(): sc_biguint<4>(mul_ln113_fu_273_p0.read()) * sc_biguint<6>(mul_ln113_fu_273_p1.read());
}

void max_pool::thread_or_ln114_fu_396_p2() {
    or_ln114_fu_396_p2 = (input_r_q0.read() | max_1_reg_185.read());
}

void max_pool::thread_output_r_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_r_address0 =  (sc_lv<13>) (zext_ln117_fu_353_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        output_r_address0 =  (sc_lv<13>) (zext_ln104_fu_238_p1.read());
    } else {
        output_r_address0 = "XXXXXXXXXXXXX";
    }
}

void max_pool::thread_output_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void max_pool::thread_output_r_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_r_d0 = max_0_reg_161.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        output_r_d0 = ap_const_lv1_0;
    } else {
        output_r_d0 =  (sc_lv<1>) ("X");
    }
}

void max_pool::thread_output_r_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln104_fu_226_p2.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln111_fu_341_p2.read())))) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void max_pool::thread_r_fu_367_p2() {
    r_fu_367_p2 = (!r_0_reg_197.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(r_0_reg_197.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void max_pool::thread_shl_ln113_1_fu_327_p2() {
    shl_ln113_1_fu_327_p2 = (!ap_const_lv4_1.is_01())? sc_lv<4>(): y_0_reg_150.read() << (unsigned short)ap_const_lv4_1.to_uint();
}

void max_pool::thread_shl_ln113_fu_293_p2() {
    shl_ln113_fu_293_p2 = (!ap_const_lv4_1.is_01())? sc_lv<4>(): x_0_reg_139.read() << (unsigned short)ap_const_lv4_1.to_uint();
}

void max_pool::thread_tmp1_fu_373_p2() {
    tmp1_fu_373_p2 = (!zext_ln112_fu_357_p1.read().is_01() || !phi_mul_reg_127.read().is_01())? sc_lv<9>(): (sc_biguint<9>(zext_ln112_fu_357_p1.read()) + sc_biguint<9>(phi_mul_reg_127.read()));
}

void max_pool::thread_tmp5_fu_379_p2() {
    tmp5_fu_379_p2 = (!zext_ln113_4_reg_509.read().is_01() || !tmp1_fu_373_p2.read().is_01())? sc_lv<9>(): (sc_biguint<9>(zext_ln113_4_reg_509.read()) + sc_biguint<9>(tmp1_fu_373_p2.read()));
}

void max_pool::thread_tmp_fu_318_p2() {
    tmp_fu_318_p2 = (!zext_ln108_fu_303_p1.read().is_01() || !mul_ln113_reg_473.read().is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln108_fu_303_p1.read()) + sc_biguint<8>(mul_ln113_reg_473.read()));
}

void max_pool::thread_x_fu_287_p2() {
    x_fu_287_p2 = (!x_0_reg_139.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(x_0_reg_139.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void max_pool::thread_y_fu_312_p2() {
    y_fu_312_p2 = (!y_0_reg_150.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(y_0_reg_150.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void max_pool::thread_zext_ln104_fu_238_p1() {
    zext_ln104_fu_238_p1 = esl_zext<64,13>(i_0_reg_105.read());
}

void max_pool::thread_zext_ln106_fu_258_p1() {
    zext_ln106_fu_258_p1 = esl_zext<7,6>(m_0_reg_116.read());
}

void max_pool::thread_zext_ln107_fu_278_p1() {
    zext_ln107_fu_278_p1 = esl_zext<11,4>(x_0_reg_139.read());
}

void max_pool::thread_zext_ln108_fu_303_p1() {
    zext_ln108_fu_303_p1 = esl_zext<8,4>(y_0_reg_150.read());
}

void max_pool::thread_zext_ln109_fu_218_p1() {
    zext_ln109_fu_218_p1 = esl_zext<11,4>(O_fu_208_p4.read());
}

void max_pool::thread_zext_ln111_fu_337_p1() {
    zext_ln111_fu_337_p1 = esl_zext<13,2>(c_0_reg_174.read());
}

void max_pool::thread_zext_ln112_fu_357_p1() {
    zext_ln112_fu_357_p1 = esl_zext<9,2>(r_0_reg_197.read());
}

void max_pool::thread_zext_ln113_1_fu_243_p1() {
    zext_ln113_1_fu_243_p1 = esl_zext<9,6>(I.read());
}

void max_pool::thread_zext_ln113_3_fu_299_p1() {
    zext_ln113_3_fu_299_p1 = esl_zext<13,4>(shl_ln113_fu_293_p2.read());
}

void max_pool::thread_zext_ln113_4_fu_333_p1() {
    zext_ln113_4_fu_333_p1 = esl_zext<9,4>(shl_ln113_1_fu_327_p2.read());
}

void max_pool::thread_zext_ln113_fu_222_p1() {
    zext_ln113_fu_222_p1 = esl_zext<8,4>(O_fu_208_p4.read());
}

void max_pool::thread_zext_ln114_fu_391_p1() {
    zext_ln114_fu_391_p1 = esl_zext<64,13>(i_index_fu_387_p2.read());
}

void max_pool::thread_zext_ln117_fu_353_p1() {
    zext_ln117_fu_353_p1 = esl_zext<64,11>(o_index_reg_504.read());
}

void max_pool::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln104_fu_226_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln106_fu_262_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln107_fu_282_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln108_fu_307_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln111_fu_341_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln112_fu_361_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<9>) ("XXXXXXXXX");
            break;
    }
}

}

