-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dut is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    strm_in_V_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    strm_in_V_V_empty_n : IN STD_LOGIC;
    strm_in_V_V_read : OUT STD_LOGIC;
    strm_out_V_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    strm_out_V_V_full_n : IN STD_LOGIC;
    strm_out_V_V_write : OUT STD_LOGIC );
end;


architecture behav of dut is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "dut,hls_ip_2019_2_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=11.313500,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=23,HLS_SYN_DSP=11,HLS_SYN_FF=2151,HLS_SYN_LUT=4740,HLS_VERSION=2019_2_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal strm_in_V_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln29_fu_167_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal strm_out_V_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal i_fu_173_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_reg_232 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal tmp_V_2_reg_237 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln_fu_183_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln_reg_242 : STD_LOGIC_VECTOR (7 downto 0);
    signal j_fu_205_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal input_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal input_ce0 : STD_LOGIC;
    signal input_we0 : STD_LOGIC;
    signal input_d0 : STD_LOGIC_VECTOR (0 downto 0);
    signal input_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_bnn_xcel_fu_145_ap_start : STD_LOGIC;
    signal grp_bnn_xcel_fu_145_ap_done : STD_LOGIC;
    signal grp_bnn_xcel_fu_145_ap_idle : STD_LOGIC;
    signal grp_bnn_xcel_fu_145_ap_ready : STD_LOGIC;
    signal grp_bnn_xcel_fu_145_input_r_address0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_bnn_xcel_fu_145_input_r_ce0 : STD_LOGIC;
    signal grp_bnn_xcel_fu_145_ap_return : STD_LOGIC_VECTOR (31 downto 0);
    signal i_0_reg_123 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln31_fu_199_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Hi_assign_reg_134 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_bnn_xcel_fu_145_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state2_ignore_call0 : BOOLEAN;
    signal zext_ln32_fu_224_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln32_fu_179_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln31_1_fu_195_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln31_fu_191_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln32_fu_219_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);

    component bnn_xcel IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_r_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        input_r_ce0 : OUT STD_LOGIC;
        input_r_q0 : IN STD_LOGIC_VECTOR (0 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component bnn_xcel_mem_conv1 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (12 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (0 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    input_U : component bnn_xcel_mem_conv1
    generic map (
        DataWidth => 1,
        AddressRange => 5184,
        AddressWidth => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => input_address0,
        ce0 => input_ce0,
        we0 => input_we0,
        d0 => input_d0,
        q0 => input_q0);

    grp_bnn_xcel_fu_145 : component bnn_xcel
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_bnn_xcel_fu_145_ap_start,
        ap_done => grp_bnn_xcel_fu_145_ap_done,
        ap_idle => grp_bnn_xcel_fu_145_ap_idle,
        ap_ready => grp_bnn_xcel_fu_145_ap_ready,
        input_r_address0 => grp_bnn_xcel_fu_145_input_r_address0,
        input_r_ce0 => grp_bnn_xcel_fu_145_input_r_ce0,
        input_r_q0 => input_q0,
        ap_return => grp_bnn_xcel_fu_145_ap_return);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_bnn_xcel_fu_145_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_bnn_xcel_fu_145_ap_start_reg <= ap_const_logic_0;
            else
                if ((not(((icmp_ln29_fu_167_p2 = ap_const_lv1_0) and (strm_in_V_V_empty_n = ap_const_logic_0))) and (icmp_ln29_fu_167_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_bnn_xcel_fu_145_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_bnn_xcel_fu_145_ap_ready = ap_const_logic_1)) then 
                    grp_bnn_xcel_fu_145_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    Hi_assign_reg_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln31_fu_199_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                Hi_assign_reg_134 <= j_fu_205_p2;
            elsif ((not(((icmp_ln29_fu_167_p2 = ap_const_lv1_0) and (strm_in_V_V_empty_n = ap_const_logic_0))) and (icmp_ln29_fu_167_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                Hi_assign_reg_134 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    i_0_reg_123_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln31_fu_199_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_0_reg_123 <= i_reg_232;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_0_reg_123 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((icmp_ln29_fu_167_p2 = ap_const_lv1_0) and (strm_in_V_V_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                i_reg_232 <= i_fu_173_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((icmp_ln29_fu_167_p2 = ap_const_lv1_0) and (strm_in_V_V_empty_n = ap_const_logic_0))) and (icmp_ln29_fu_167_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    shl_ln_reg_242(7 downto 5) <= shl_ln_fu_183_p3(7 downto 5);
                tmp_V_2_reg_237 <= strm_in_V_V_dout;
            end if;
        end if;
    end process;
    shl_ln_reg_242(4 downto 0) <= "00000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, strm_in_V_V_empty_n, strm_out_V_V_full_n, ap_CS_fsm_state2, icmp_ln29_fu_167_p2, ap_CS_fsm_state4, ap_CS_fsm_state3, grp_bnn_xcel_fu_145_ap_done, icmp_ln31_fu_199_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((icmp_ln29_fu_167_p2 = ap_const_lv1_0) and (strm_in_V_V_empty_n = ap_const_logic_0))) and (icmp_ln29_fu_167_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                elsif ((not(((icmp_ln29_fu_167_p2 = ap_const_lv1_0) and (strm_in_V_V_empty_n = ap_const_logic_0))) and (icmp_ln29_fu_167_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln31_fu_199_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if ((not(((grp_bnn_xcel_fu_145_ap_done = ap_const_logic_0) or (strm_out_V_V_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln32_fu_219_p2 <= std_logic_vector(unsigned(zext_ln31_fu_191_p1) + unsigned(shl_ln_reg_242));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_block_state2_assign_proc : process(strm_in_V_V_empty_n, icmp_ln29_fu_167_p2)
    begin
                ap_block_state2 <= ((icmp_ln29_fu_167_p2 = ap_const_lv1_0) and (strm_in_V_V_empty_n = ap_const_logic_0));
    end process;


    ap_block_state2_ignore_call0_assign_proc : process(strm_in_V_V_empty_n, icmp_ln29_fu_167_p2)
    begin
                ap_block_state2_ignore_call0 <= ((icmp_ln29_fu_167_p2 = ap_const_lv1_0) and (strm_in_V_V_empty_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(strm_out_V_V_full_n, ap_CS_fsm_state4, grp_bnn_xcel_fu_145_ap_done)
    begin
        if ((not(((grp_bnn_xcel_fu_145_ap_done = ap_const_logic_0) or (strm_out_V_V_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(strm_out_V_V_full_n, ap_CS_fsm_state4, grp_bnn_xcel_fu_145_ap_done)
    begin
        if ((not(((grp_bnn_xcel_fu_145_ap_done = ap_const_logic_0) or (strm_out_V_V_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_bnn_xcel_fu_145_ap_start <= grp_bnn_xcel_fu_145_ap_start_reg;
    i_fu_173_p2 <= std_logic_vector(unsigned(i_0_reg_123) + unsigned(ap_const_lv4_1));
    icmp_ln29_fu_167_p2 <= "1" when (i_0_reg_123 = ap_const_lv4_8) else "0";
    icmp_ln31_fu_199_p2 <= "1" when (Hi_assign_reg_134 = ap_const_lv6_20) else "0";

    input_address0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state3, grp_bnn_xcel_fu_145_input_r_address0, zext_ln32_fu_224_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_address0 <= zext_ln32_fu_224_p1(13 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_address0 <= grp_bnn_xcel_fu_145_input_r_address0;
        else 
            input_address0 <= "XXXXXXXXXXXXX";
        end if; 
    end process;


    input_ce0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state3, grp_bnn_xcel_fu_145_input_r_ce0)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_ce0 <= grp_bnn_xcel_fu_145_input_r_ce0;
        else 
            input_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    input_d0 <= tmp_V_2_reg_237(to_integer(unsigned(zext_ln31_1_fu_195_p1)) downto to_integer(unsigned(zext_ln31_1_fu_195_p1))) when (to_integer(unsigned(zext_ln31_1_fu_195_p1))>= 0 and to_integer(unsigned(zext_ln31_1_fu_195_p1))<=31) else "-";

    input_we0_assign_proc : process(ap_CS_fsm_state3, icmp_ln31_fu_199_p2)
    begin
        if (((icmp_ln31_fu_199_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            input_we0 <= ap_const_logic_1;
        else 
            input_we0 <= ap_const_logic_0;
        end if; 
    end process;

    j_fu_205_p2 <= std_logic_vector(unsigned(Hi_assign_reg_134) + unsigned(ap_const_lv6_1));
    shl_ln_fu_183_p3 <= (trunc_ln32_fu_179_p1 & ap_const_lv5_0);

    strm_in_V_V_blk_n_assign_proc : process(strm_in_V_V_empty_n, ap_CS_fsm_state2, icmp_ln29_fu_167_p2)
    begin
        if (((icmp_ln29_fu_167_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            strm_in_V_V_blk_n <= strm_in_V_V_empty_n;
        else 
            strm_in_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    strm_in_V_V_read_assign_proc : process(strm_in_V_V_empty_n, ap_CS_fsm_state2, icmp_ln29_fu_167_p2)
    begin
        if ((not(((icmp_ln29_fu_167_p2 = ap_const_lv1_0) and (strm_in_V_V_empty_n = ap_const_logic_0))) and (icmp_ln29_fu_167_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            strm_in_V_V_read <= ap_const_logic_1;
        else 
            strm_in_V_V_read <= ap_const_logic_0;
        end if; 
    end process;


    strm_out_V_V_blk_n_assign_proc : process(strm_out_V_V_full_n, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            strm_out_V_V_blk_n <= strm_out_V_V_full_n;
        else 
            strm_out_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    strm_out_V_V_din <= grp_bnn_xcel_fu_145_ap_return;

    strm_out_V_V_write_assign_proc : process(strm_out_V_V_full_n, ap_CS_fsm_state4, grp_bnn_xcel_fu_145_ap_done)
    begin
        if ((not(((grp_bnn_xcel_fu_145_ap_done = ap_const_logic_0) or (strm_out_V_V_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            strm_out_V_V_write <= ap_const_logic_1;
        else 
            strm_out_V_V_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln32_fu_179_p1 <= i_0_reg_123(3 - 1 downto 0);
    zext_ln31_1_fu_195_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Hi_assign_reg_134),32));
    zext_ln31_fu_191_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(Hi_assign_reg_134),8));
    zext_ln32_fu_224_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln32_fu_219_p2),64));
end behav;
